In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"D:\Khushi\[XB3421] Data Extraction For USA Counties_Virec\us\texas\harris\prop\Raw_Data\us_tx_48201_data_prop_building-summary_bronze_20260501.csv")
df

C:\Users\khushi.limbachiya\AppData\Local\Temp\ipykernel_17648\1318872480.py:1: DtypeWarning: Columns (1,2,4,6,7,9,10,11,14,15,17,18,20,21,23,24,26,27,29,30,32,33,34,35,37,38,39,42,45,46,47,48,51,53,56,59,60,63,69,71,73,75,77,79,82,83,84,86,87,89,90,91,92,95,98,101,102,103,104,105,106,107,109,110,111,112,115,118,121,123,127,128,129,139,140,145,147,152,153,157,162,163) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"D:\Khushi\[XB3421] Data Extraction For USA Counties_Virec\us\texas\harris\prop\Raw_Data\us_tx_48201_data_prop_building-summary_bronze_20260501.csv")

,parcel_number,leed_certification_level,open_frame_porch_pri,elev_hydro_pass,basement,fireplace_open_1,unfin_basement_lwr,util_bldg_frm_c,frame_overhang_upr,one_story_mas_lwr,...,base_value_medium_tank,bank_vault_no_door,frame_util_bldg_lwr,elev_hydro_frght,functional_utility,grade_adjustment,physical_condition,open_frame_porch_upr,parking_garage_upper_level_c,page_save
0,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2021.html
1,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2021.html
2,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2021.html
3,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2021.html
4,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2022.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4988247,1321770010001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1321770010001_2026.html
4988248,1321770010001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1321770010001_2026.html
4988249,1321770010001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1321770010001_2026.html
4988250,1321770010001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1321770010001_2026.html
4988251,1321770010001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1321770010001_2026.html

In [3]:
df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4988252 entries, 0 to 4988251
Data columns (total 165 columns):
 #    Column                                Non-Null Count    Dtype
---   ------                                --------------    -----
 0    parcel_number                         4988252 non-null  int64
 1    leed_certification_level              541 non-null      object
 2    open_frame_porch_pri                  2615132 non-null  object
 3    elev_hydro_pass                       3790 non-null     float64
 4    basement                              1454 non-null     object
 5    fireplace_open_1                      697 non-null      float64
 6    unfin_basement_lwr                    579 non-null      object
 7    util_bldg_frm_c                       8731 non-null     object
 8    frame_overhang_upr                    118276 non-null   float64
 9    one_story_mas_lwr                     956 non-null      object
 10   living_area_lwr                       1271 non-null     object
 11   garage_interior_parking_apartments_c  4456 non-null     object
 12   parking_spaces                        1025 non-null     float64
 13   store_front_metal                     20503 non-null    float64
 14   unfin_l_a_upper                       2572 non-null     object
 15   mobile_home_8_11_width                2367 non-null     object
 16   economic_obsolescence                 491169 non-null   object
 17   cnpy_roof_ss_ave_c                    1891 non-null     object
 18   mobile_home_30_width                  2639 non-null     object
 19   base_value_small_tank                 3978 non-null     float64
 20   canopy_lwr                            16114 non-null    object
 21   garage_att_frm_c                      4667 non-null     object
 22   cost_and_design                       1153901 non-null  object
 23   unfin_l_a_primary                     526 non-null      object
 24   attic_finished                        130021 non-null   object
 25   cond_desir_util                       4472728 non-null  object
 26   masonry_terrace_pri                   27393 non-null    object
 27   bank_canopy_c                         3578 non-null     object
 28   basement_top                          62 non-null       float64
 29   one_story_frame_upr                   407718 non-null   object
 30   enclosed_entry_c                      1177 non-null     object
 31   datetime                              4988252 non-null  object
 32   masonry_bay_pri                       37557 non-null    object
 33   encl_frame_porch_upr                  1828 non-null     object
 34   cnpy_roof_ss_eco_c                    678 non-null      object
 35   comm_condo_neighborhood               6993 non-null     object
 36   fireplace_masonry_firebrick           892900 non-null   float64
 37   basement_c                            539 non-null      object
 38   mas_brk_garage_pri                    2101497 non-null  object
 39   mobile_home_12_14_width               28882 non-null    object
 40   oh_door_motor_rs                      916 non-null      float64
 41   quality                               4988252 non-null  object
 42   mas_conc_patio_pri                    593313 non-null   object
 43   fireplace_direct_vent                 108980 non-null   float64
 44   bank_drive_thru                       1355 non-null     float64
 45   canopy_pri                            153376 non-null   object
 46   frame_garage_pri                      496304 non-null   object
 47   dock_level_floor_c                    174 non-null      object
 48   mobile_home_15_19_width               12042 non-null    object
 49   fireplace_adl_open                    18317 non-null    float64
 50   room_rec                              1587644 non-null  float64
 51   cnpy_roof_ss_gd_c                     2065 non-null     object
 52   interior_finish_percent               464550 non-null   float64
 53   one_story_frame_pri                   535971 non-null   object
 54   medical_beds                          486 non-null      float64
 55   heating_ac                            4131626 non-null  object
 56   energy_star_certification             832 non-null      object
 57   year                                  4988252 non-null  int64
 58   exterior_wall                         4959775 non-null  object
 59   base_area_lwr                         76432 non-null    object
 60   masonry_bay_upr                       1400 non-null     object
 61   room_full_bath                        4472412 non-null  float64
 62   store_front_wood                      1465 non-null     float64
 63   util_bldg_mtl_c                       2870 non-null     object
 64   masonry_overhang_upr                  4238 non-null     float64
 65   oh_door_motor_w_m                     1384 non-null     float64
 66   plumbing_type                         440921 non-null   object
 67   base_area_upr                         1684872 non-null  object
 68   oh_door_roll_steel                    31230 non-null    float64
 69   mobile_home_20_29_width               15395 non-null    object
 70   atrium                                6445 non-null     float64
 71   open_mas_porch_upr                    31134 non-null    object
 72   heating_type                          333887 non-null   object
 73   masonry_overhang_pri                  1200 non-null     object
 74   miscellaneous                         540 non-null      float64
 75   one_story_mas_upr                     115162 non-null   object
 76   office_warehouse_ratio                60613 non-null    float64
 77   wood_deck_lwr                         1472 non-null     object
 78   elevator_stops                        17409 non-null    float64
 79   open_mas_porch_pri                    1474209 non-null  object
 80   elev_elect_pass                       9804 non-null     float64
 81   style                                 4988252 non-null  object
 82   mas_conc_patio_lwr                    4209 non-null     object
 83   construction_type                     24267 non-null    object
 84   carport_c                             4802 non-null     object
 85   base_value_large_tank                 701 non-null      float64
 86   sprinkler_type                        43403 non-null    object
 87   porch_enclosed_c                      3534 non-null     object
 88   building_number                       4988252 non-null  int64
 89   stone_tile_patio_upper                4508 non-null     object
 90   area_hirise_ofc_c                     64 non-null       object
 91   mas_brk_garage_lwr                    24574 non-null    object
 92   encl_frame_porch_pri                  121662 non-null   object
 93   year_built                            4988252 non-null  int64
 94   masonry_trim                          128032 non-null   float64
 95   encl_mas_porch_pri                    9256 non-null     object
 96   base_area_pri                         4920170 non-null  object
 97   impr_sq_ft                            4733883 non-null  object
 98   stone_tile_patio_pri                  33688 non-null    object
 99   oh_door_wood_mtl                      107258 non-null   float64
 100  base_value_tiny_tank                  7687 non-null     float64
 101  market_adjustment                     87495 non-null    object
 102  half_story_mas_upr                    2047 non-null     object
 103  ldng_ramp_conc_c                      1705 non-null     object
 104  frame_garage_lwr                      77382 non-null    object
 105  carport_lwr                           5086 non-null     object
 106  truck_train_wells_c                   3899 non-null     object
 107  open_mas_porch_lwr                    11738 non-null    object
 108  apt_3_bedroom_unit                    8717 non-null     float64
 109  half_story_frame_upr                  7326 non-null     object
 110  carport_pri                           189321 non-null   object
 111  wood_deck_upr                         29703 non-null    object
 112  cnpy_only_c                           26752 non-null    object
 113  frame_overhang_pri                    8110 non-null     float64
 114  retry                                 0 non-null        float64
 115  one_story_mas_pri                     677420 non-null   object
 116  apt_effcncy_unit                      2782 non-null     float64
 117  sprinkler_wet                         2461 non-null     float64
 118  attic_unfinished                      24263 non-null    object
 119  number_of_apartment_units             1684 non-null     float64
 120  foundation_type                       4472730 non-null  object
 121  cnpy_roof_w_slab_c                    117468 non-null   object
 122  craneway_5_ton                        654 non-null      float64
 123  masnry_util_bldg_pri                  10992 non-null    object
 124  partition_type                        446997 non-null   object
 125  net_rentable_area                     1068 non-null     float64
 126  room_half_bath                        1761052 non-null  float64
 127  wood_deck_pri                         160941 non-null   object
 128  porch_open_c                          110041 non-null   object
 129  parking_garage_c                      1612 non-null     object
 130  type                                  4988252 non-null  object
 131  frame_bay_pri                         15464 non-null    float64
 132  stories                               44838 non-null    float64
 133  cooling_type                          311928 non-null   object
 134  apt_1_bedroom_unit                    34940 non-null    float64
 135  franchise_code                        10080 non-null    float64
 136  wall_height                           345669 non-null   float64
 137  apt_2_bedroom_unit                    36675 non-null    float64
 138  wall_height_enclosure                 148762 non-null   float64
 139  garage_att_mas_c                      1024 non-null     object
 140  perimeter                             566 non-null      object
 141  room_total                            4472521 non-null  float64
 142  elev_elect_frght                      3925 non-null     float64
 143  room_bedroom                          4472840 non-null  float64
 144  building_details                      4985587 non-null  object
 145  frame_util_bldg_upr                   2094 non-null     object
 146  fireplace_metal_prefab                1478397 non-null  float64
 147  open_frame_porch_lwr                  34349 non-null    object
 148  escalator_48                          203 non-null      float64
 149  remodeled                             4988234 non-null  object
 150  market_index_adjustment               470798 non-null   object
 151  ip                                    4988252 non-null  object
 152  frame_util_bldg_pri                   74298 non-null    object
 153  porch_open_upr_c                      89188 non-null    object
 154  frame_bay_upr                         2135 non-null     float64
 155  base_value_medium_tank                6236 non-null     float64
 156  bank_vault_no_door                    662 non-null      float64
 157  frame_util_bldg_lwr                   4171 non-null     object
 158  elev_hydro_frght                      658 non-null      float64
 159  functional_utility                    489806 non-null   object
 160  grade_adjustment                      4474587 non-null  object
 161  physical_condition                    4964694 non-null  object
 162  open_frame_porch_upr                  116118 non-null   object
 163  parking_garage_upper_level_c          1315 non-null     object
 164  page_save                             4988252 non-null  object
dtypes: float64(54), int64(4), object(107)
memory usage: 6.1+ GB

In [4]:
# Define fake null values
fake_nulls = ['',' ' ,'null', 'none', 'nan', "None", 'na', 'n/a', 'n.a.', 'NaN', 'NAN', 'NULL', 'nil', 'Nan', 'Null',"NONE"]

# ✅ Now check and replace in all columns
for col in df.columns:
    mask = df[col].astype(str).str.lower().isin([str(x).lower() for x in fake_nulls])
    problem_rows = df.loc[mask, [col]]

    if not problem_rows.empty:
        print(f"Rows where '{col}' has fake nulls:")
        print(problem_rows)

        df[col] = df[col].replace(fake_nulls, np.nan)
print("\nNaN count per column:")

print(df.isna().sum())
print("\nCleaned DataFrame:")
print(df)

Rows where 'leed_certification_level' has fake nulls:
        leed_certification_level
0                            NaN
1                            NaN
2                            NaN
3                            NaN
4                            NaN
...                          ...
4988247                      NaN
4988248                      NaN
4988249                      NaN
4988250                      NaN
4988251                      NaN

[4987711 rows x 1 columns]
Rows where 'open_frame_porch_pri' has fake nulls:
        open_frame_porch_pri
0                        NaN
1                        NaN
2                        NaN
3                        NaN
4                        NaN
...                      ...
4988247                  NaN
4988248                  NaN
4988249                  NaN
4988250                  NaN
4988251                  NaN

[2373120 rows x 1 columns]
Rows where 'elev_hydro_pass' has fake nulls:
         elev_hydro_pass
0                    NaN
1                    NaN
2                    NaN
3                    NaN
4                    NaN
...                  ...
4988247              NaN
4988248              NaN
4988249              NaN
4988250              NaN
4988251              NaN

[4984462 rows x 1 columns]
Rows where 'basement' has fake nulls:
        basement
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
...          ...
4988247      NaN
4988248      NaN
4988249      NaN
4988250      NaN
4988251      NaN

[4986798 rows x 1 columns]
Rows where 'fireplace_open_1' has fake nulls:
         fireplace_open_1
0                     NaN
1                     NaN
2                     NaN
3                     NaN
4                     NaN
...                   ...
4988247               NaN
4988248               NaN
4988249               NaN
4988250               NaN
4988251               NaN

[4987555 rows x 1 columns]
Rows where 'unfin_basement_lwr' has fake nulls:
        unfin_basement_lwr
0                      NaN
1                      NaN
2                      NaN
3                      NaN
4                      NaN
...                    ...
4988247                NaN
4988248                NaN
4988249                NaN
4988250                NaN
4988251                NaN

[4987673 rows x 1 columns]
Rows where 'util_bldg_frm_c' has fake nulls:
        util_bldg_frm_c
0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   NaN
...                 ...
4988247             NaN
4988248             NaN
4988249             NaN
4988250             NaN
4988251             NaN

[4979521 rows x 1 columns]
Rows where 'frame_overhang_upr' has fake nulls:
         frame_overhang_upr
0                       NaN
1                       NaN
2                       NaN
3                       NaN
4                       NaN
...                     ...
4988247                 NaN
4988248                 NaN
4988249                 NaN
4988250                 NaN
4988251                 NaN

[4869976 rows x 1 columns]
Rows where 'one_story_mas_lwr' has fake nulls:
        one_story_mas_lwr
0                     NaN
1                     NaN
2                     NaN
3                     NaN
4                     NaN
...                   ...
4988247               NaN
4988248               NaN
4988249               NaN
4988250               NaN
4988251               NaN

[4987296 rows x 1 columns]
Rows where 'living_area_lwr' has fake nulls:
        living_area_lwr
0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   NaN
...                 ...
4988247             NaN
4988248             NaN
4988249             NaN
4988250             NaN
4988251             NaN

[4986981 rows x 1 columns]
Rows where 'garage_interior_parking_apartments_c' has fake nulls:
        garage_interior_parking_apartments_c
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN
...                                      ...
4988247                                  NaN
4988248                                  NaN
4988249                                  NaN
4988250                                  NaN
4988251                                  NaN

[4983796 rows x 1 columns]
Rows where 'parking_spaces' has fake nulls:
         parking_spaces
0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   NaN
...                 ...
4988247             NaN
4988248             NaN
4988249             NaN
4988250             NaN
4988251             NaN

[4987227 rows x 1 columns]
Rows where 'store_front_metal' has fake nulls:
         store_front_metal
2                      NaN
3                      NaN
6                      NaN
7                      NaN
10                     NaN
...                    ...
4988247                NaN
4988248                NaN
4988249                NaN
4988250                NaN
4988251                NaN

[4967749 rows x 1 columns]
Rows where 'unfin_l_a_upper' has fake nulls:
        unfin_l_a_upper
0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   NaN
...                 ...
4988247             NaN
4988248             NaN
4988249             NaN
4988250             NaN
4988251             NaN

[4985680 rows x 1 columns]
Rows where 'mobile_home_8_11_width' has fake nulls:
        mobile_home_8_11_width
0                          NaN
1                          NaN
2                          NaN
3                          NaN
4                          NaN
...                        ...
4988247                    NaN
4988248                    NaN
4988249                    NaN
4988250                    NaN
4988251                    NaN

[4985885 rows x 1 columns]
Rows where 'economic_obsolescence' has fake nulls:
        economic_obsolescence
24                        NaN
25                        NaN
26                        NaN
27                        NaN
28                        NaN
...                       ...
4987961                   NaN
4987979                   NaN
4987980                   NaN
4987983                   NaN
4987984                   NaN

[4497083 rows x 1 columns]
Rows where 'cnpy_roof_ss_ave_c' has fake nulls:
        cnpy_roof_ss_ave_c
0                      NaN
1                      NaN
2                      NaN
3                      NaN
4                      NaN
...                    ...
4988247                NaN
4988248                NaN
4988249                NaN
4988250                NaN
4988251                NaN

[4986361 rows x 1 columns]
Rows where 'mobile_home_30_width' has fake nulls:
        mobile_home_30_width
0                        NaN
1                        NaN
2                        NaN
3                        NaN
4                        NaN
...                      ...
4988247                  NaN
4988248                  NaN
4988249                  NaN
4988250                  NaN
4988251                  NaN

[4985613 rows x 1 columns]
Rows where 'base_value_small_tank' has fake nulls:
         base_value_small_tank
0                          NaN
1                          NaN
2                          NaN
3                          NaN
4                          NaN
...                        ...
4988247                    NaN
4988248                    NaN
4988249                    NaN
4988250                    NaN
4988251                    NaN

[4984274 rows x 1 columns]
Rows where 'canopy_lwr' has fake nulls:
        canopy_lwr
0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
...            ...
4988247        NaN
4988248        NaN
4988249        NaN
4988250        NaN
4988251        NaN

[4972138 rows x 1 columns]
Rows where 'garage_att_frm_c' has fake nulls:
        garage_att_frm_c
0                    NaN
1                    NaN
2                    NaN
3                    NaN
4                    NaN
...                  ...
4988231              NaN
4988232              NaN
4988233              NaN
4988234              NaN
4988236              NaN

[4983585 rows x 1 columns]
Rows where 'cost_and_design' has fake nulls:
        cost_and_design
0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   NaN
...                 ...
4988247             NaN
4988248             NaN
4988249             NaN
4988250             NaN
4988251             NaN

[3834351 rows x 1 columns]
Rows where 'unfin_l_a_primary' has fake nulls:
        unfin_l_a_primary
0                     NaN
1                     NaN
2                     NaN
3                     NaN
4                     NaN
...                   ...
4988247               NaN
4988248               NaN
4988249               NaN
4988250               NaN
4988251               NaN

[4987726 rows x 1 columns]
Rows where 'attic_finished' has fake nulls:
        attic_finished
0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN
...                ...
4988247            NaN
4988248            NaN
4988249            NaN
4988250            NaN
4988251            NaN

[4858231 rows x 1 columns]
Rows where 'cond_desir_util' has fake nulls:
        cond_desir_util
0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   NaN
...                 ...
4988247             NaN
4988248             NaN
4988249             NaN
4988250             NaN
4988251             NaN

[515524 rows x 1 columns]
Rows where 'masonry_terrace_pri' has fake nulls:
        masonry_terrace_pri
0                       NaN
1                       NaN
2                       NaN
3                       NaN
4                       NaN
...                     ...
4988247                 NaN
4988248                 NaN
4988249                 NaN
4988250                 NaN
4988251                 NaN

[4960859 rows x 1 columns]
Rows where 'bank_canopy_c' has fake nulls:
        bank_canopy_c
0                 NaN
1                 NaN
2                 NaN
3                 NaN
4                 NaN
...               ...
4988247           NaN
4988248           NaN
4988249           NaN
4988250           NaN
4988251           NaN

[4984674 rows x 1 columns]
Rows where 'basement_top' has fake nulls:
         basement_top
0                 NaN
1                 NaN
2                 NaN
3                 NaN
4                 NaN
...               ...
4988247           NaN
4988248           NaN
4988249           NaN
4988250           NaN
4988251           NaN

[4988190 rows x 1 columns]
Rows where 'one_story_frame_upr' has fake nulls:
        one_story_frame_upr
0                       NaN
1                       NaN
2                       NaN
3                       NaN
4                       NaN
...                     ...
4988247                 NaN
4988248                 NaN
4988249                 NaN
4988250                 NaN
4988251                 NaN

[4580534 rows x 1 columns]
Rows where 'enclosed_entry_c' has fake nulls:
        enclosed_entry_c
0                    NaN
1                    NaN
2                    NaN
3                    NaN
4                    NaN
...                  ...
4988247              NaN
4988248              NaN
4988249              NaN
4988250              NaN
4988251              NaN

[4987075 rows x 1 columns]
Rows where 'masonry_bay_pri' has fake nulls:
        masonry_bay_pri
0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   NaN
...                 ...
4988247             NaN
4988248             NaN
4988249             NaN
4988250             NaN
4988251             NaN

[4950695 rows x 1 columns]
Rows where 'encl_frame_porch_upr' has fake nulls:
        encl_frame_porch_upr
0                        NaN
1                        NaN
2                        NaN
3                        NaN
4                        NaN
...                      ...
4988247                  NaN
4988248                  NaN
4988249                  NaN
4988250                  NaN
4988251                  NaN

[4986424 rows x 1 columns]
Rows where 'cnpy_roof_ss_eco_c' has fake nulls:
        cnpy_roof_ss_eco_c
0                      NaN
1                      NaN
2                      NaN
3                      NaN
4                      NaN
...                    ...
4988247                NaN
4988248                NaN
4988249                NaN
4988250                NaN
4988251                NaN

[4987574 rows x 1 columns]
Rows where 'comm_condo_neighborhood' has fake nulls:
        comm_condo_neighborhood
0                           NaN
1                           NaN
2                           NaN
3                           NaN
4                           NaN
...                         ...
4988247                     NaN
4988248                     NaN
4988249                     NaN
4988250                     NaN
4988251                     NaN

[4981259 rows x 1 columns]
Rows where 'fireplace_masonry_firebrick' has fake nulls:
         fireplace_masonry_firebrick
0                                NaN
1                                NaN
2                                NaN
3                                NaN
4                                NaN
...                              ...
4988247                          NaN
4988248                          NaN
4988249                          NaN
4988250                          NaN
4988251                          NaN

[4095352 rows x 1 columns]
Rows where 'basement_c' has fake nulls:
        basement_c
0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
...            ...
4988247        NaN
4988248        NaN
4988249        NaN
4988250        NaN
4988251        NaN

[4987713 rows x 1 columns]
Rows where 'mas_brk_garage_pri' has fake nulls:
        mas_brk_garage_pri
0                      NaN
1                      NaN
2                      NaN
3                      NaN
4                      NaN
...                    ...
4988247                NaN
4988248                NaN
4988249                NaN
4988250                NaN
4988251                NaN

[2886755 rows x 1 columns]
Rows where 'mobile_home_12_14_width' has fake nulls:
        mobile_home_12_14_width
0                           NaN
1                           NaN
2                           NaN
3                           NaN
4                           NaN
...                         ...
4988247                     NaN
4988248                     NaN
4988249                     NaN
4988250                     NaN
4988251                     NaN

[4959370 rows x 1 columns]
Rows where 'oh_door_motor_rs' has fake nulls:
         oh_door_motor_rs
0                     NaN
1                     NaN
2                     NaN
3                     NaN
4                     NaN
...                   ...
4988247               NaN
4988248               NaN
4988249               NaN
4988250               NaN
4988251               NaN

[4987336 rows x 1 columns]
Rows where 'mas_conc_patio_pri' has fake nulls:
        mas_conc_patio_pri
0                      NaN
1                      NaN
2                      NaN
3                      NaN
4                      NaN
...                    ...
4988247                NaN
4988248                NaN
4988249                NaN
4988250                NaN
4988251                NaN

[4394939 rows x 1 columns]
Rows where 'fireplace_direct_vent' has fake nulls:
         fireplace_direct_vent
0                          NaN
1                          NaN
2                          NaN
3                          NaN
4                          NaN
...                        ...
4988247                    NaN
4988248                    NaN
4988249                    NaN
4988250                    NaN
4988251                    NaN

[4879272 rows x 1 columns]
Rows where 'bank_drive_thru' has fake nulls:
         bank_drive_thru
0                    NaN
1                    NaN
2                    NaN
3                    NaN
4                    NaN
...                  ...
4988247              NaN
4988248              NaN
4988249              NaN
4988250              NaN
4988251              NaN

[4986897 rows x 1 columns]
Rows where 'canopy_pri' has fake nulls:
        canopy_pri
0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
...            ...
4988247        NaN
4988248        NaN
4988249        NaN
4988250        NaN
4988251        NaN

[4834876 rows x 1 columns]
Rows where 'frame_garage_pri' has fake nulls:
        frame_garage_pri
0                    NaN
1                    NaN
2                    NaN
3                    NaN
4                    NaN
...                  ...
4988247              NaN
4988248              NaN
4988249              NaN
4988250              NaN
4988251              NaN

[4491948 rows x 1 columns]
Rows where 'dock_level_floor_c' has fake nulls:
        dock_level_floor_c
0                      NaN
1                      NaN
2                      NaN
3                      NaN
4                      NaN
...                    ...
4988247                NaN
4988248                NaN
4988249                NaN
4988250                NaN
4988251                NaN

[4988078 rows x 1 columns]
Rows where 'mobile_home_15_19_width' has fake nulls:
        mobile_home_15_19_width
0                           NaN
1                           NaN
2                           NaN
3                           NaN
4                           NaN
...                         ...
4988247                     NaN
4988248                     NaN
4988249                     NaN
4988250                     NaN
4988251                     NaN

[4976210 rows x 1 columns]
Rows where 'fireplace_adl_open' has fake nulls:
         fireplace_adl_open
0                       NaN
1                       NaN
2                       NaN
3                       NaN
4                       NaN
...                     ...
4988247                 NaN
4988248                 NaN
4988249                 NaN
4988250                 NaN
4988251                 NaN

[4969935 rows x 1 columns]
Rows where 'room_rec' has fake nulls:
         room_rec
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
...           ...
4988247       NaN
4988248       NaN
4988249       NaN
4988250       NaN
4988251       NaN

[3400608 rows x 1 columns]
Rows where 'cnpy_roof_ss_gd_c' has fake nulls:
        cnpy_roof_ss_gd_c
0                     NaN
1                     NaN
2                     NaN
3                     NaN
4                     NaN
...                   ...
4988247               NaN
4988248               NaN
4988249               NaN
4988250               NaN
4988251               NaN

[4986187 rows x 1 columns]
Rows where 'interior_finish_percent' has fake nulls:
         interior_finish_percent
3                            NaN
7                            NaN
11                           NaN
24                           NaN
25                           NaN
...                          ...
4988109                      NaN
4988110                      NaN
4988111                      NaN
4988112                      NaN
4988113                      NaN

[4523702 rows x 1 columns]
Rows where 'one_story_frame_pri' has fake nulls:
        one_story_frame_pri
0                       NaN
1                       NaN
2                       NaN

In [5]:
import re
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].apply(
        lambda x: re.sub(r'\s+', ' ', x).strip() if isinstance(x, str) else x
    )

In [6]:
for col in df.columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=True))

--- parcel_number ---
parcel_number
440990010029     1899
440990010031     1398
370590240005     1044
410320010095     1026
410880000003      978
                 ...
1332700010001       1
1148770020017       1
1122580000008       1
1122600000010       1
1147690000034       1
Name: count, Length: 770104, dtype: int64

--- leed_certification_level ---
leed_certification_level
LEED Gold Certification 60-79 points      295
LEED Silver Certification 50-59 points    198
LEED Platinum Certification 80+ points     30
LEED Certified 40-49 points                12
LEED Certification absent                   6
Name: count, dtype: int64

--- open_frame_porch_pri ---
open_frame_porch_pri
24.0     81347
48.0     65766
40.0     64074
60.0     62761
36.0     52222
         ...
1,367        1
1,183        1
1,734        1
905.0        1
2,924        1
Name: count, Length: 2094, dtype: int64

--- elev_hydro_pass ---
elev_hydro_pass
1.0    2405
2.0    1040
3.0     198
4.0      96
0.0      15
6.0      12
5.0      12
7.0       6
8.0       6
Name: count, dtype: int64

--- basement ---
basement
1,158    192
676.0    171
594      144
1,200    113
1,040     74
        ...
56.0       2
100.0      2
902.0      2
1,295      1
1,078      1
Name: count, Length: 79, dtype: int64

--- fireplace_open_1 ---
fireplace_open_1
1.0     319
2.0     180
4.0      84
10.0     48
8.0      36
0.0      12
9.0      12
3.0       6
Name: count, dtype: int64

--- unfin_basement_lwr ---
unfin_basement_lwr
191.0    30
2,070    12
120.0    12
130.0    12
350.0    12
         ..
1,726     2
312.0     2
304.0     2
240.0     1
608       1
Name: count, Length: 97, dtype: int64

--- util_bldg_frm_c ---
util_bldg_frm_c
24.0     828
18.0     559
12.0     451
16.0     442
15.0     431
        ...
235.0      1
28         1
72         1
366.0      1
270.0      1
Name: count, Length: 261, dtype: int64

--- frame_overhang_upr ---
frame_overhang_upr
40.0     7884
44.0     5392
48.0     5140
36.0     5048
42.0     4367
         ...
224.0       2
162.0       1
164.0       1
212.0       1
187.0       1
Name: count, Length: 244, dtype: int64

--- one_story_mas_lwr ---
one_story_mas_lwr
72.0     96
240.0    42
120.0    38
273.0    32
108.0    24
         ..
2,339     1
140.0     1
347.0     1
210.0     1
512.0     1
Name: count, Length: 114, dtype: int64

--- living_area_lwr ---
living_area_lwr
552.0    24
400.0    24
630.0    18
468.0    18
120.0    13
         ..
1,572     1
1,163     1
696.0     1
150.0     1
196       1
Name: count, Length: 212, dtype: int64

--- garage_interior_parking_apartments_c ---
garage_interior_parking_apartments_c
1,048    186
880      168
3,726    144
39       126
462      120
        ...
4,950      2
810        2
437.0      1
378        1
336.0      1
Name: count, Length: 268, dtype: int64

--- parking_spaces ---
parking_spaces
0.0       42
8.0       24
11.0      24
30.0      24
9.0       23
          ..
330.0      3
686.0      3
240.0      1
1409.0     1
485.0      1
Name: count, Length: 138, dtype: int64

--- store_front_metal ---
store_front_metal
1.0      14777
2.0        335
100.0      127
20.0       126
40.0       121
         ...
451.0        1
23.0         1
41.0         1
246.0        1
442.0        1
Name: count, Length: 288, dtype: int64

--- unfin_l_a_upper ---
unfin_l_a_upper
240.0    237
480.0     55
160.0     48
182.0     41
280.0     39
        ...
105.0      1
758.0      1
442.0      1
1,969      1
285        1
Name: count, Length: 283, dtype: int64

--- mobile_home_8_11_width ---
mobile_home_8_11_width
500.0    184
360.0     93
480.0     88
460.0     88
560.0     88
        ...
2,400      2
812.0      2
825.0      2
924        2
170.0      1
Name: count, Length: 126, dtype: int64

--- economic_obsolescence ---
economic_obsolescence
Normal       439200
Fair          16084
Moderate      15808
Poor          10908
Very Poor      6819
Unsound        2350
Name: count, dtype: int64

--- cnpy_roof_ss_ave_c ---
cnpy_roof_ss_ave_c
2,400    38
1,200    26
1,680    24
2,500    22
3,600    21
         ..
4,968     1
1,216     1
5,225     1
2,590     1
624       1
Name: count, Length: 291, dtype: int64

--- mobile_home_30_width ---
mobile_home_30_width
1,290    185
2,432    178
1,920    147
1,680    107
1,792    106
        ...
1,568      1
1,976      1
2,520      1
2,030      1
1,088      1
Name: count, Length: 167, dtype: int64

--- base_value_small_tank ---
base_value_small_tank
1.0    3972
0.0       6
Name: count, dtype: int64

--- canopy_lwr ---
canopy_lwr
40.0     1025
60.0      940
76.0      886
133.0     756
38.0      749
         ...
391.0       1
230.0       1
385.0       1
8.0         1
270.0       1
Name: count, Length: 204, dtype: int64

--- garage_att_frm_c ---
garage_att_frm_c
200.0    186
400.0    164
1,118    132
380.0    121
504.0    115
        ...
666.0      2
119.0      2
192.0      1
220        1
612.0      1
Name: count, Length: 272, dtype: int64

--- cost_and_design ---
cost_and_design
New / Rebuilt          400941
Extensive              346142
Partial                254909
Total                   84966
Condo Code 1            28389
Econ Misimprovement     26229
Condo Code 2             7446
Condo Code 3             2868
Condo Code 5             1080
Condo Code 4              931
Name: count, dtype: int64

--- unfin_l_a_primary ---
unfin_l_a_primary
200.0    20
120.0    18
400.0    17
220.0    12
100.0    12
         ..
575.0     1
524.0     1
482.0     1
299.0     1
224.0     1
Name: count, Length: 84, dtype: int64

--- attic_finished ---
attic_finished
400      982
420      814
360      657
240      612
480      599
        ...
1,789      1
2,028      1
2,367      1
1,756      1
2,034      1
Name: count, Length: 2453, dtype: int64

--- cond_desir_util ---
cond_desir_util
Average      3354712
Good          420069
Very Good     340407
Fair          246358
Poor           56904
Excellent      29146
Very Poor      19011
Unsound         6121
Name: count, dtype: int64

--- masonry_terrace_pri ---
masonry_terrace_pri
240.0    570
100.0    433
48.0     398
60.0     388
120.0    370
        ...
273        1
1,747      1
155        1
428.0      1
280        1
Name: count, Length: 747, dtype: int64

--- bank_canopy_c ---
bank_canopy_c
197.0    78
486.0    77
468.0    59
300.0    56
504.0    54
         ..
8,496     1
576       1
5,738     1
3,795     1
1,092     1
Name: count, Length: 402, dtype: int64

--- basement_top ---
basement_top
1.0    62
Name: count, dtype: int64

--- one_story_frame_upr ---
one_story_frame_upr
400.0    8582
420.0    7852
420      6658
400      6655
399.0    4807
         ...
999         1
2,114       1
971.0       1
993         1
1,318       1
Name: count, Length: 2278, dtype: int64

--- enclosed_entry_c ---
enclosed_entry_c
96.0     47
112.0    42
60.0     42
48.0     38
128.0    36
         ..
147.0     3
462.0     3
83.0      3
98.0      3
1,454     2
Name: count, Length: 115, dtype: int64

--- datetime ---
datetime
2026-04-24 10:33:05    297
2026-04-24 11:20:34    261
2026-04-24 14:32:37    241
2026-04-28 16:34:59    222
2026-04-28 23:41:59    221
                      ...
2026-04-23 09:03:11      1
2026-04-24 09:26:39      1
2026-04-23 09:04:00      1
2026-04-24 09:27:03      1
2026-04-24 09:27:20      1
Name: count, Length: 718523, dtype: int64

--- masonry_bay_pri ---
masonry_bay_pri
16.0     4994
12.0     4892
14.0     3755
24.0     2947
18.0     2651
         ...
209.0       6
53.0        6
85.0        5
597.0       3
800.0       1
Name: count, Length: 132, dtype: int64

--- encl_frame_porch_upr ---
encl_frame_porch_upr
72.0     72
132.0    64
98.0     63
120.0    55
96.0     44
         ..
612.0     1
78.0      1
320.0     1
318.0     1
237.0     1
Name: count, Length: 150, dtype: int64

--- cnpy_roof_ss_eco_c ---
cnpy_roof_ss_eco_c
480.0    35
576.0    28
520.0    26
500.0    22
960.0    18
         ..
336.0     1
452.0     1
940       1
1,242     1
490       1
Name: count, Length: 96, dtype: int64

--- comm_condo_neighborhood ---
comm_condo_neighborhood
Comm.Condo 1            6653
Comm.Condo 0             220
NBHD 9678.30/9673.00     120
Name: count, dtype: int64

--- fireplace_masonry_firebrick ---
fireplace_masonry_firebrick
1.0    857991
2.0     29027
3.0      4464
4.0       985
5.0       209
0.0       109
6.0        84
7.0        18
9.0        12
8.0         1
Name: count, dtype: int64

--- basement_c ---
basement_c
1,232     18
40.0      18
1,584     12
224       12
30.0       9
          ..
2,176      3
1,752      2
73,288     2
837.0      1
625.0      1
Name: count, Length: 88, dtype: int64

--- mas_brk_garage_pri ---
mas_brk_garage_pri
400      193362
420      151207
400.0    135817
420.0    109705
440      101190
          ...
997.0         1
1,370         1
1,501         1
1,181         1
970.0         1
Name: count, Length: 2458, dtype: int64

--- mobile_home_12_14_width ---
mobile_home_12_14_width
1,064    2851
924      1555
840      1441
980      1284
784      1088
         ...
396.0       1
352.0       1
2,356       1
1,984       1
444         1
Name: count, Length: 323, dtype: int64

--- oh_door_motor_rs ---
oh_door_motor_rs
1.00     284
2.00     253
3.00     170
4.00      95
5.00      18
8.00      18
7.00      14
12.00     12
6.00      10
0.48       6
13.00      6
20.00      6
9.00       6
18.00      6
17.00      6
10.00      6
Name: count, dtype: int64

--- quality ---
quality
Average      603165
Good         233651
Low          122080
Excellent     53669
1,440 *        7429
              ...
528,221           1
579,975           1
31,290            1
31,080            1
35,400            1
Name: count, Length: 24636, dtype: int64

--- mas_conc_patio_pri ---
mas_conc_patio_pri
200      17850
240      15327
100       8888
300       8669
120       7513
         ...
3,672        1
1,818        1
1,591        1
869.0        1
6,325        1
Name: count, Length: 2580, dtype: int64

--- fireplace_direct_vent ---
fireplace_direct_vent
1.0    105738
2.0      2849
3.0       241
0.0       116
4.0        30
5.0         6
Name: count, dtype: int64

--- bank_drive_thru ---
bank_drive_thru
1.0    1253
2.0      75
3.0      24
0.0       3
Name: count, dtype: int64

--- canopy_pri ---
canopy_pri
80.0     7324
60.0     5911
120.0    4860
40.0     4775
100.0    4606
         ...
928.0       1
125         1
1,400       1
728         1
478.0       1
Name: count, Length: 1025, dtype: int64

--- frame_garage_pri ---
frame_garage_pri
400.0    27856
400      19822
420.0    16321
380.0    16068
420      10855
         ...
1,204        1
146          1
217          1
1,162        1
1,203        1
Name: count, Length: 2175, dtype: int64

--- dock_level_floor_c ---
dock_level_floor_c
10,350     12
7,999       6
22,010      6
1,575       6
5,300       6
1,504       6
900.0       6
1,388       6
36,540      6
2,250       6
378.0       6
144.0       6
3,200       6
1,215       6
794.0       6
532.0       6
100,100     6
2,200       6
20,700      6
3,000       6
692.0       6
1,600       6
14,000      6
30,000      6
10,000      6
9,389       6
768.0       5
10,700      4
408.0       2
12,708      1
Name: count, dtype: int64

--- mobile_home_15_19_width ---
mobile_home_15_19_width
1,216    4123
1,140     563
1,056     510
896       419
1,368     404
         ...
644         2
1           2
576         2
945         1
752         1
Name: count, Length: 216, dtype: int64

--- fireplace_adl_open ---
fireplace_adl_open
1.0    17187
2.0      966
3.0      146
4.0       18
Name: count, dtype: int64

--- room_rec ---
room_rec
1.0     1327970
2.0      197996
3.0       51472
4.0        7051
5.0        1557
6.0         792
0.0         541
7.0         138
8.0          69
11.0         21
9.0          18
10.0         18
17.0          1
Name: count, dtype: int64

--- cnpy_roof_ss_gd_c ---
cnpy_roof_ss_gd_c
2,500    34
1,560    29
3,600    25
1,800    24
2,352    24
         ..
5,750     1
100       1
800       1
4,550     1
1,154     1
Name: count, Length: 310, dtype: int64

--- interior_finish_percent ---
interior_finish_percent
100.00     420706
0.00        38344
50.00        2258
70.00         564
40.00         428
            ...
0.24            2
200.00          1
78.00           1
1001.00         1
48.00           1
Name: count, Length: 78, dtype: int64

--- one_story_frame_pri ---
one_story_frame_pri
240      10380
120       5876
200       5687
220       5632
288       5630
         ...
913.0        1
1,565        1
2,292        1
1,786        1
573.0        1
Name: count, Length: 2573, dtype: int64

--- medical_beds ---
medical_beds
0.0      225
100.0     18
16.0      18
128.0     12
112.0     12
200.0      7
120.0      7
78.0       6
124.0      6
90.0       6
248.0      6
107.0      6
196.0      6
134.0      6
79.0       6
131.0      6
140.0      6
101.0      6
395.0      6
28.0       6
58.0       6
202.0      6
14.0       6
125.0      6
92.0       6
8.0        6
73.0       6
148.0      6
75.0       6
6.0        6
60.0       6
154.0      6
118.0      6
337.0      6
32.0       6
12.0       6
168.0      5
117.0      4
56.0       4
Name: count, dtype: int64

--- heating_ac ---
heating_ac
Central Heat/AC    4044630
Central Heat         76270
A/C Only             10726
Name: count, dtype: int64

--- energy_star_certification ---
energy_star_certification
Energy Star Certification    832
Name: count, dtype: int64

--- year ---
year
2026    831858
2024    831836
2025    831578
2023    831530
2022    831104
2021    830346
Name: count, dtype: int64

--- exterior_wall ---
exterior_wall
Brick / Veneer          1994935
Frame / Concrete Blk    1049443
Brick / Masonry          806529
Aluminum / Vinyl         208785
Stucco                   162667
Metal, Light             138960
Stone                    100174
Brick / Stone             99259
Frame / Stucco            80085
Asbestos                  77525
Masonry / Frame           75729
Shake Shingle             73138
Concr Block               35412
Concr Tilt Up             25618
Brick / Concr Block       12721
Glass / Masonry            7355
Aluminum Siding            3469
Concr Load Bearing         1905
Glass                      1815
Metal, Sandwich            1279
Tile / Dressed Stone       1246
Concr Non-Ld Bearing        900
Asbestos Corr Rigid         540
Solar Glass                 156
Native Stone                116
Enclosure                    14
Name: count, dtype: int64

--- base_area_lwr ---
base_area_lwr
420.0      790
460.0      500
400.0      438
484.0      422
396.0      422
          ...
750.0        1
737          1
156.0        1
1,425        1
229,000      1
Name: count, Length: 1716, dtype: int64

--- masonry_bay_upr ---
masonry_bay_upr
14.0     182
24.0     162
16.0     146
12.0     122
27.0      95
20.0      84
21.0      72
18.0      66
10.0      54
30.0      48
33.0      46
32.0      42
70.0      24
36.0      24
48.0      23
54.0      18
44.0      18
40.0      18
8.0       18
42.0      12
45.0      12
15.0      12
5.0        6
34.0       6
6.0        6
9.0        6
66.0       6
297.0      6
60.0       6
26.0       6
90.0       6
80.0       6
55.0       6
65.0       6
161.0      6
69.0       6
1,140      6
169.0      6
180.0      6
Name: count, dtype: int64

--- room_full_bath ---
room_full_bath
2.0     2848269
1.0      943182
3.0      532188
4.0      109570
5.0       28349
6.0        8003
7.0        1943
8.0         628
9.0         195
10.0         47
0.0          31
11.0          6
12.0          1
Name: count, dtype: int64

--- store_front_wood ---
store_front_wood
1.0      1117
20.0       24
2.0        21
150.0      19
180.0      18
50.0       17
100.0      16
110.0      14
140.0      12
130.0      12
118.0      12
156.0      12
90.0       10
80.0       10
24.0        9
18.0        6
57.0        6
210.0       6
162.0       6
55.0        6
52.0        6
72.0        6
190.0       6
300.0       6
120.0       6
36.0        6
184.0       6
66.0        6
70.0        6
230.0       6
40.0        6
87.0        6
109.0       6
400.0       6
171.0       6
166.0       6
0.0         6
105.0       6
106.0       2
30.0        1
132.0       1
Name: count, dtype: int64

--- util_bldg_mtl_c ---
util_bldg_mtl_c
600.0    106
400.0     86
240.0     67
120.0     58
160.0     58
        ...
833.0      1
100        1
1,400      1
529.0      1
901.0      1
Name: count, Length: 267, dtype: int64

--- masonry_overhang_upr ---
masonry_overhang_upr
52.0     348
63.0     264
18.0     226
24.0     216
16.0     214
        ...
273.0      5
168.0      3
169.0      3
216.0      2
140.0      1
Name: count, Length: 98, dtype: int64

--- oh_door_motor_w_m ---
oh_door_motor_w_m
2.0      344
1.0      276
3.0      188
4.0      172
6.0       72
5.0       68
8.0       60
10.0      54
0.0       25
24.0      24
14.0      12
9.0       12
7.0       10
104.0      6
22.0       6
21.0       6
37.0       6
16.0       6
11.0       6
15.0       6
18.0       6
20.0       6
25.0       6
12.0       4
44.0       3
Name: count, dtype: int64

--- plumbing_type ---
plumbing_type
Adequate    404511
Minimum      27597
Good          8813
Name: count, dtype: int64

--- base_area_upr ---
base_area_upr
600        6296
720        5851
900        5611
840        5516
1,190      5335
           ...
3,697         1
4,849         1
6,761         1
181,596       1
112,015       1
Name: count, Length: 8551, dtype: int64

--- oh_door_roll_steel ---
oh_door_roll_steel
1.0      7383
2.0      7046
3.0      3910
4.0      2601
5.0      1367
         ...
90.0        2
520.0       2
212.0       1
442.0       1
116.0       1
Name: count, Length: 168, dtype: int64

--- mobile_home_20_29_width ---
mobile_home_20_29_width
1,344    1439
1,568    1383
1,456     963
2,128     816
1,680     803
         ...
640         1
1,222       1
1,423       1
1,713       1
1,357       1
Name: count, Length: 311, dtype: int64

--- atrium ---
atrium
40.0     1104
36.0      523
32.0      344
38.0      333
48.0      331
         ...
121.0       6
225.0       6
200.0       3
82.0        3
31.0        2
Name: count, Length: 80, dtype: int64

--- open_mas_porch_upr ---
open_mas_porch_upr
60.0     631
48.0     596
40.0     554
120.0    504
80.0     487
        ...
797.0      1
457.0      1
688.0      1
558.0      1
702.0      1
Name: count, Length: 604, dtype: int64

--- heating_type ---
heating_type
Hot Air            300050
Unit Heaters        30751
Unknown              2224
Hot Water Steam       862
Name: count, dtype: int64

--- masonry_overhang_pri ---
masonry_overhang_pri
12.0     72
144.0    61
16.0     60
44.0     52
36.0     52
         ..
66.0      6
160.0     6
458.0     6
63.0      5
62.0      5
Name: count, Length: 67, dtype: int64

--- miscellaneous ---
miscellaneous
1.0    282
8.0    102
4.0     78
2.0     72
3.0      6
Name: count, dtype: int64

--- one_story_mas_upr ---
one_story_mas_upr
420.0    7561
400.0    6266
24.0     4530
18.0     2727
440.0    2614
         ...
74.0        1
1,092       1
2,279       1
1,643       1
1,772       1
Name: count, Length: 1352, dtype: int64

--- office_warehouse_ratio ---
office_warehouse_ratio
0.00     6023
0.10     2153
0.12     1920
0.08     1907
0.20     1853
         ...
49.00       3
1.50        3
20.00       3
58.00       2
4.75        1
Name: count, Length: 163, dtype: int64

--- wood_deck_lwr ---
wood_deck_lwr
180.0    68
192.0    48
200.0    42
80.0     36
168.0    36
         ..
700.0     1
622.0     1
1,290     1
474.0     1
209.0     1
Name: count, Length: 166, dtype: int64

--- elevator_stops ---
elevator_stops
2.0    8490
3.0    6123
4.0    2533
5.0     246
0.0      10
1.0       7
Name: count, dtype: int64

--- open_mas_porch_pri ---
open_mas_porch_pri
24.0     77940
30.0     67875
36.0     57434
40.0     56724
28.0     47018
         ...
774.0        1
996.0        1
814          1
681          1
446          1
Name: count, Length: 1636, dtype: int64

--- elev_elect_pass ---
elev_elect_pass
1.00     3850
2.00     2088
0.00     1968
3.00      639
4.00      548
6.00      174
0.04      126

In [7]:
pd.set_option('display.max_columns',None)
df[df['parcel_number']==1168130000001]

,parcel_number,leed_certification_level,open_frame_porch_pri,elev_hydro_pass,basement,fireplace_open_1,unfin_basement_lwr,util_bldg_frm_c,frame_overhang_upr,one_story_mas_lwr,living_area_lwr,garage_interior_parking_apartments_c,parking_spaces,store_front_metal,unfin_l_a_upper,mobile_home_8_11_width,economic_obsolescence,cnpy_roof_ss_ave_c,mobile_home_30_width,base_value_small_tank,canopy_lwr,garage_att_frm_c,cost_and_design,unfin_l_a_primary,attic_finished,cond_desir_util,masonry_terrace_pri,bank_canopy_c,basement_top,one_story_frame_upr,enclosed_entry_c,datetime,masonry_bay_pri,encl_frame_porch_upr,cnpy_roof_ss_eco_c,comm_condo_neighborhood,fireplace_masonry_firebrick,basement_c,mas_brk_garage_pri,mobile_home_12_14_width,oh_door_motor_rs,quality,mas_conc_patio_pri,fireplace_direct_vent,bank_drive_thru,canopy_pri,frame_garage_pri,dock_level_floor_c,mobile_home_15_19_width,fireplace_adl_open,room_rec,cnpy_roof_ss_gd_c,interior_finish_percent,one_story_frame_pri,medical_beds,heating_ac,energy_star_certification,year,exterior_wall,base_area_lwr,masonry_bay_upr,room_full_bath,store_front_wood,util_bldg_mtl_c,masonry_overhang_upr,oh_door_motor_w_m,plumbing_type,base_area_upr,oh_door_roll_steel,mobile_home_20_29_width,atrium,open_mas_porch_upr,heating_type,masonry_overhang_pri,miscellaneous,one_story_mas_upr,office_warehouse_ratio,wood_deck_lwr,elevator_stops,open_mas_porch_pri,elev_elect_pass,style,mas_conc_patio_lwr,construction_type,carport_c,base_value_large_tank,sprinkler_type,porch_enclosed_c,building_number,stone_tile_patio_upper,area_hirise_ofc_c,mas_brk_garage_lwr,encl_frame_porch_pri,year_built,masonry_trim,encl_mas_porch_pri,base_area_pri,impr_sq_ft,stone_tile_patio_pri,oh_door_wood_mtl,base_value_tiny_tank,market_adjustment,half_story_mas_upr,ldng_ramp_conc_c,frame_garage_lwr,carport_lwr,truck_train_wells_c,open_mas_porch_lwr,apt_3_bedroom_unit,half_story_frame_upr,carport_pri,wood_deck_upr,cnpy_only_c,frame_overhang_pri,retry,one_story_mas_pri,apt_effcncy_unit,sprinkler_wet,attic_unfinished,number_of_apartment_units,foundation_type,cnpy_roof_w_slab_c,craneway_5_ton,masnry_util_bldg_pri,partition_type,net_rentable_area,room_half_bath,wood_deck_pri,porch_open_c,parking_garage_c,type,frame_bay_pri,stories,cooling_type,apt_1_bedroom_unit,franchise_code,wall_height,apt_2_bedroom_unit,wall_height_enclosure,garage_att_mas_c,perimeter,room_total,elev_elect_frght,room_bedroom,building_details,frame_util_bldg_upr,fireplace_metal_prefab,open_frame_porch_lwr,escalator_48,remodeled,market_index_adjustment,ip,frame_util_bldg_pri,porch_open_upr_c,frame_bay_upr,base_value_medium_tank,bank_vault_no_door,frame_util_bldg_lwr,elev_hydro_frght,functional_utility,grade_adjustment,physical_condition,open_frame_porch_upr,parking_garage_upper_level_c,page_save
0,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 18:46:31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2021,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,1990,NaN,NaN,"13,054","13,054",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"7,000",NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,Strip Shopping Center,NaN,NaN,Central / Forced,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Displayed,NaN,NaN,NaN,NaN,2007,111% Market Index Adjustment,192.168.3.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2021.html
1,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 18:46:31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2021,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,1990,NaN,NaN,"4,958","4,958",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"4,646",NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,Strip Shopping Center,NaN,NaN,Central / Forced,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,View,NaN,NaN,NaN,NaN,NaN,111% Market Index Adjustment,192.168.3.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2021.html
2,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 18:46:31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2021,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,1990,NaN,NaN,"11,160","11,160",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,Strip Shopping Center,NaN,NaN,Central / Forced,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,View,NaN,NaN,NaN,NaN,NaN,111% Market Index Adjustment,192.168.3.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2021.html
3,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 18:46:31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,1990,NaN,NaN,"23,030","23,030",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,Strip Shopping Center,NaN,NaN,Central / Forced,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,View,NaN,NaN,NaN,NaN,NaN,111% Market Index Adjustment,192.168.3.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2021.html
4,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 18:46:32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2022,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,1990,NaN,NaN,"13,054","13,054",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"7,000",NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,Strip Shopping Center,NaN,NaN,Central / Forced,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Displayed,NaN,NaN,NaN,NaN,2007,100% No Mkt Index Adjustment,192.168.3.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2022.html
5,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 18:46:32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2022,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,1990,NaN,NaN,"4,958","4,958",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"4,646",NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,Strip Shopping Center,NaN,NaN,Central / Forced,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,View,NaN,NaN,NaN,NaN,NaN,100% No Mkt Index Adjustment,192.168.3.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2022.html
6,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 18:46:32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2022,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,1990,NaN,NaN,"11,160","11,160",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,Strip Shopping Center,NaN,NaN,Central / Forced,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,View,NaN,NaN,NaN,NaN,NaN,100% No Mkt Index Adjustment,192.168.3.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2022.html
7,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 18:46:32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,1990,NaN,NaN,"23,030","23,030",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,Strip Shopping Center,NaN,NaN,Central / Forced,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,View,NaN,NaN,NaN,NaN,NaN,100% No Mkt Index Adjustment,192.168.3.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2022.html
8,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 18:46:33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2023,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,1990,NaN,NaN,"13,054","13,054",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"7,000",NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,Strip Shopping Center,NaN,NaN,Central / Forced,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,Displayed,NaN,NaN,NaN,NaN,2007,100% No Mkt Index Adjustment,192.168.3.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2023.html
9,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 18:46:33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2023,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,1990,NaN,NaN,"4,958","4,958",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"4,646",NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,Strip Shopping Center,NaN,NaN,Central / Forced,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,View,NaN,NaN,NaN,NaN,NaN,100% No Mkt Index Adjustment,192.168.3.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2023.html
10,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 18:46:33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2023,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,1990,NaN,NaN,"11,160","11,160",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,Strip Shopping Center,NaN,NaN,Central / Forced,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,View,NaN,NaN,NaN,NaN,NaN,100% No Mkt Index Adjustment,192.168.3.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2023.html
11,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 18:46:33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,1990,NaN,NaN,"23,030","23,030",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,Strip Shopping Center,NaN,NaN,Central / Forced,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,View,NaN,NaN,NaN,NaN,NaN,100% No Mkt Index Adjustment,192.168.3.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2023.html
12,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 18:46:34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2024,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,1990,NaN,NaN,"13,054","13,054",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"7,000",NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,Strip Shopping Center,NaN,NaN,Central / Forced,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Displayed,NaN,NaN,NaN,NaN,2007,100% No Mkt Index Adjustment,192.168.3.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2024.html
13,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 18:46:34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2024,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,1990,NaN,NaN,"4,958","4,958",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"4,646",NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,Strip Shopping Center,NaN,NaN,Central / Forced,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,View,NaN,NaN,NaN,NaN,NaN,100% No Mkt Index Adjustment,192.168.3.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2024.html
14,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 18:46:34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2024,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,1990,NaN,NaN,"11,160","11,160",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,Strip Shopping Center,NaN,NaN,Central / Forced,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,View,NaN,NaN,NaN,NaN,NaN,100% No Mkt Index Adjustment,192.168.3.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2024.html
15,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 18:46:34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2024,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,1990,NaN,NaN,"23,030","23,030",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,Strip Shopping Center,NaN,NaN,Central / Forced,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,View,NaN,NaN,NaN,NaN,NaN,100% No Mkt Index Adjustment,192.168.3.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2024.html
16,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 18:46:35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2025,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,1990,NaN,NaN,"13,054","13,054",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"7,000",NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,Strip Shopping Center,NaN,NaN,Central / Forced,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Displayed,NaN,NaN,NaN,NaN,2007,100% No Mkt Index Adjustment,192.168.3.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2025.html
17,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 18:46:35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2025,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,1990,NaN,NaN,"4,958","4,958",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"4,646",NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,Strip Shopping Center,NaN,NaN,Central / Forced,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,View,NaN,NaN,NaN,NaN,NaN,100% No Mkt Index Adjustment,192.168.3.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2025.html
18,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 18:46:35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2025,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,1990,NaN,NaN,"11,160","11,160",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,Strip Shopping Center,NaN,NaN,Central / Forced,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,View,NaN,NaN,NaN,NaN,NaN,100% No Mkt Index Adjustment,192.168.3.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2025.html

In [8]:
df[(df['parcel_number']==1168130000001) & (df['year']==2021)]

,parcel_number,leed_certification_level,open_frame_porch_pri,elev_hydro_pass,basement,fireplace_open_1,unfin_basement_lwr,util_bldg_frm_c,frame_overhang_upr,one_story_mas_lwr,living_area_lwr,garage_interior_parking_apartments_c,parking_spaces,store_front_metal,unfin_l_a_upper,mobile_home_8_11_width,economic_obsolescence,cnpy_roof_ss_ave_c,mobile_home_30_width,base_value_small_tank,canopy_lwr,garage_att_frm_c,cost_and_design,unfin_l_a_primary,attic_finished,cond_desir_util,masonry_terrace_pri,bank_canopy_c,basement_top,one_story_frame_upr,enclosed_entry_c,datetime,masonry_bay_pri,encl_frame_porch_upr,cnpy_roof_ss_eco_c,comm_condo_neighborhood,fireplace_masonry_firebrick,basement_c,mas_brk_garage_pri,mobile_home_12_14_width,oh_door_motor_rs,quality,mas_conc_patio_pri,fireplace_direct_vent,bank_drive_thru,canopy_pri,frame_garage_pri,dock_level_floor_c,mobile_home_15_19_width,fireplace_adl_open,room_rec,cnpy_roof_ss_gd_c,interior_finish_percent,one_story_frame_pri,medical_beds,heating_ac,energy_star_certification,year,exterior_wall,base_area_lwr,masonry_bay_upr,room_full_bath,store_front_wood,util_bldg_mtl_c,masonry_overhang_upr,oh_door_motor_w_m,plumbing_type,base_area_upr,oh_door_roll_steel,mobile_home_20_29_width,atrium,open_mas_porch_upr,heating_type,masonry_overhang_pri,miscellaneous,one_story_mas_upr,office_warehouse_ratio,wood_deck_lwr,elevator_stops,open_mas_porch_pri,elev_elect_pass,style,mas_conc_patio_lwr,construction_type,carport_c,base_value_large_tank,sprinkler_type,porch_enclosed_c,building_number,stone_tile_patio_upper,area_hirise_ofc_c,mas_brk_garage_lwr,encl_frame_porch_pri,year_built,masonry_trim,encl_mas_porch_pri,base_area_pri,impr_sq_ft,stone_tile_patio_pri,oh_door_wood_mtl,base_value_tiny_tank,market_adjustment,half_story_mas_upr,ldng_ramp_conc_c,frame_garage_lwr,carport_lwr,truck_train_wells_c,open_mas_porch_lwr,apt_3_bedroom_unit,half_story_frame_upr,carport_pri,wood_deck_upr,cnpy_only_c,frame_overhang_pri,retry,one_story_mas_pri,apt_effcncy_unit,sprinkler_wet,attic_unfinished,number_of_apartment_units,foundation_type,cnpy_roof_w_slab_c,craneway_5_ton,masnry_util_bldg_pri,partition_type,net_rentable_area,room_half_bath,wood_deck_pri,porch_open_c,parking_garage_c,type,frame_bay_pri,stories,cooling_type,apt_1_bedroom_unit,franchise_code,wall_height,apt_2_bedroom_unit,wall_height_enclosure,garage_att_mas_c,perimeter,room_total,elev_elect_frght,room_bedroom,building_details,frame_util_bldg_upr,fireplace_metal_prefab,open_frame_porch_lwr,escalator_48,remodeled,market_index_adjustment,ip,frame_util_bldg_pri,porch_open_upr_c,frame_bay_upr,base_value_medium_tank,bank_vault_no_door,frame_util_bldg_lwr,elev_hydro_frght,functional_utility,grade_adjustment,physical_condition,open_frame_porch_upr,parking_garage_upper_level_c,page_save
0,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 18:46:31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2021,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,1990,NaN,NaN,"13,054","13,054",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"7,000",NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,Strip Shopping Center,NaN,NaN,Central / Forced,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Displayed,NaN,NaN,NaN,NaN,2007,111% Market Index Adjustment,192.168.3.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2021.html
1,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 18:46:31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2021,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,1990,NaN,NaN,"4,958","4,958",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"4,646",NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,Strip Shopping Center,NaN,NaN,Central / Forced,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,View,NaN,NaN,NaN,NaN,NaN,111% Market Index Adjustment,192.168.3.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2021.html
2,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 18:46:31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2021,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,1990,NaN,NaN,"11,160","11,160",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,Strip Shopping Center,NaN,NaN,Central / Forced,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,View,NaN,NaN,NaN,NaN,NaN,111% Market Index Adjustment,192.168.3.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2021.html
3,1168130000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-04-17 18:46:31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,1990,NaN,NaN,"23,030","23,030",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,Strip Shopping Center,NaN,NaN,Central / Forced,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,View,NaN,NaN,NaN,NaN,NaN,111% Market Index Adjustment,192.168.3.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1168130000001_2021.html

In [9]:
filtered_df = df[(df['parcel_number'] == 1168130000001) & (df['year'] == 2021)]

filtered_df = filtered_df.dropna(axis=1, how='all')
filtered_df

,parcel_number,store_front_metal,economic_obsolescence,datetime,quality,interior_finish_percent,year,exterior_wall,plumbing_type,heating_type,style,building_number,year_built,base_area_pri,impr_sq_ft,cnpy_roof_w_slab_c,partition_type,type,cooling_type,wall_height,building_details,remodeled,market_index_adjustment,ip,functional_utility,physical_condition,page_save
0,1168130000001,1.0,Normal,2026-04-17 18:46:31,Good,100.0,2021,Concr Tilt Up,Adequate,Hot Air,8412 -- Neighborhood Shopping Ctr,1,1990,"13,054","13,054","7,000",Normal,Strip Shopping Center,Central / Forced,14.0,Displayed,2007,111% Market Index Adjustment,192.168.3.102,Avg/Normal,Avg/Normal,1168130000001_2021.html
1,1168130000001,1.0,Normal,2026-04-17 18:46:31,Average,100.0,2021,Concr Tilt Up,Adequate,Hot Air,8412 -- Neighborhood Shopping Ctr,2,1990,"4,958","4,958","4,646",Normal,Strip Shopping Center,Central / Forced,14.0,View,NaN,111% Market Index Adjustment,192.168.3.102,Avg/Normal,Avg/Normal,1168130000001_2021.html
2,1168130000001,NaN,Normal,2026-04-17 18:46:31,Good,100.0,2021,Concr Tilt Up,Adequate,Hot Air,8412 -- Neighborhood Shopping Ctr,6,1990,"11,160","11,160",NaN,Normal,Strip Shopping Center,Central / Forced,14.0,View,NaN,111% Market Index Adjustment,192.168.3.102,Avg/Normal,Avg/Normal,1168130000001_2021.html
3,1168130000001,NaN,Normal,2026-04-17 18:46:31,Good,NaN,2021,Concr Tilt Up,Adequate,Hot Air,8412 -- Neighborhood Shopping Ctr,7,1990,"23,030","23,030",NaN,Normal,Strip Shopping Center,Central / Forced,0.0,View,NaN,111% Market Index Adjustment,192.168.3.102,Avg/Normal,Avg/Normal,1168130000001_2021.html

In [10]:
df.info(verbose=True,show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4988252 entries, 0 to 4988251
Data columns (total 165 columns):
 #    Column                                Non-Null Count    Dtype
---   ------                                --------------    -----
 0    parcel_number                         4988252 non-null  int64
 1    leed_certification_level              541 non-null      object
 2    open_frame_porch_pri                  2615132 non-null  object
 3    elev_hydro_pass                       3790 non-null     float64
 4    basement                              1454 non-null     object
 5    fireplace_open_1                      697 non-null      float64
 6    unfin_basement_lwr                    579 non-null      object
 7    util_bldg_frm_c                       8731 non-null     object
 8    frame_overhang_upr                    118276 non-null   float64
 9    one_story_mas_lwr                     956 non-null      object
 10   living_area_lwr                       1271 non-null     object
 11   garage_interior_parking_apartments_c  4456 non-null     object
 12   parking_spaces                        1025 non-null     float64
 13   store_front_metal                     20503 non-null    float64
 14   unfin_l_a_upper                       2572 non-null     object
 15   mobile_home_8_11_width                2367 non-null     object
 16   economic_obsolescence                 491169 non-null   object
 17   cnpy_roof_ss_ave_c                    1891 non-null     object
 18   mobile_home_30_width                  2639 non-null     object
 19   base_value_small_tank                 3978 non-null     float64
 20   canopy_lwr                            16114 non-null    object
 21   garage_att_frm_c                      4667 non-null     object
 22   cost_and_design                       1153901 non-null  object
 23   unfin_l_a_primary                     526 non-null      object
 24   attic_finished                        130021 non-null   object
 25   cond_desir_util                       4472728 non-null  object
 26   masonry_terrace_pri                   27393 non-null    object
 27   bank_canopy_c                         3578 non-null     object
 28   basement_top                          62 non-null       float64
 29   one_story_frame_upr                   407718 non-null   object
 30   enclosed_entry_c                      1177 non-null     object
 31   datetime                              4988252 non-null  object
 32   masonry_bay_pri                       37557 non-null    object
 33   encl_frame_porch_upr                  1828 non-null     object
 34   cnpy_roof_ss_eco_c                    678 non-null      object
 35   comm_condo_neighborhood               6993 non-null     object
 36   fireplace_masonry_firebrick           892900 non-null   float64
 37   basement_c                            539 non-null      object
 38   mas_brk_garage_pri                    2101497 non-null  object
 39   mobile_home_12_14_width               28882 non-null    object
 40   oh_door_motor_rs                      916 non-null      float64
 41   quality                               4988252 non-null  object
 42   mas_conc_patio_pri                    593313 non-null   object
 43   fireplace_direct_vent                 108980 non-null   float64
 44   bank_drive_thru                       1355 non-null     float64
 45   canopy_pri                            153376 non-null   object
 46   frame_garage_pri                      496304 non-null   object
 47   dock_level_floor_c                    174 non-null      object
 48   mobile_home_15_19_width               12042 non-null    object
 49   fireplace_adl_open                    18317 non-null    float64
 50   room_rec                              1587644 non-null  float64
 51   cnpy_roof_ss_gd_c                     2065 non-null     object
 52   interior_finish_percent               464550 non-null   float64
 53   one_story_frame_pri                   535971 non-null   object
 54   medical_beds                          486 non-null      float64
 55   heating_ac                            4131626 non-null  object
 56   energy_star_certification             832 non-null      object
 57   year                                  4988252 non-null  int64
 58   exterior_wall                         4959775 non-null  object
 59   base_area_lwr                         76432 non-null    object
 60   masonry_bay_upr                       1400 non-null     object
 61   room_full_bath                        4472412 non-null  float64
 62   store_front_wood                      1465 non-null     float64
 63   util_bldg_mtl_c                       2870 non-null     object
 64   masonry_overhang_upr                  4238 non-null     float64
 65   oh_door_motor_w_m                     1384 non-null     float64
 66   plumbing_type                         440921 non-null   object
 67   base_area_upr                         1684872 non-null  object
 68   oh_door_roll_steel                    31230 non-null    float64
 69   mobile_home_20_29_width               15395 non-null    object
 70   atrium                                6445 non-null     float64
 71   open_mas_porch_upr                    31134 non-null    object
 72   heating_type                          333887 non-null   object
 73   masonry_overhang_pri                  1200 non-null     object
 74   miscellaneous                         540 non-null      float64
 75   one_story_mas_upr                     115162 non-null   object
 76   office_warehouse_ratio                60613 non-null    float64
 77   wood_deck_lwr                         1472 non-null     object
 78   elevator_stops                        17409 non-null    float64
 79   open_mas_porch_pri                    1474209 non-null  object
 80   elev_elect_pass                       9804 non-null     float64
 81   style                                 4988252 non-null  object
 82   mas_conc_patio_lwr                    4209 non-null     object
 83   construction_type                     24267 non-null    object
 84   carport_c                             4802 non-null     object
 85   base_value_large_tank                 701 non-null      float64
 86   sprinkler_type                        43403 non-null    object
 87   porch_enclosed_c                      3534 non-null     object
 88   building_number                       4988252 non-null  int64
 89   stone_tile_patio_upper                4508 non-null     object
 90   area_hirise_ofc_c                     64 non-null       object
 91   mas_brk_garage_lwr                    24574 non-null    object
 92   encl_frame_porch_pri                  121662 non-null   object
 93   year_built                            4988252 non-null  int64
 94   masonry_trim                          128032 non-null   float64
 95   encl_mas_porch_pri                    9256 non-null     object
 96   base_area_pri                         4920170 non-null  object
 97   impr_sq_ft                            4733883 non-null  object
 98   stone_tile_patio_pri                  33688 non-null    object
 99   oh_door_wood_mtl                      107258 non-null   float64
 100  base_value_tiny_tank                  7687 non-null     float64
 101  market_adjustment                     87495 non-null    object
 102  half_story_mas_upr                    2047 non-null     object
 103  ldng_ramp_conc_c                      1705 non-null     object
 104  frame_garage_lwr                      77382 non-null    object
 105  carport_lwr                           5086 non-null     object
 106  truck_train_wells_c                   3899 non-null     object
 107  open_mas_porch_lwr                    11738 non-null    object
 108  apt_3_bedroom_unit                    8717 non-null     float64
 109  half_story_frame_upr                  7326 non-null     object
 110  carport_pri                           189321 non-null   object
 111  wood_deck_upr                         29703 non-null    object
 112  cnpy_only_c                           26752 non-null    object
 113  frame_overhang_pri                    8110 non-null     float64
 114  retry                                 0 non-null        float64
 115  one_story_mas_pri                     677420 non-null   object
 116  apt_effcncy_unit                      2782 non-null     float64
 117  sprinkler_wet                         2461 non-null     float64
 118  attic_unfinished                      24263 non-null    object
 119  number_of_apartment_units             1684 non-null     float64
 120  foundation_type                       4472730 non-null  object
 121  cnpy_roof_w_slab_c                    117468 non-null   object
 122  craneway_5_ton                        654 non-null      float64
 123  masnry_util_bldg_pri                  10992 non-null    object
 124  partition_type                        446997 non-null   object
 125  net_rentable_area                     1068 non-null     float64
 126  room_half_bath                        1761052 non-null  float64
 127  wood_deck_pri                         160941 non-null   object
 128  porch_open_c                          110041 non-null   object
 129  parking_garage_c                      1612 non-null     object
 130  type                                  4988252 non-null  object
 131  frame_bay_pri                         15464 non-null    float64
 132  stories                               44838 non-null    float64
 133  cooling_type                          311928 non-null   object
 134  apt_1_bedroom_unit                    34940 non-null    float64
 135  franchise_code                        10080 non-null    float64
 136  wall_height                           345669 non-null   float64
 137  apt_2_bedroom_unit                    36675 non-null    float64
 138  wall_height_enclosure                 148762 non-null   float64
 139  garage_att_mas_c                      1024 non-null     object
 140  perimeter                             566 non-null      object
 141  room_total                            4472521 non-null  float64
 142  elev_elect_frght                      3925 non-null     float64
 143  room_bedroom                          4472840 non-null  float64
 144  building_details                      4985587 non-null  object
 145  frame_util_bldg_upr                   2094 non-null     object
 146  fireplace_metal_prefab                1478397 non-null  float64
 147  open_frame_porch_lwr                  34349 non-null    object
 148  escalator_48                          203 non-null      float64
 149  remodeled                             4988234 non-null  object
 150  market_index_adjustment               470798 non-null   object
 151  ip                                    4988252 non-null  object
 152  frame_util_bldg_pri                   74298 non-null    object
 153  porch_open_upr_c                      89188 non-null    object
 154  frame_bay_upr                         2135 non-null     float64
 155  base_value_medium_tank                6236 non-null     float64
 156  bank_vault_no_door                    662 non-null      float64
 157  frame_util_bldg_lwr                   4171 non-null     object
 158  elev_hydro_frght                      658 non-null      float64
 159  functional_utility                    489806 non-null   object
 160  grade_adjustment                      4474587 non-null  object
 161  physical_condition                    4964694 non-null  object
 162  open_frame_porch_upr                  116118 non-null   object
 163  parking_garage_upper_level_c          1315 non-null     object
 164  page_save                             4988252 non-null  object
dtypes: float64(54), int64(4), object(107)
memory usage: 6.1+ GB

In [11]:
col = ['retry','ip','datetime']
df.drop(columns=col,inplace=True)

In [12]:
df.info(verbose=True,show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4988252 entries, 0 to 4988251
Data columns (total 162 columns):
 #    Column                                Non-Null Count    Dtype
---   ------                                --------------    -----
 0    parcel_number                         4988252 non-null  int64
 1    leed_certification_level              541 non-null      object
 2    open_frame_porch_pri                  2615132 non-null  object
 3    elev_hydro_pass                       3790 non-null     float64
 4    basement                              1454 non-null     object
 5    fireplace_open_1                      697 non-null      float64
 6    unfin_basement_lwr                    579 non-null      object
 7    util_bldg_frm_c                       8731 non-null     object
 8    frame_overhang_upr                    118276 non-null   float64
 9    one_story_mas_lwr                     956 non-null      object
 10   living_area_lwr                       1271 non-null     object
 11   garage_interior_parking_apartments_c  4456 non-null     object
 12   parking_spaces                        1025 non-null     float64
 13   store_front_metal                     20503 non-null    float64
 14   unfin_l_a_upper                       2572 non-null     object
 15   mobile_home_8_11_width                2367 non-null     object
 16   economic_obsolescence                 491169 non-null   object
 17   cnpy_roof_ss_ave_c                    1891 non-null     object
 18   mobile_home_30_width                  2639 non-null     object
 19   base_value_small_tank                 3978 non-null     float64
 20   canopy_lwr                            16114 non-null    object
 21   garage_att_frm_c                      4667 non-null     object
 22   cost_and_design                       1153901 non-null  object
 23   unfin_l_a_primary                     526 non-null      object
 24   attic_finished                        130021 non-null   object
 25   cond_desir_util                       4472728 non-null  object
 26   masonry_terrace_pri                   27393 non-null    object
 27   bank_canopy_c                         3578 non-null     object
 28   basement_top                          62 non-null       float64
 29   one_story_frame_upr                   407718 non-null   object
 30   enclosed_entry_c                      1177 non-null     object
 31   masonry_bay_pri                       37557 non-null    object
 32   encl_frame_porch_upr                  1828 non-null     object
 33   cnpy_roof_ss_eco_c                    678 non-null      object
 34   comm_condo_neighborhood               6993 non-null     object
 35   fireplace_masonry_firebrick           892900 non-null   float64
 36   basement_c                            539 non-null      object
 37   mas_brk_garage_pri                    2101497 non-null  object
 38   mobile_home_12_14_width               28882 non-null    object
 39   oh_door_motor_rs                      916 non-null      float64
 40   quality                               4988252 non-null  object
 41   mas_conc_patio_pri                    593313 non-null   object
 42   fireplace_direct_vent                 108980 non-null   float64
 43   bank_drive_thru                       1355 non-null     float64
 44   canopy_pri                            153376 non-null   object
 45   frame_garage_pri                      496304 non-null   object
 46   dock_level_floor_c                    174 non-null      object
 47   mobile_home_15_19_width               12042 non-null    object
 48   fireplace_adl_open                    18317 non-null    float64
 49   room_rec                              1587644 non-null  float64
 50   cnpy_roof_ss_gd_c                     2065 non-null     object
 51   interior_finish_percent               464550 non-null   float64
 52   one_story_frame_pri                   535971 non-null   object
 53   medical_beds                          486 non-null      float64
 54   heating_ac                            4131626 non-null  object
 55   energy_star_certification             832 non-null      object
 56   year                                  4988252 non-null  int64
 57   exterior_wall                         4959775 non-null  object
 58   base_area_lwr                         76432 non-null    object
 59   masonry_bay_upr                       1400 non-null     object
 60   room_full_bath                        4472412 non-null  float64
 61   store_front_wood                      1465 non-null     float64
 62   util_bldg_mtl_c                       2870 non-null     object
 63   masonry_overhang_upr                  4238 non-null     float64
 64   oh_door_motor_w_m                     1384 non-null     float64
 65   plumbing_type                         440921 non-null   object
 66   base_area_upr                         1684872 non-null  object
 67   oh_door_roll_steel                    31230 non-null    float64
 68   mobile_home_20_29_width               15395 non-null    object
 69   atrium                                6445 non-null     float64
 70   open_mas_porch_upr                    31134 non-null    object
 71   heating_type                          333887 non-null   object
 72   masonry_overhang_pri                  1200 non-null     object
 73   miscellaneous                         540 non-null      float64
 74   one_story_mas_upr                     115162 non-null   object
 75   office_warehouse_ratio                60613 non-null    float64
 76   wood_deck_lwr                         1472 non-null     object
 77   elevator_stops                        17409 non-null    float64
 78   open_mas_porch_pri                    1474209 non-null  object
 79   elev_elect_pass                       9804 non-null     float64
 80   style                                 4988252 non-null  object
 81   mas_conc_patio_lwr                    4209 non-null     object
 82   construction_type                     24267 non-null    object
 83   carport_c                             4802 non-null     object
 84   base_value_large_tank                 701 non-null      float64
 85   sprinkler_type                        43403 non-null    object
 86   porch_enclosed_c                      3534 non-null     object
 87   building_number                       4988252 non-null  int64
 88   stone_tile_patio_upper                4508 non-null     object
 89   area_hirise_ofc_c                     64 non-null       object
 90   mas_brk_garage_lwr                    24574 non-null    object
 91   encl_frame_porch_pri                  121662 non-null   object
 92   year_built                            4988252 non-null  int64
 93   masonry_trim                          128032 non-null   float64
 94   encl_mas_porch_pri                    9256 non-null     object
 95   base_area_pri                         4920170 non-null  object
 96   impr_sq_ft                            4733883 non-null  object
 97   stone_tile_patio_pri                  33688 non-null    object
 98   oh_door_wood_mtl                      107258 non-null   float64
 99   base_value_tiny_tank                  7687 non-null     float64
 100  market_adjustment                     87495 non-null    object
 101  half_story_mas_upr                    2047 non-null     object
 102  ldng_ramp_conc_c                      1705 non-null     object
 103  frame_garage_lwr                      77382 non-null    object
 104  carport_lwr                           5086 non-null     object
 105  truck_train_wells_c                   3899 non-null     object
 106  open_mas_porch_lwr                    11738 non-null    object
 107  apt_3_bedroom_unit                    8717 non-null     float64
 108  half_story_frame_upr                  7326 non-null     object
 109  carport_pri                           189321 non-null   object
 110  wood_deck_upr                         29703 non-null    object
 111  cnpy_only_c                           26752 non-null    object
 112  frame_overhang_pri                    8110 non-null     float64
 113  one_story_mas_pri                     677420 non-null   object
 114  apt_effcncy_unit                      2782 non-null     float64
 115  sprinkler_wet                         2461 non-null     float64
 116  attic_unfinished                      24263 non-null    object
 117  number_of_apartment_units             1684 non-null     float64
 118  foundation_type                       4472730 non-null  object
 119  cnpy_roof_w_slab_c                    117468 non-null   object
 120  craneway_5_ton                        654 non-null      float64
 121  masnry_util_bldg_pri                  10992 non-null    object
 122  partition_type                        446997 non-null   object
 123  net_rentable_area                     1068 non-null     float64
 124  room_half_bath                        1761052 non-null  float64
 125  wood_deck_pri                         160941 non-null   object
 126  porch_open_c                          110041 non-null   object
 127  parking_garage_c                      1612 non-null     object
 128  type                                  4988252 non-null  object
 129  frame_bay_pri                         15464 non-null    float64
 130  stories                               44838 non-null    float64
 131  cooling_type                          311928 non-null   object
 132  apt_1_bedroom_unit                    34940 non-null    float64
 133  franchise_code                        10080 non-null    float64
 134  wall_height                           345669 non-null   float64
 135  apt_2_bedroom_unit                    36675 non-null    float64
 136  wall_height_enclosure                 148762 non-null   float64
 137  garage_att_mas_c                      1024 non-null     object
 138  perimeter                             566 non-null      object
 139  room_total                            4472521 non-null  float64
 140  elev_elect_frght                      3925 non-null     float64
 141  room_bedroom                          4472840 non-null  float64
 142  building_details                      4985587 non-null  object
 143  frame_util_bldg_upr                   2094 non-null     object
 144  fireplace_metal_prefab                1478397 non-null  float64
 145  open_frame_porch_lwr                  34349 non-null    object
 146  escalator_48                          203 non-null      float64
 147  remodeled                             4988234 non-null  object
 148  market_index_adjustment               470798 non-null   object
 149  frame_util_bldg_pri                   74298 non-null    object
 150  porch_open_upr_c                      89188 non-null    object
 151  frame_bay_upr                         2135 non-null     float64
 152  base_value_medium_tank                6236 non-null     float64
 153  bank_vault_no_door                    662 non-null      float64
 154  frame_util_bldg_lwr                   4171 non-null     object
 155  elev_hydro_frght                      658 non-null      float64
 156  functional_utility                    489806 non-null   object
 157  grade_adjustment                      4474587 non-null  object
 158  physical_condition                    4964694 non-null  object
 159  open_frame_porch_upr                  116118 non-null   object
 160  parking_garage_upper_level_c          1315 non-null     object
 161  page_save                             4988252 non-null  object
dtypes: float64(53), int64(4), object(105)
memory usage: 6.0+ GB

In [13]:
filtered_df = df[(df['parcel_number'] == 1168130000001) & (df['year'] == 2021)]

filtered_df = filtered_df.dropna(axis=1, how='all')
filtered_df

,parcel_number,store_front_metal,economic_obsolescence,quality,interior_finish_percent,year,exterior_wall,plumbing_type,heating_type,style,building_number,year_built,base_area_pri,impr_sq_ft,cnpy_roof_w_slab_c,partition_type,type,cooling_type,wall_height,building_details,remodeled,market_index_adjustment,functional_utility,physical_condition,page_save
0,1168130000001,1.0,Normal,Good,100.0,2021,Concr Tilt Up,Adequate,Hot Air,8412 -- Neighborhood Shopping Ctr,1,1990,"13,054","13,054","7,000",Normal,Strip Shopping Center,Central / Forced,14.0,Displayed,2007,111% Market Index Adjustment,Avg/Normal,Avg/Normal,1168130000001_2021.html
1,1168130000001,1.0,Normal,Average,100.0,2021,Concr Tilt Up,Adequate,Hot Air,8412 -- Neighborhood Shopping Ctr,2,1990,"4,958","4,958","4,646",Normal,Strip Shopping Center,Central / Forced,14.0,View,NaN,111% Market Index Adjustment,Avg/Normal,Avg/Normal,1168130000001_2021.html
2,1168130000001,NaN,Normal,Good,100.0,2021,Concr Tilt Up,Adequate,Hot Air,8412 -- Neighborhood Shopping Ctr,6,1990,"11,160","11,160",NaN,Normal,Strip Shopping Center,Central / Forced,14.0,View,NaN,111% Market Index Adjustment,Avg/Normal,Avg/Normal,1168130000001_2021.html
3,1168130000001,NaN,Normal,Good,NaN,2021,Concr Tilt Up,Adequate,Hot Air,8412 -- Neighborhood Shopping Ctr,7,1990,"23,030","23,030",NaN,Normal,Strip Shopping Center,Central / Forced,0.0,View,NaN,111% Market Index Adjustment,Avg/Normal,Avg/Normal,1168130000001_2021.html

In [14]:
df['building_number'].unique()

array([  1,   2,   6,   7,   3,   4,   9,  11,  12,  13,  14,  15,  16,
        17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,
        30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
        43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
        56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,
        69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,
        82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,
        95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107,
       108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
       121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133,
       134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146,
       147, 148, 149, 150, 151, 152, 153, 154, 160, 161, 162, 163, 165,
       167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
       180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192,
       193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205,
       206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218,
       219, 220,   5,   8,  10, 155, 156, 157, 158, 159, 164, 166, 221,
       222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234,
       235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247,
       248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260,
       261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273,
       274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286,
       287, 288, 289, 290, 292, 293, 294, 295, 297, 298, 299, 300, 301,
       302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314,
       315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327,
       328])

In [15]:
df[df['building_number']==328]

,parcel_number,leed_certification_level,open_frame_porch_pri,elev_hydro_pass,basement,fireplace_open_1,unfin_basement_lwr,util_bldg_frm_c,frame_overhang_upr,one_story_mas_lwr,living_area_lwr,garage_interior_parking_apartments_c,parking_spaces,store_front_metal,unfin_l_a_upper,mobile_home_8_11_width,economic_obsolescence,cnpy_roof_ss_ave_c,mobile_home_30_width,base_value_small_tank,canopy_lwr,garage_att_frm_c,cost_and_design,unfin_l_a_primary,attic_finished,cond_desir_util,masonry_terrace_pri,bank_canopy_c,basement_top,one_story_frame_upr,enclosed_entry_c,masonry_bay_pri,encl_frame_porch_upr,cnpy_roof_ss_eco_c,comm_condo_neighborhood,fireplace_masonry_firebrick,basement_c,mas_brk_garage_pri,mobile_home_12_14_width,oh_door_motor_rs,quality,mas_conc_patio_pri,fireplace_direct_vent,bank_drive_thru,canopy_pri,frame_garage_pri,dock_level_floor_c,mobile_home_15_19_width,fireplace_adl_open,room_rec,cnpy_roof_ss_gd_c,interior_finish_percent,one_story_frame_pri,medical_beds,heating_ac,energy_star_certification,year,exterior_wall,base_area_lwr,masonry_bay_upr,room_full_bath,store_front_wood,util_bldg_mtl_c,masonry_overhang_upr,oh_door_motor_w_m,plumbing_type,base_area_upr,oh_door_roll_steel,mobile_home_20_29_width,atrium,open_mas_porch_upr,heating_type,masonry_overhang_pri,miscellaneous,one_story_mas_upr,office_warehouse_ratio,wood_deck_lwr,elevator_stops,open_mas_porch_pri,elev_elect_pass,style,mas_conc_patio_lwr,construction_type,carport_c,base_value_large_tank,sprinkler_type,porch_enclosed_c,building_number,stone_tile_patio_upper,area_hirise_ofc_c,mas_brk_garage_lwr,encl_frame_porch_pri,year_built,masonry_trim,encl_mas_porch_pri,base_area_pri,impr_sq_ft,stone_tile_patio_pri,oh_door_wood_mtl,base_value_tiny_tank,market_adjustment,half_story_mas_upr,ldng_ramp_conc_c,frame_garage_lwr,carport_lwr,truck_train_wells_c,open_mas_porch_lwr,apt_3_bedroom_unit,half_story_frame_upr,carport_pri,wood_deck_upr,cnpy_only_c,frame_overhang_pri,one_story_mas_pri,apt_effcncy_unit,sprinkler_wet,attic_unfinished,number_of_apartment_units,foundation_type,cnpy_roof_w_slab_c,craneway_5_ton,masnry_util_bldg_pri,partition_type,net_rentable_area,room_half_bath,wood_deck_pri,porch_open_c,parking_garage_c,type,frame_bay_pri,stories,cooling_type,apt_1_bedroom_unit,franchise_code,wall_height,apt_2_bedroom_unit,wall_height_enclosure,garage_att_mas_c,perimeter,room_total,elev_elect_frght,room_bedroom,building_details,frame_util_bldg_upr,fireplace_metal_prefab,open_frame_porch_lwr,escalator_48,remodeled,market_index_adjustment,frame_util_bldg_pri,porch_open_upr_c,frame_bay_upr,base_value_medium_tank,bank_vault_no_door,frame_util_bldg_lwr,elev_hydro_frght,functional_utility,grade_adjustment,physical_condition,open_frame_porch_upr,parking_garage_upper_level_c,page_save
4850235,440990010029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9783 -- Storage Tank - Medium,NaN,NaN,NaN,NaN,NaN,NaN,328,NaN,NaN,NaN,NaN,2024,NaN,NaN,"100,200","100,200",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Storage Tank - Medium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,View,NaN,NaN,NaN,NaN,--,100% No Mkt Index Adjustment,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0440990010029_2025.html
4854942,440990010029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9783 -- Storage Tank - Medium,NaN,NaN,NaN,NaN,NaN,NaN,328,NaN,NaN,NaN,NaN,2024,NaN,NaN,"97,000","97,000",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Storage Tank - Medium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,View,NaN,NaN,NaN,NaN,--,100% No Mkt Index Adjustment,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0440990010029_2026.html

In [16]:
filtered_df = df[(df['parcel_number'] == 440990010029) & (df['building_number'] == 328)]

filtered_df = filtered_df.dropna(axis=1, how='all')
filtered_df

,parcel_number,quality,year,style,building_number,year_built,base_area_pri,impr_sq_ft,type,building_details,remodeled,market_index_adjustment,base_value_medium_tank,page_save
4850235,440990010029,Average,2025,9783 -- Storage Tank - Medium,328,2024,"100,200","100,200",Storage Tank - Medium,View,--,100% No Mkt Index Adjustment,1.0,0440990010029_2025.html
4854942,440990010029,Average,2026,9783 -- Storage Tank - Medium,328,2024,"97,000","97,000",Storage Tank - Medium,View,--,100% No Mkt Index Adjustment,1.0,0440990010029_2026.html

In [17]:
df['leed_certification_level'].value_counts()

leed_certification_level
LEED Gold Certification 60-79 points      295
LEED Silver Certification 50-59 points    198
LEED Platinum Certification 80+ points     30
LEED Certified 40-49 points                12
LEED Certification absent                   6
Name: count, dtype: int64

In [18]:
filtered_df = df[(df['parcel_number'] == 1113770000001) ]

filtered_df = filtered_df.dropna(axis=1, how='all')
filtered_df

,parcel_number,leed_certification_level,economic_obsolescence,quality,interior_finish_percent,energy_star_certification,year,exterior_wall,plumbing_type,base_area_upr,heating_type,elev_elect_pass,style,sprinkler_type,building_number,area_hirise_ofc_c,year_built,base_area_pri,impr_sq_ft,partition_type,type,stories,cooling_type,wall_height,building_details,remodeled,market_index_adjustment,functional_utility,physical_condition,page_save
18710,1113770000001,LEED Gold Certification 60-79 points,Normal,"324,758",100.0,Energy Star Certification,2021,Glass,Adequate,"1,749",Hot Air,6.0,Excellent,Wet,1,756.0,1981,"1,749",Displayed,Normal,8344 -- Office Building,14.0,Central / Forced,13.0,Displayed,Office Bldgs. Hi-Rise (5+ Stories),111% Market Index Adjustment,Avg/Normal,Avg/Normal,1113770000001_2021.html
18711,1113770000001,NaN,Normal,"340,792",0.0,NaN,2021,NaN,NaN,"42,599",NaN,3.0,Average,NaN,2,NaN,1981,"42,599",NaN,Normal,8345 -- Parking Structure,NaN,NaN,10.0,View,Parking Garage,100% No Mkt Index Adjustment,Avg/Normal,Avg/Normal,1113770000001_2021.html
18771,1113770000001,LEED Gold Certification 60-79 points,Normal,"324,758",100.0,Energy Star Certification,2022,Glass,Adequate,"1,749",Hot Air,6.0,Excellent,Wet,1,756.0,1981,"1,749",Displayed,Normal,8344 -- Office Building,14.0,Central / Forced,13.0,Displayed,Office Bldgs. Hi-Rise (5+ Stories),100% No Mkt Index Adjustment,Avg/Normal,Avg/Normal,1113770000001_2022.html
18772,1113770000001,NaN,Normal,"340,792",0.0,NaN,2022,NaN,NaN,"42,599",NaN,3.0,Average,NaN,2,NaN,1981,"42,599",NaN,Normal,8345 -- Parking Structure,NaN,NaN,10.0,View,Parking Garage,100% No Mkt Index Adjustment,Avg/Normal,Avg/Normal,1113770000001_2022.html
18839,1113770000001,LEED Gold Certification 60-79 points,Normal,"324,758",100.0,Energy Star Certification,2023,Glass,Adequate,"1,749",Hot Air,6.0,Excellent,Wet,1,756.0,1981,"1,749",Displayed,Normal,8344 -- Office Building,14.0,Central / Forced,13.0,Displayed,Office Bldgs. Hi-Rise (5+ Stories),100% No Mkt Index Adjustment,Avg/Normal,Avg/Normal,1113770000001_2023.html
18840,1113770000001,NaN,Normal,"340,792",0.0,NaN,2023,NaN,NaN,"42,599",NaN,3.0,Average,NaN,2,NaN,1981,"42,599",NaN,Normal,8345 -- Parking Structure,NaN,NaN,10.0,View,Parking Garage,100% No Mkt Index Adjustment,Avg/Normal,Avg/Normal,1113770000001_2023.html
18909,1113770000001,LEED Gold Certification 60-79 points,Normal,"324,758",100.0,Energy Star Certification,2024,Glass,Adequate,"1,749",Hot Air,6.0,Excellent,Wet,1,756.0,1981,"1,749",Displayed,Normal,8344 -- Office Building,14.0,Central / Forced,13.0,Displayed,Office Bldgs. Hi-Rise (5+ Stories),100% No Mkt Index Adjustment,Avg/Normal,Avg/Normal,1113770000001_2024.html
18910,1113770000001,NaN,Normal,"340,792",0.0,NaN,2024,NaN,NaN,"42,599",NaN,3.0,Average,NaN,2,NaN,1981,"42,599",NaN,Normal,8345 -- Parking Structure,NaN,NaN,10.0,View,Parking Garage,100% No Mkt Index Adjustment,Avg/Normal,Avg/Normal,1113770000001_2024.html
18966,1113770000001,LEED Gold Certification 60-79 points,Normal,"324,758",100.0,Energy Star Certification,2025,Glass,Adequate,"1,749",Hot Air,6.0,Excellent,Wet,1,756.0,1981,"1,749",Displayed,Normal,8344 -- Office Building,14.0,Central / Forced,13.0,Displayed,Office Bldgs. Hi-Rise (5+ Stories),100% No Mkt Index Adjustment,Avg/Normal,Avg/Normal,1113770000001_2025.html
18967,1113770000001,NaN,Normal,"340,792",0.0,NaN,2025,NaN,NaN,"42,599",NaN,3.0,Average,NaN,2,NaN,1981,"42,599",NaN,Normal,8345 -- Parking Structure,NaN,NaN,10.0,View,Parking Garage,100% No Mkt Index Adjustment,Avg/Normal,Avg/Normal,1113770000001_2025.html
19013,1113770000001,LEED Gold Certification 60-79 points,Normal,"324,758",100.0,Energy Star Certification,2026,Glass,Adequate,"1,749",Hot Air,6.0,Excellent,Wet,1,756.0,1981,"1,749",Displayed,Normal,8344 -- Office Building,14.0,Central / Forced,13.0,Displayed,Office Bldgs. Hi-Rise (5+ Stories),100% No Mkt Index Adjustment,Avg/Normal,Avg/Normal,1113770000001_2026.html
19014,1113770000001,NaN,Normal,"340,792",0.0,NaN,2026,NaN,NaN,"42,599",NaN,3.0,Average,NaN,2,NaN,1981,"42,599",NaN,Normal,8345 -- Parking Structure,NaN,NaN,10.0,View,Parking Garage,100% No Mkt Index Adjustment,Avg/Normal,Avg/Normal,1113770000001_2026.html

In [19]:
df[(df['parcel_number'] == 1113770000001) & (df['base_area_upr']=='20,746')]

Empty DataFrame
Columns: [parcel_number, leed_certification_level, open_frame_porch_pri, elev_hydro_pass, basement, fireplace_open_1, unfin_basement_lwr, util_bldg_frm_c, frame_overhang_upr, one_story_mas_lwr, living_area_lwr, garage_interior_parking_apartments_c, parking_spaces, store_front_metal, unfin_l_a_upper, mobile_home_8_11_width, economic_obsolescence, cnpy_roof_ss_ave_c, mobile_home_30_width, base_value_small_tank, canopy_lwr, garage_att_frm_c, cost_and_design, unfin_l_a_primary, attic_finished, cond_desir_util, masonry_terrace_pri, bank_canopy_c, basement_top, one_story_frame_upr, enclosed_entry_c, masonry_bay_pri, encl_frame_porch_upr, cnpy_roof_ss_eco_c, comm_condo_neighborhood, fireplace_masonry_firebrick, basement_c, mas_brk_garage_pri, mobile_home_12_14_width, oh_door_motor_rs, quality, mas_conc_patio_pri, fireplace_direct_vent, bank_drive_thru, canopy_pri, frame_garage_pri, dock_level_floor_c, mobile_home_15_19_width, fireplace_adl_open, room_rec, cnpy_roof_ss_gd_c, interior_finish_percent, one_story_frame_pri, medical_beds, heating_ac, energy_star_certification, year, exterior_wall, base_area_lwr, masonry_bay_upr, room_full_bath, store_front_wood, util_bldg_mtl_c, masonry_overhang_upr, oh_door_motor_w_m, plumbing_type, base_area_upr, oh_door_roll_steel, mobile_home_20_29_width, atrium, open_mas_porch_upr, heating_type, masonry_overhang_pri, miscellaneous, one_story_mas_upr, office_warehouse_ratio, wood_deck_lwr, elevator_stops, open_mas_porch_pri, elev_elect_pass, style, mas_conc_patio_lwr, construction_type, carport_c, base_value_large_tank, sprinkler_type, porch_enclosed_c, building_number, stone_tile_patio_upper, area_hirise_ofc_c, mas_brk_garage_lwr, encl_frame_porch_pri, year_built, masonry_trim, encl_mas_porch_pri, base_area_pri, impr_sq_ft, stone_tile_patio_pri, oh_door_wood_mtl, base_value_tiny_tank, ...]
Index: []

In [20]:
filtered_df = df[(df['parcel_number'] == 1113770000001) & (df['base_area_upr']=='20,746')]

filtered_df = filtered_df.dropna(axis=1, how='all')
filtered_df

Empty DataFrame
Columns: []
Index: []

In [21]:
df[df['leed_certification_level']=='LEED Gold Certification 60-79 points']

,parcel_number,leed_certification_level,open_frame_porch_pri,elev_hydro_pass,basement,fireplace_open_1,unfin_basement_lwr,util_bldg_frm_c,frame_overhang_upr,one_story_mas_lwr,living_area_lwr,garage_interior_parking_apartments_c,parking_spaces,store_front_metal,unfin_l_a_upper,mobile_home_8_11_width,economic_obsolescence,cnpy_roof_ss_ave_c,mobile_home_30_width,base_value_small_tank,canopy_lwr,garage_att_frm_c,cost_and_design,unfin_l_a_primary,attic_finished,cond_desir_util,masonry_terrace_pri,bank_canopy_c,basement_top,one_story_frame_upr,enclosed_entry_c,masonry_bay_pri,encl_frame_porch_upr,cnpy_roof_ss_eco_c,comm_condo_neighborhood,fireplace_masonry_firebrick,basement_c,mas_brk_garage_pri,mobile_home_12_14_width,oh_door_motor_rs,quality,mas_conc_patio_pri,fireplace_direct_vent,bank_drive_thru,canopy_pri,frame_garage_pri,dock_level_floor_c,mobile_home_15_19_width,fireplace_adl_open,room_rec,cnpy_roof_ss_gd_c,interior_finish_percent,one_story_frame_pri,medical_beds,heating_ac,energy_star_certification,year,exterior_wall,base_area_lwr,masonry_bay_upr,room_full_bath,store_front_wood,util_bldg_mtl_c,masonry_overhang_upr,oh_door_motor_w_m,plumbing_type,base_area_upr,oh_door_roll_steel,mobile_home_20_29_width,atrium,open_mas_porch_upr,heating_type,masonry_overhang_pri,miscellaneous,one_story_mas_upr,office_warehouse_ratio,wood_deck_lwr,elevator_stops,open_mas_porch_pri,elev_elect_pass,style,mas_conc_patio_lwr,construction_type,carport_c,base_value_large_tank,sprinkler_type,porch_enclosed_c,building_number,stone_tile_patio_upper,area_hirise_ofc_c,mas_brk_garage_lwr,encl_frame_porch_pri,year_built,masonry_trim,encl_mas_porch_pri,base_area_pri,impr_sq_ft,stone_tile_patio_pri,oh_door_wood_mtl,base_value_tiny_tank,market_adjustment,half_story_mas_upr,ldng_ramp_conc_c,frame_garage_lwr,carport_lwr,truck_train_wells_c,open_mas_porch_lwr,apt_3_bedroom_unit,half_story_frame_upr,carport_pri,wood_deck_upr,cnpy_only_c,frame_overhang_pri,one_story_mas_pri,apt_effcncy_unit,sprinkler_wet,attic_unfinished,number_of_apartment_units,foundation_type,cnpy_roof_w_slab_c,craneway_5_ton,masnry_util_bldg_pri,partition_type,net_rentable_area,room_half_bath,wood_deck_pri,porch_open_c,parking_garage_c,type,frame_bay_pri,stories,cooling_type,apt_1_bedroom_unit,franchise_code,wall_height,apt_2_bedroom_unit,wall_height_enclosure,garage_att_mas_c,perimeter,room_total,elev_elect_frght,room_bedroom,building_details,frame_util_bldg_upr,fireplace_metal_prefab,open_frame_porch_lwr,escalator_48,remodeled,market_index_adjustment,frame_util_bldg_pri,porch_open_upr_c,frame_bay_upr,base_value_medium_tank,bank_vault_no_door,frame_util_bldg_lwr,elev_hydro_frght,functional_utility,grade_adjustment,physical_condition,open_frame_porch_upr,parking_garage_upper_level_c,page_save
18710,1113770000001,LEED Gold Certification 60-79 points,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"324,758",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,Energy Star Certification,2021,Glass,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,"1,749",NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,Excellent,NaN,NaN,NaN,NaN,Wet,NaN,1,NaN,756.0,NaN,NaN,1981,NaN,NaN,"1,749",Displayed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,8344 -- Office Building,NaN,14.0,Central / Forced,NaN,NaN,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Displayed,NaN,NaN,NaN,NaN,Office Bldgs. Hi-Rise (5+ Stories),111% Market Index Adjustment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1113770000001_2021.html
18771,1113770000001,LEED Gold Certification 60-79 points,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"324,758",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,Energy Star Certification,2022,Glass,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,"1,749",NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,Excellent,NaN,NaN,NaN,NaN,Wet,NaN,1,NaN,756.0,NaN,NaN,1981,NaN,NaN,"1,749",Displayed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,8344 -- Office Building,NaN,14.0,Central / Forced,NaN,NaN,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Displayed,NaN,NaN,NaN,NaN,Office Bldgs. Hi-Rise (5+ Stories),100% No Mkt Index Adjustment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1113770000001_2022.html
18839,1113770000001,LEED Gold Certification 60-79 points,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"324,758",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,Energy Star Certification,2023,Glass,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,"1,749",NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,Excellent,NaN,NaN,NaN,NaN,Wet,NaN,1,NaN,756.0,NaN,NaN,1981,NaN,NaN,"1,749",Displayed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,8344 -- Office Building,NaN,14.0,Central / Forced,NaN,NaN,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Displayed,NaN,NaN,NaN,NaN,Office Bldgs. Hi-Rise (5+ Stories),100% No Mkt Index Adjustment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1113770000001_2023.html
18909,1113770000001,LEED Gold Certification 60-79 points,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"324,758",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,Energy Star Certification,2024,Glass,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,"1,749",NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,Excellent,NaN,NaN,NaN,NaN,Wet,NaN,1,NaN,756.0,NaN,NaN,1981,NaN,NaN,"1,749",Displayed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,8344 -- Office Building,NaN,14.0,Central / Forced,NaN,NaN,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Displayed,NaN,NaN,NaN,NaN,Office Bldgs. Hi-Rise (5+ Stories),100% No Mkt Index Adjustment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1113770000001_2024.html
18966,1113770000001,LEED Gold Certification 60-79 points,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"324,758",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,Energy Star Certification,2025,Glass,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,"1,749",NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,Excellent,NaN,NaN,NaN,NaN,Wet,NaN,1,NaN,756.0,NaN,NaN,1981,NaN,NaN,"1,749",Displayed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,8344 -- Office Building,NaN,14.0,Central / Forced,NaN,NaN,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Displayed,NaN,NaN,NaN,NaN,Office Bldgs. Hi-Rise (5+ Stories),100% No Mkt Index Adjustment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1113770000001_2025.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4965932,1329030010002,LEED Gold Certification 60-79 points,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very Poor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"164,070",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,Energy Star Certification,2025,Glass / Masonry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,"136,725",NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Excellent,NaN,NaN,NaN,NaN,Wet,NaN,2,NaN,NaN,NaN,NaN,2008,NaN,NaN,"27,345",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,8344 -- Office Building,NaN,6.0,Central / Forced,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,View,NaN,NaN,NaN,NaN,Office Bldgs. Hi-Rise (5+ Stories),100% No Mkt Index Adjustment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1329030010002_2025.html
4965934,1329030010002,LEED Gold Certification 60-79 points,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very Poor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"3,046",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,Energy Star Certification,2025,Concr Non-Ld Bearing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Excellent,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,2008,NaN,NaN,"3,046",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,8344 -- Office Building,NaN,NaN,Central / Forced,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,View,NaN,NaN,NaN,NaN,Office Bldgs. Low-Rise (1 to 4 Stories),100% No Mkt Index Adjustment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1329030010002_2025.html
4965962,1329030010002,LEED Gold Certification 60-79 points,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very Poor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"164,070",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,Energy Star Certification,2026,Glass / Masonry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,"136,725",NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Excellent,NaN,NaN,NaN,NaN,Wet,NaN,1,NaN,NaN,NaN,NaN,2008,NaN,NaN,"27,345",Displayed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,8344 -- Office Building,NaN,6.0,Central / Forced,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,Displayed,NaN,NaN,NaN,NaN,Office Bldgs. Hi-Rise (5+ Stories),100% No Mkt Index Adjustment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1329030010002_2026.html
4965963,1329030010002,LEED Gold Certification 60-79 points,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very Poor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"164,070",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,Energy Star Certification,2026,Glass / Masonry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,"136,725",NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Excellent,NaN,NaN,NaN,NaN,Wet,NaN,2,NaN,NaN,NaN,NaN,2008,NaN,NaN,"27,345",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,8344 -- Office Building,NaN,6.0,Central / Forced,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,View,NaN,NaN,NaN,NaN,Office Bldgs. Hi-Rise (5+ Stories),100% No Mkt Index Adjustment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1329030010002_2026.html
4965965,1329030010002,LEED Gold Certification 60-79 points,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very Poor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"3,046",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,Energy Star Certification,2026,Concr Non-Ld Bearing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,NaN,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Excellent,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,2008,NaN,NaN,"3,046",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,8344 -- Office Building,NaN,NaN,Central / Forced,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,View,NaN,NaN,NaN,NaN,Office Bldgs. Low-Rise (1 to 4 Stories),100% No Mkt Index Adjustment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Avg/Normal,NaN,Avg/Normal,NaN,NaN,1329030010002_2026.html

In [22]:
df['quality'].value_counts()

quality
Average      603165
Good         233651
Low          122080
Excellent     53669
1,440 *        7429
              ...
528,221           1
579,975           1
31,290            1
31,080            1
35,400            1
Name: count, Length: 24636, dtype: int64

In [23]:
df[df['quality']=='31,290']

,parcel_number,leed_certification_level,open_frame_porch_pri,elev_hydro_pass,basement,fireplace_open_1,unfin_basement_lwr,util_bldg_frm_c,frame_overhang_upr,one_story_mas_lwr,living_area_lwr,garage_interior_parking_apartments_c,parking_spaces,store_front_metal,unfin_l_a_upper,mobile_home_8_11_width,economic_obsolescence,cnpy_roof_ss_ave_c,mobile_home_30_width,base_value_small_tank,canopy_lwr,garage_att_frm_c,cost_and_design,unfin_l_a_primary,attic_finished,cond_desir_util,masonry_terrace_pri,bank_canopy_c,basement_top,one_story_frame_upr,enclosed_entry_c,masonry_bay_pri,encl_frame_porch_upr,cnpy_roof_ss_eco_c,comm_condo_neighborhood,fireplace_masonry_firebrick,basement_c,mas_brk_garage_pri,mobile_home_12_14_width,oh_door_motor_rs,quality,mas_conc_patio_pri,fireplace_direct_vent,bank_drive_thru,canopy_pri,frame_garage_pri,dock_level_floor_c,mobile_home_15_19_width,fireplace_adl_open,room_rec,cnpy_roof_ss_gd_c,interior_finish_percent,one_story_frame_pri,medical_beds,heating_ac,energy_star_certification,year,exterior_wall,base_area_lwr,masonry_bay_upr,room_full_bath,store_front_wood,util_bldg_mtl_c,masonry_overhang_upr,oh_door_motor_w_m,plumbing_type,base_area_upr,oh_door_roll_steel,mobile_home_20_29_width,atrium,open_mas_porch_upr,heating_type,masonry_overhang_pri,miscellaneous,one_story_mas_upr,office_warehouse_ratio,wood_deck_lwr,elevator_stops,open_mas_porch_pri,elev_elect_pass,style,mas_conc_patio_lwr,construction_type,carport_c,base_value_large_tank,sprinkler_type,porch_enclosed_c,building_number,stone_tile_patio_upper,area_hirise_ofc_c,mas_brk_garage_lwr,encl_frame_porch_pri,year_built,masonry_trim,encl_mas_porch_pri,base_area_pri,impr_sq_ft,stone_tile_patio_pri,oh_door_wood_mtl,base_value_tiny_tank,market_adjustment,half_story_mas_upr,ldng_ramp_conc_c,frame_garage_lwr,carport_lwr,truck_train_wells_c,open_mas_porch_lwr,apt_3_bedroom_unit,half_story_frame_upr,carport_pri,wood_deck_upr,cnpy_only_c,frame_overhang_pri,one_story_mas_pri,apt_effcncy_unit,sprinkler_wet,attic_unfinished,number_of_apartment_units,foundation_type,cnpy_roof_w_slab_c,craneway_5_ton,masnry_util_bldg_pri,partition_type,net_rentable_area,room_half_bath,wood_deck_pri,porch_open_c,parking_garage_c,type,frame_bay_pri,stories,cooling_type,apt_1_bedroom_unit,franchise_code,wall_height,apt_2_bedroom_unit,wall_height_enclosure,garage_att_mas_c,perimeter,room_total,elev_elect_frght,room_bedroom,building_details,frame_util_bldg_upr,fireplace_metal_prefab,open_frame_porch_lwr,escalator_48,remodeled,market_index_adjustment,frame_util_bldg_pri,porch_open_upr_c,frame_bay_upr,base_value_medium_tank,bank_vault_no_door,frame_util_bldg_lwr,elev_hydro_frght,functional_utility,grade_adjustment,physical_condition,open_frame_porch_upr,parking_garage_upper_level_c,page_save
4987250,421300000163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Moderate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"31,290",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2026,Glass / Masonry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequate,80,NaN,NaN,NaN,NaN,Hot Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Average,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,1977,NaN,NaN,740,Displayed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98,NaN,NaN,Normal,NaN,NaN,NaN,NaN,NaN,8344 -- Office Building,NaN,NaN,Central / Forced,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,Displayed,NaN,NaN,NaN,NaN,Office Bldgs. Low-Rise (1 to 4 Stories),100% No Mkt Index Adjustment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fair,NaN,Avg/Normal,NaN,NaN,0421300000163_2026.html

In [24]:

filtered_df = df[(df['parcel_number'] == 421300000163) ]

filtered_df = filtered_df.dropna(axis=1, how='all')
filtered_df

,parcel_number,economic_obsolescence,quality,interior_finish_percent,year,exterior_wall,plumbing_type,base_area_upr,heating_type,style,building_number,year_built,base_area_pri,impr_sq_ft,market_adjustment,cnpy_roof_w_slab_c,partition_type,type,cooling_type,wall_height,wall_height_enclosure,building_details,remodeled,market_index_adjustment,functional_utility,physical_condition,page_save
4987241,421300000163,Normal,"31,050",100.0,2021,Glass / Masonry,Adequate,80,Hot Air,Average,1,1977,740,Displayed,NaN,98,Normal,8344 -- Office Building,Central / Forced,12.0,NaN,Displayed,Office Bldgs. Low-Rise (1 to 4 Stories),111% Market Index Adjustment,Avg/Normal,Avg/Normal,0421300000163_2021.html
4987242,421300000163,Normal,"31,050",100.0,2022,Glass / Masonry,Adequate,80,Hot Air,Average,1,1977,740,Displayed,NaN,98,Normal,8344 -- Office Building,Central / Forced,12.0,NaN,Displayed,Office Bldgs. Low-Rise (1 to 4 Stories),100% No Mkt Index Adjustment,Avg/Normal,Avg/Normal,0421300000163_2022.html
4987244,421300000163,Moderate,"31,050",100.0,2023,Glass / Masonry,Adequate,80,Hot Air,Average,1,1977,740,Displayed,NaN,98,Normal,8344 -- Office Building,Central / Forced,NaN,12.0,Displayed,Office Bldgs. Low-Rise (1 to 4 Stories),100% No Mkt Index Adjustment,Fair,Avg/Normal,0421300000163_2023.html
4987246,421300000163,Moderate,"31,050",100.0,2024,Glass / Masonry,Adequate,80,Hot Air,Average,1,1977,740,Displayed,NaN,98,Normal,8344 -- Office Building,Central / Forced,NaN,12.0,Displayed,Office Bldgs. Low-Rise (1 to 4 Stories),100% No Mkt Index Adjustment,Fair,Avg/Normal,0421300000163_2024.html
4987248,421300000163,Moderate,"31,050",100.0,2025,Glass / Masonry,Adequate,80,Hot Air,Average,1,1977,740,Displayed,6% Market Adjustment,98,Normal,8344 -- Office Building,Central / Forced,NaN,12.0,Displayed,Office Bldgs. Low-Rise (1 to 4 Stories),100% No Mkt Index Adjustment,Fair,Avg/Normal,0421300000163_2025.html
4987250,421300000163,Moderate,"31,290",100.0,2026,Glass / Masonry,Adequate,80,Hot Air,Average,1,1977,740,Displayed,NaN,98,Normal,8344 -- Office Building,Central / Forced,NaN,12.0,Displayed,Office Bldgs. Low-Rise (1 to 4 Stories),100% No Mkt Index Adjustment,Fair,Avg/Normal,0421300000163_2026.html

## Change type into intger from column

In [41]:
cold = [ "elev_hydro_pass", "fireplace_open_1", "store_front_metal", "base_value_small_tank", "basement_top", "fireplace_masonry_firebrick", "oh_door_motor_w_m", "atrium", "miscellaneous", 
        "elevator_stops", "base_value_large_tank", "masonry_trim", "base_value_tiny_tank", "apt_3_bedroom_unit", "apt_effcncy_unit", "sprinkler_wet", "number_of_apartment_units", "craneway_5_ton",
          "net_rentable_area", "room_half_bath", "frame_bay_pri", "apt_1_bedroom_unit", "franchise_code", "apt_2_bedroom_unit", "room_total", "elev_elect_frght", "room_bedroom", 
        "fireplace_metal_prefab", "escalator_48", "frame_bay_upr", "base_value_medium_tank", "bank_vault_no_door", "elev_hydro_frght", "base_area_pri", "parking_garage_upper_level_c", "base_area_upr" ,]

df[cold] = df[cold].replace(',', '', regex=True)
df[cold] = df[cold].astype('Int64')
df[cold]

,elev_hydro_pass,fireplace_open_1,store_front_metal,base_value_small_tank,basement_top,fireplace_masonry_firebrick,oh_door_motor_w_m,atrium,miscellaneous,elevator_stops,base_value_large_tank,masonry_trim,base_value_tiny_tank,apt_3_bedroom_unit,apt_effcncy_unit,sprinkler_wet,number_of_apartment_units,craneway_5_ton,net_rentable_area,room_half_bath,frame_bay_pri,apt_1_bedroom_unit,franchise_code,apt_2_bedroom_unit,room_total,elev_elect_frght,room_bedroom,fireplace_metal_prefab,escalator_48,frame_bay_upr,base_value_medium_tank,bank_vault_no_door,elev_hydro_frght,base_area_pri,parking_garage_upper_level_c,base_area_upr
0,<NA>,<NA>,1,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,13054,<NA>,<NA>
1,<NA>,<NA>,1,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4958,<NA>,<NA>
2,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,11160,<NA>,<NA>
3,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,23030,<NA>,<NA>
4,<NA>,<NA>,1,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,13054,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4988247,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5287,<NA>,<NA>
4988248,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5287,<NA>,<NA>
4988249,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5287,<NA>,<NA>
4988250,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5287,<NA>,<NA>
4988251,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5287,<NA>,<NA>

## Chnage type into float  from columns

In [26]:
cols = ["open_frame_porch_pri","basement","unfin_basement_lwr","util_bldg_frm_c","one_story_mas_lwr","living_area_lwr","garage_interior_parking_apartments_c","unfin_l_a_upper","mobile_home_8_11_width",
        "cnpy_roof_ss_ave_c","canopy_lwr","garage_att_frm_c","unfin_l_a_primary","attic_finished","masonry_terrace_pri","bank_canopy_c","one_story_frame_upr","enclosed_entry_c","masonry_bay_pri","encl_frame_porch_upr",
        "cnpy_roof_ss_eco_c","basement_c","mas_brk_garage_pri","mobile_home_12_14_width","mas_conc_patio_pri","canopy_pri","frame_garage_pri","dock_level_floor_c","mobile_home_15_19_width","cnpy_roof_ss_gd_c","one_story_frame_pri",
        "base_area_lwr","masonry_bay_upr","util_bldg_mtl_c","open_mas_porch_upr","masonry_overhang_pri","one_story_mas_upr","wood_deck_lwr","open_mas_porch_pri","mas_conc_patio_lwr","carport_c","porch_enclosed_c","stone_tile_patio_upper",
        "area_hirise_ofc_c","mas_brk_garage_lwr","encl_frame_porch_pri","encl_mas_porch_pri","stone_tile_patio_pri","half_story_mas_upr","ldng_ramp_conc_c","frame_garage_lwr","carport_lwr","truck_train_wells_c","open_mas_porch_lwr",
        "half_story_frame_upr","carport_pri","wood_deck_upr","cnpy_only_c","one_story_mas_pri","attic_unfinished","cnpy_roof_w_slab_c","masnry_util_bldg_pri","wood_deck_pri","porch_open_c","parking_garage_c","garage_att_mas_c",
        "perimeter","frame_util_bldg_upr","open_frame_porch_lwr","frame_util_bldg_pri","porch_open_upr_c","frame_util_bldg_lwr","open_frame_porch_upr","mobile_home_30_width","mobile_home_20_29_width", "parking_spaces", "stories", 
        "wall_height", "wall_height_enclosure",
    "interior_finish_percent", "office_warehouse_ratio"]
df[cols] = df[cols].replace(',', '', regex=True)
df[cols] = df[cols].astype(float)
df[cols]

,open_frame_porch_pri,basement,unfin_basement_lwr,util_bldg_frm_c,one_story_mas_lwr,living_area_lwr,garage_interior_parking_apartments_c,unfin_l_a_upper,mobile_home_8_11_width,cnpy_roof_ss_ave_c,canopy_lwr,garage_att_frm_c,unfin_l_a_primary,attic_finished,masonry_terrace_pri,bank_canopy_c,one_story_frame_upr,enclosed_entry_c,masonry_bay_pri,encl_frame_porch_upr,cnpy_roof_ss_eco_c,basement_c,mas_brk_garage_pri,mobile_home_12_14_width,mas_conc_patio_pri,canopy_pri,frame_garage_pri,dock_level_floor_c,mobile_home_15_19_width,cnpy_roof_ss_gd_c,one_story_frame_pri,base_area_lwr,masonry_bay_upr,util_bldg_mtl_c,open_mas_porch_upr,masonry_overhang_pri,one_story_mas_upr,wood_deck_lwr,open_mas_porch_pri,mas_conc_patio_lwr,carport_c,porch_enclosed_c,stone_tile_patio_upper,area_hirise_ofc_c,mas_brk_garage_lwr,encl_frame_porch_pri,encl_mas_porch_pri,stone_tile_patio_pri,half_story_mas_upr,ldng_ramp_conc_c,frame_garage_lwr,carport_lwr,truck_train_wells_c,open_mas_porch_lwr,half_story_frame_upr,carport_pri,wood_deck_upr,cnpy_only_c,one_story_mas_pri,attic_unfinished,cnpy_roof_w_slab_c,masnry_util_bldg_pri,wood_deck_pri,porch_open_c,parking_garage_c,garage_att_mas_c,perimeter,frame_util_bldg_upr,open_frame_porch_lwr,frame_util_bldg_pri,porch_open_upr_c,frame_util_bldg_lwr,open_frame_porch_upr,mobile_home_30_width,mobile_home_20_29_width,parking_spaces,stories,wall_height,wall_height_enclosure,interior_finish_percent,office_warehouse_ratio
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,100.0,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4646.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,100.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,100.0,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,100.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4988247,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,991.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,137.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,100.0,NaN
4988248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,991.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,137.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,100.0,NaN
4988249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,991.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,137.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,100.0,NaN
4988250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,991.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,137.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,100.0,NaN
4988251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,991.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,137.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,100.0,NaN

In [27]:
df.info(verbose=True,show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4988252 entries, 0 to 4988251
Data columns (total 162 columns):
 #    Column                                Non-Null Count    Dtype
---   ------                                --------------    -----
 0    parcel_number                         4988252 non-null  int64
 1    leed_certification_level              541 non-null      object
 2    open_frame_porch_pri                  2615132 non-null  float64
 3    elev_hydro_pass                       3790 non-null     Int64
 4    basement                              1454 non-null     float64
 5    fireplace_open_1                      697 non-null      Int64
 6    unfin_basement_lwr                    579 non-null      float64
 7    util_bldg_frm_c                       8731 non-null     float64
 8    frame_overhang_upr                    118276 non-null   float64
 9    one_story_mas_lwr                     956 non-null      float64
 10   living_area_lwr                       1271 non-null     float64
 11   garage_interior_parking_apartments_c  4456 non-null     float64
 12   parking_spaces                        1025 non-null     float64
 13   store_front_metal                     20503 non-null    Int64
 14   unfin_l_a_upper                       2572 non-null     float64
 15   mobile_home_8_11_width                2367 non-null     float64
 16   economic_obsolescence                 491169 non-null   object
 17   cnpy_roof_ss_ave_c                    1891 non-null     float64
 18   mobile_home_30_width                  2639 non-null     float64
 19   base_value_small_tank                 3978 non-null     Int64
 20   canopy_lwr                            16114 non-null    float64
 21   garage_att_frm_c                      4667 non-null     float64
 22   cost_and_design                       1153901 non-null  object
 23   unfin_l_a_primary                     526 non-null      float64
 24   attic_finished                        130021 non-null   float64
 25   cond_desir_util                       4472728 non-null  object
 26   masonry_terrace_pri                   27393 non-null    float64
 27   bank_canopy_c                         3578 non-null     float64
 28   basement_top                          62 non-null       Int64
 29   one_story_frame_upr                   407718 non-null   float64
 30   enclosed_entry_c                      1177 non-null     float64
 31   masonry_bay_pri                       37557 non-null    float64
 32   encl_frame_porch_upr                  1828 non-null     float64
 33   cnpy_roof_ss_eco_c                    678 non-null      float64
 34   comm_condo_neighborhood               6993 non-null     object
 35   fireplace_masonry_firebrick           892900 non-null   Int64
 36   basement_c                            539 non-null      float64
 37   mas_brk_garage_pri                    2101497 non-null  float64
 38   mobile_home_12_14_width               28882 non-null    float64
 39   oh_door_motor_rs                      916 non-null      float64
 40   quality                               4988252 non-null  object
 41   mas_conc_patio_pri                    593313 non-null   float64
 42   fireplace_direct_vent                 108980 non-null   float64
 43   bank_drive_thru                       1355 non-null     float64
 44   canopy_pri                            153376 non-null   float64
 45   frame_garage_pri                      496304 non-null   float64
 46   dock_level_floor_c                    174 non-null      float64
 47   mobile_home_15_19_width               12042 non-null    float64
 48   fireplace_adl_open                    18317 non-null    float64
 49   room_rec                              1587644 non-null  float64
 50   cnpy_roof_ss_gd_c                     2065 non-null     float64
 51   interior_finish_percent               464550 non-null   float64
 52   one_story_frame_pri                   535971 non-null   float64
 53   medical_beds                          486 non-null      float64
 54   heating_ac                            4131626 non-null  object
 55   energy_star_certification             832 non-null      object
 56   year                                  4988252 non-null  int64
 57   exterior_wall                         4959775 non-null  object
 58   base_area_lwr                         76432 non-null    float64
 59   masonry_bay_upr                       1400 non-null     float64
 60   room_full_bath                        4472412 non-null  float64
 61   store_front_wood                      1465 non-null     float64
 62   util_bldg_mtl_c                       2870 non-null     float64
 63   masonry_overhang_upr                  4238 non-null     float64
 64   oh_door_motor_w_m                     1384 non-null     Int64
 65   plumbing_type                         440921 non-null   object
 66   base_area_upr                         1684872 non-null  Int64
 67   oh_door_roll_steel                    31230 non-null    float64
 68   mobile_home_20_29_width               15395 non-null    float64
 69   atrium                                6445 non-null     Int64
 70   open_mas_porch_upr                    31134 non-null    float64
 71   heating_type                          333887 non-null   object
 72   masonry_overhang_pri                  1200 non-null     float64
 73   miscellaneous                         540 non-null      Int64
 74   one_story_mas_upr                     115162 non-null   float64
 75   office_warehouse_ratio                60613 non-null    float64
 76   wood_deck_lwr                         1472 non-null     float64
 77   elevator_stops                        17409 non-null    Int64
 78   open_mas_porch_pri                    1474209 non-null  float64
 79   elev_elect_pass                       9804 non-null     float64
 80   style                                 4988252 non-null  object
 81   mas_conc_patio_lwr                    4209 non-null     float64
 82   construction_type                     24267 non-null    object
 83   carport_c                             4802 non-null     float64
 84   base_value_large_tank                 701 non-null      Int64
 85   sprinkler_type                        43403 non-null    object
 86   porch_enclosed_c                      3534 non-null     float64
 87   building_number                       4988252 non-null  int64
 88   stone_tile_patio_upper                4508 non-null     float64
 89   area_hirise_ofc_c                     64 non-null       float64
 90   mas_brk_garage_lwr                    24574 non-null    float64
 91   encl_frame_porch_pri                  121662 non-null   float64
 92   year_built                            4988252 non-null  int64
 93   masonry_trim                          128032 non-null   Int64
 94   encl_mas_porch_pri                    9256 non-null     float64
 95   base_area_pri                         4920170 non-null  Int64
 96   impr_sq_ft                            4733883 non-null  object
 97   stone_tile_patio_pri                  33688 non-null    float64
 98   oh_door_wood_mtl                      107258 non-null   float64
 99   base_value_tiny_tank                  7687 non-null     Int64
 100  market_adjustment                     87495 non-null    object
 101  half_story_mas_upr                    2047 non-null     float64
 102  ldng_ramp_conc_c                      1705 non-null     float64
 103  frame_garage_lwr                      77382 non-null    float64
 104  carport_lwr                           5086 non-null     float64
 105  truck_train_wells_c                   3899 non-null     float64
 106  open_mas_porch_lwr                    11738 non-null    float64
 107  apt_3_bedroom_unit                    8717 non-null     Int64
 108  half_story_frame_upr                  7326 non-null     float64
 109  carport_pri                           189321 non-null   float64
 110  wood_deck_upr                         29703 non-null    float64
 111  cnpy_only_c                           26752 non-null    float64
 112  frame_overhang_pri                    8110 non-null     float64
 113  one_story_mas_pri                     677420 non-null   float64
 114  apt_effcncy_unit                      2782 non-null     Int64
 115  sprinkler_wet                         2461 non-null     Int64
 116  attic_unfinished                      24263 non-null    float64
 117  number_of_apartment_units             1684 non-null     Int64
 118  foundation_type                       4472730 non-null  object
 119  cnpy_roof_w_slab_c                    117468 non-null   float64
 120  craneway_5_ton                        654 non-null      Int64
 121  masnry_util_bldg_pri                  10992 non-null    float64
 122  partition_type                        446997 non-null   object
 123  net_rentable_area                     1068 non-null     Int64
 124  room_half_bath                        1761052 non-null  Int64
 125  wood_deck_pri                         160941 non-null   float64
 126  porch_open_c                          110041 non-null   float64
 127  parking_garage_c                      1612 non-null     float64
 128  type                                  4988252 non-null  object
 129  frame_bay_pri                         15464 non-null    Int64
 130  stories                               44838 non-null    float64
 131  cooling_type                          311928 non-null   object
 132  apt_1_bedroom_unit                    34940 non-null    Int64
 133  franchise_code                        10080 non-null    Int64
 134  wall_height                           345669 non-null   float64
 135  apt_2_bedroom_unit                    36675 non-null    Int64
 136  wall_height_enclosure                 148762 non-null   float64
 137  garage_att_mas_c                      1024 non-null     float64
 138  perimeter                             566 non-null      float64
 139  room_total                            4472521 non-null  Int64
 140  elev_elect_frght                      3925 non-null     Int64
 141  room_bedroom                          4472840 non-null  Int64
 142  building_details                      4985587 non-null  object
 143  frame_util_bldg_upr                   2094 non-null     float64
 144  fireplace_metal_prefab                1478397 non-null  Int64
 145  open_frame_porch_lwr                  34349 non-null    float64
 146  escalator_48                          203 non-null      Int64
 147  remodeled                             4988234 non-null  object
 148  market_index_adjustment               470798 non-null   object
 149  frame_util_bldg_pri                   74298 non-null    float64
 150  porch_open_upr_c                      89188 non-null    float64
 151  frame_bay_upr                         2135 non-null     Int64
 152  base_value_medium_tank                6236 non-null     Int64
 153  bank_vault_no_door                    662 non-null      Int64
 154  frame_util_bldg_lwr                   4171 non-null     float64
 155  elev_hydro_frght                      658 non-null      Int64
 156  functional_utility                    489806 non-null   object
 157  grade_adjustment                      4474587 non-null  object
 158  physical_condition                    4964694 non-null  object
 159  open_frame_porch_upr                  116118 non-null   float64
 160  parking_garage_upper_level_c          1315 non-null     Int64
 161  page_save                             4988252 non-null  object
dtypes: Int64(36), float64(95), int64(4), object(27)
memory usage: 6.2+ GB

In [28]:
result = {}

for col in df.columns:
    vals = df[col].astype(str)
    filtered = vals[vals.str.len() == 1].unique().tolist()
    
    if filtered: 
        result[col] = filtered

print(result)

{'elev_hydro_pass': ['1', '2', '3', '6', '0', '5', '4', '7', '8'], 'fireplace_open_1': ['1', '3', '2', '0', '8', '9', '4'], 'store_front_metal': ['1', '2', '3', '4', '0', '8', '6'], 'base_value_small_tank': ['1', '0'], 'basement_top': ['1'], 'fireplace_masonry_firebrick': ['1', '2', '4', '3', '0', '5', '6', '7', '8', '9'], 'quality': ['0'], 'oh_door_motor_w_m': ['1', '2', '5', '8', '4', '7', '6', '3', '0', '9'], 'base_area_upr': ['9', '3', '8', '7', '4', '6'], 'atrium': ['1', '3', '6'], 'miscellaneous': ['1', '4', '2', '8', '3'], 'elevator_stops': ['3', '2', '4', '5', '1', '0'], 'base_value_large_tank': ['1'], 'building_number': ['1', '2', '6', '7', '3', '4', '9', '5', '8'], 'year_built': ['0'], 'masonry_trim': ['1', '2'], 'base_area_pri': ['0', '9', '6', '8', '2', '1', '7'], 'impr_sq_ft': ['0', '1'], 'base_value_tiny_tank': ['1', '0'], 'apt_3_bedroom_unit': ['0', '6', '8', '3', '4', '5', '1', '9', '2', '7'], 'apt_effcncy_unit': ['2', '4', '8', '9', '0', '6', '3', '7', '1', '5'], 'sprinkler_wet': ['1', '2', '0', '3', '4', '6'], 'number_of_apartment_units': ['2', '4', '8', '9', '6', '7', '5', '3', '0', '1'], 'craneway_5_ton': ['3', '1', '2', '0', '6', '5'], 'net_rentable_area': ['0', '1'], 'room_half_bath': ['1', '2', '3', '5', '0', '4', '8', '7', '6'], 'frame_bay_pri': ['5', '6', '8', '4', '7', '9'], 'apt_1_bedroom_unit': ['4', '0', '6', '3', '2', '8', '5', '1', '7', '9'], 'franchise_code': ['0'], 'apt_2_bedroom_unit': ['0', '4', '2', '8', '1', '6', '3', '9', '5', '7'], 'room_total': ['6', '8', '7', '4', '5', '9', '3', '2', '1', '0'], 'elev_elect_frght': ['1', '2', '0', '4', '3', '6', '5'], 'room_bedroom': ['3', '4', '2', '1', '6', '5', '8', '7', '9', '0'], 'fireplace_metal_prefab': ['1', '2', '3', '0', '4', '5', '6', '7', '8'], 'escalator_48': ['2', '4', '1', '6'], 'remodeled': ['8'], 'frame_bay_upr': ['6', '8', '9'], 'base_value_medium_tank': ['1'], 'bank_vault_no_door': ['1', '0', '2'], 'elev_hydro_frght': ['1', '2', '4', '3', '0'], 'grade_adjustment': ['C', 'D', 'A', 'B', 'X', 'E']}

In [29]:


checks = {
    "Numeric 0": [0, 0.0],
    "String '0'": ['0', '00', '0.0','0 x 0 x 0'],
    "Hyphen '-'": ['-', '--', '---', '----'],
    "Symbols": ['+', '_', '=', '\\', '|', '!', '@', '`', '~', "'", '"', "''", '""'],
    "Question marks": ['?', '???', '??', '????', '?? 00000'],
    "Punctuation": ['%', '&', '^', '*', '(', ')', '[', ']', '{', '}'],
    "Dots / Slash": ['..', '...', '…', '', ' ', '/', '.'],
    "Unknown text": ['UNK','unk','Unknown','unknown','UNKNOWN','Unkown','Unkonw','UNKNOW'],
    "NA values": ['Na','N/A','N/a','n/A','n/ a','N.A','N/A/','null','none','nan','nil','None','NONE'],
    "Other": ['XXXXX','x x','unsure','undeveloped']
}

# Flatten junk values
all_bad_values = [v for vals in checks.values() for v in vals]

junk_mask = df.isin(all_bad_values)

print("===== DETAILED JUNK VALUE REPORT =====")

for category, values in checks.items():
    print(f"\n=== {category} ===")
    
    columns_with_junk = []   # store columns
    
    for col in df.columns:
        counts = df[col].value_counts(dropna=False)
        junk_counts = counts[counts.index.isin(values)]
        
        if not junk_counts.empty:
            columns_with_junk.append(col)
            
            print(f"\nColumn: {col}")
            for val, cnt in junk_counts.items():
                print(f"{val} : {cnt}")
    
    # NEW PART: show columns list
    if columns_with_junk:
        print(f"\nColumns containing {category}: {columns_with_junk}")

# Total junk count per column
total_junk_counts = junk_mask.sum()
total_junk_counts = total_junk_counts[total_junk_counts > 0]

print("\n===== TOTAL JUNK COUNT PER COLUMN =====")
print(total_junk_counts)

===== DETAILED JUNK VALUE REPORT =====

=== Numeric 0 ===

Column: open_frame_porch_pri
0.0 : 49

Column: elev_hydro_pass
0 : 15

Column: fireplace_open_1
0 : 12

Column: frame_overhang_upr
0.0 : 18

Column: garage_interior_parking_apartments_c
0.0 : 6

Column: parking_spaces
0.0 : 42

Column: store_front_metal
0 : 61

Column: base_value_small_tank
0 : 6

Column: canopy_lwr
0.0 : 6

Column: attic_finished
0.0 : 5

Column: one_story_frame_upr
0.0 : 12

Column: fireplace_masonry_firebrick
0 : 109

Column: mas_brk_garage_pri
0.0 : 19

Column: mas_conc_patio_pri
0.0 : 1

Column: fireplace_direct_vent
0.0 : 116

Column: bank_drive_thru
0.0 : 3

Column: frame_garage_pri
0.0 : 6

Column: room_rec
0.0 : 541

Column: interior_finish_percent
0.0 : 38344

Column: medical_beds
0.0 : 225

Column: room_full_bath
0.0 : 31

Column: store_front_wood
0.0 : 6

Column: oh_door_motor_w_m
0 : 25

Column: oh_door_roll_steel
0.0 : 263

Column: office_warehouse_ratio
0.0 : 6023

Column: elevator_stops
0 : 10

Column: open_mas_porch_pri
0.0 : 12

Column: elev_elect_pass
0.0 : 1968

Column: year_built
0 : 16

Column: base_area_pri
0 : 139

Column: oh_door_wood_mtl
0.0 : 2203

Column: base_value_tiny_tank
0 : 30

Column: apt_3_bedroom_unit
0 : 5709

Column: one_story_mas_pri
0.0 : 12

Column: apt_effcncy_unit
0 : 31

Column: sprinkler_wet
0 : 109

Column: attic_unfinished
0.0 : 1703

Column: number_of_apartment_units
0 : 28

Column: craneway_5_ton
0 : 6

Column: net_rentable_area
0 : 126

Column: room_half_bath
0 : 1140

Column: porch_open_c
0.0 : 16

Column: stories
0.0 : 777

Column: apt_1_bedroom_unit
0 : 27171

Column: franchise_code
0 : 10

Column: wall_height
0.0 : 2143

Column: apt_2_bedroom_unit
0 : 28964

Column: wall_height_enclosure
0.0 : 1240

Column: room_total
0 : 41

Column: elev_elect_frght
0 : 2184

Column: room_bedroom
0 : 77

Column: fireplace_metal_prefab
0 : 3846

Column: bank_vault_no_door
0 : 188

Column: elev_hydro_frght
0 : 12

Columns containing Numeric 0: ['open_frame_porch_pri', 'elev_hydro_pass', 'fireplace_open_1', 'frame_overhang_upr', 'garage_interior_parking_apartments_c', 'parking_spaces', 'store_front_metal', 'base_value_small_tank', 'canopy_lwr', 'attic_finished', 'one_story_frame_upr', 'fireplace_masonry_firebrick', 'mas_brk_garage_pri', 'mas_conc_patio_pri', 'fireplace_direct_vent', 'bank_drive_thru', 'frame_garage_pri', 'room_rec', 'interior_finish_percent', 'medical_beds', 'room_full_bath', 'store_front_wood', 'oh_door_motor_w_m', 'oh_door_roll_steel', 'office_warehouse_ratio', 'elevator_stops', 'open_mas_porch_pri', 'elev_elect_pass', 'year_built', 'base_area_pri', 'oh_door_wood_mtl', 'base_value_tiny_tank', 'apt_3_bedroom_unit', 'one_story_mas_pri', 'apt_effcncy_unit', 'sprinkler_wet', 'attic_unfinished', 'number_of_apartment_units', 'craneway_5_ton', 'net_rentable_area', 'room_half_bath', 'porch_open_c', 'stories', 'apt_1_bedroom_unit', 'franchise_code', 'wall_height', 'apt_2_bedroom_unit', 'wall_height_enclosure', 'room_total', 'elev_elect_frght', 'room_bedroom', 'fireplace_metal_prefab', 'bank_vault_no_door', 'elev_hydro_frght']

=== String '0' ===

Column: quality
0 : 2587

Column: impr_sq_ft
0 : 211

Columns containing String '0': ['quality', 'impr_sq_ft']

=== Hyphen '-' ===

Column: remodeled
-- : 65857

Columns containing Hyphen '-': ['remodeled']

=== Symbols ===

=== Question marks ===

=== Punctuation ===

=== Dots / Slash ===

=== Unknown text ===

Column: heating_type
Unknown : 2224

Columns containing Unknown text: ['heating_type']

=== NA values ===

=== Other ===

===== TOTAL JUNK COUNT PER COLUMN =====
open_frame_porch_pri                       49
elev_hydro_pass                            15
fireplace_open_1                           12
frame_overhang_upr                         18
garage_interior_parking_apartments_c        6
parking_spaces                             42
store_front_metal                          61
base_value_small_tank                       6
canopy_lwr                                  6
attic_finished                              5
one_story_frame_upr                        12
fireplace_masonry_firebrick               109
mas_brk_garage_pri                         19
quality                                  2587
mas_conc_patio_pri                          1
fireplace_direct_vent                     116
bank_drive_thru                             3
frame_garage_pri                            6
room_rec                                  541
interior_finish_percent                 38344
medical_beds                              225
room_full_bath                             31
store_front_wood                            6
oh_door_motor_w_m                          25
oh_door_roll_steel                        263
heating_type                             2224
office_warehouse_ratio                   6023
elevator_stops                             10
open_mas_porch_pri                         12
elev_elect_pass                          1968
year_built                                 16
base_area_pri                             139
impr_sq_ft                                211
oh_door_wood_mtl                         2203
base_value_tiny_tank                       30
apt_3_bedroom_unit                       5709
one_story_mas_pri                          12
apt_effcncy_unit                           31
sprinkler_wet                             109
attic_unfinished                         1703
number_of_apartment_units                  28
craneway_5_ton                              6
net_rentable_area                         126
room_half_bath                           1140
porch_open_c                               16
stories                                   777
apt_1_bedroom_unit                      27171
franchise_code                             10
wall_height                              2143
apt_2_bedroom_unit                      28964
wall_height_enclosure                    1240
room_total                                 41
elev_elect_frght                         2184
room_bedroom                               77
fireplace_metal_prefab                   3846
remodeled                               65857
bank_vault_no_door                        188
elev_hydro_frght                           12
dtype: Int64

## Replacing the '0' value with null from column 'open_frame_porch_pri', 'elev_hydro_pass', 'fireplace_open_1', 'frame_overhang_upr', 'garage_interior_parking_apartments_c', 'parking_spaces', 'store_front_metal', 'base_value_small_tank', 'canopy_lwr', 'attic_finished', 'one_story_frame_upr', 'fireplace_masonry_firebrick', 'mas_brk_garage_pri', 'mas_conc_patio_pri', 'fireplace_direct_vent', 'bank_drive_thru', 'frame_garage_pri', 'room_rec', 'interior_finish_percent', 'medical_beds', 'room_full_bath', 'store_front_wood', 'oh_door_motor_w_m', 'oh_door_roll_steel', 'office_warehouse_ratio', 'elevator_stops', 'open_mas_porch_pri', 'elev_elect_pass', 'year_built', 'base_area_pri', 'oh_door_wood_mtl', 'base_value_tiny_tank', 'apt_3_bedroom_unit', 'one_story_mas_pri', 'apt_effcncy_unit', 'sprinkler_wet', 'attic_unfinished', 'number_of_apartment_units', 'craneway_5_ton', 'net_rentable_area', 'room_half_bath', 'porch_open_c', 'stories', 'apt_1_bedroom_unit', 'franchise_code', 'wall_height', 'apt_2_bedroom_unit', 'wall_height_enclosure', 'room_total', 'elev_elect_frght', 'room_bedroom', 'fireplace_metal_prefab', 'bank_vault_no_door' and  'elev_hydro_frght'

In [36]:
colss =  ['open_frame_porch_pri', 'elev_hydro_pass', 'fireplace_open_1', 'frame_overhang_upr', 'garage_interior_parking_apartments_c', 'parking_spaces', 'store_front_metal', 'base_value_small_tank', 'canopy_lwr', 'attic_finished',
         'one_story_frame_upr', 'fireplace_masonry_firebrick', 'mas_brk_garage_pri', 'mas_conc_patio_pri', 'fireplace_direct_vent', 'bank_drive_thru', 'frame_garage_pri', 'room_rec', 'interior_finish_percent', 'medical_beds', 
         'room_full_bath', 'store_front_wood', 'oh_door_motor_w_m', 'oh_door_roll_steel', 'office_warehouse_ratio', 'elevator_stops', 'open_mas_porch_pri', 'elev_elect_pass', 'year_built', 'base_area_pri',
          'oh_door_wood_mtl', 'base_value_tiny_tank', 'apt_3_bedroom_unit', 'one_story_mas_pri', 'apt_effcncy_unit', 'sprinkler_wet', 'attic_unfinished', 'number_of_apartment_units',
          'craneway_5_ton', 'net_rentable_area', 'room_half_bath', 'porch_open_c', 'stories', 'apt_1_bedroom_unit', 'franchise_code', 'wall_height', 'apt_2_bedroom_unit', 'wall_height_enclosure', 
         'room_total', 'elev_elect_frght', 'room_bedroom', 'fireplace_metal_prefab', 'bank_vault_no_door', 'elev_hydro_frght']
df[colss] = df[colss].replace(0,np.nan)
df[colss]

,open_frame_porch_pri,elev_hydro_pass,fireplace_open_1,frame_overhang_upr,garage_interior_parking_apartments_c,parking_spaces,store_front_metal,base_value_small_tank,canopy_lwr,attic_finished,one_story_frame_upr,fireplace_masonry_firebrick,mas_brk_garage_pri,mas_conc_patio_pri,fireplace_direct_vent,bank_drive_thru,frame_garage_pri,room_rec,interior_finish_percent,medical_beds,room_full_bath,store_front_wood,oh_door_motor_w_m,oh_door_roll_steel,office_warehouse_ratio,elevator_stops,open_mas_porch_pri,elev_elect_pass,year_built,base_area_pri,oh_door_wood_mtl,base_value_tiny_tank,apt_3_bedroom_unit,one_story_mas_pri,apt_effcncy_unit,sprinkler_wet,attic_unfinished,number_of_apartment_units,craneway_5_ton,net_rentable_area,room_half_bath,porch_open_c,stories,apt_1_bedroom_unit,franchise_code,wall_height,apt_2_bedroom_unit,wall_height_enclosure,room_total,elev_elect_frght,room_bedroom,fireplace_metal_prefab,bank_vault_no_door,elev_hydro_frght
0,NaN,<NA>,<NA>,NaN,NaN,NaN,1,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,NaN,NaN,1990.0,13054,NaN,<NA>,<NA>,NaN,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,14.0,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,NaN,<NA>,<NA>,NaN,NaN,NaN,1,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,NaN,NaN,1990.0,4958,NaN,<NA>,<NA>,NaN,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,14.0,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,NaN,<NA>,<NA>,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,NaN,NaN,1990.0,11160,NaN,<NA>,<NA>,NaN,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,14.0,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,NaN,<NA>,<NA>,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,NaN,NaN,1990.0,23030,NaN,<NA>,<NA>,NaN,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,NaN,<NA>,<NA>,NaN,NaN,NaN,1,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,NaN,NaN,1990.0,13054,NaN,<NA>,<NA>,NaN,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,NaN,NaN,<NA>,<NA>,14.0,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4988247,NaN,<NA>,<NA>,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,NaN,NaN,2010.0,5287,NaN,<NA>,<NA>,NaN,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,137.0,NaN,<NA>,<NA>,NaN,<NA>,9.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4988248,NaN,<NA>,<NA>,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,NaN,NaN,2010.0,5287,NaN,<NA>,<NA>,NaN,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,137.0,NaN,<NA>,<NA>,9.0,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4988249,NaN,<NA>,<NA>,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,NaN,NaN,2010.0,5287,NaN,<NA>,<NA>,NaN,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,137.0,NaN,<NA>,<NA>,9.0,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4988250,NaN,<NA>,<NA>,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,NaN,NaN,2010.0,5287,NaN,<NA>,<NA>,NaN,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,137.0,NaN,<NA>,<NA>,9.0,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4988251,NaN,<NA>,<NA>,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,<NA>,NaN,NaN,<NA>,NaN,NaN,2010.0,5287,NaN,<NA>,<NA>,NaN,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,137.0,NaN,<NA>,<NA>,9.0,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

## Replacing the '0' value with null from columnn 'quality' and 'impr_sq_ft'

In [37]:
colf = ['quality', 'impr_sq_ft']
df[colf] = df[colf].replace('0',np.nan)
df[colf]

         quality impr_sq_ft
0           Good     13,054
1        Average      4,958
2           Good     11,160
3           Good     23,030
4           Good     13,054
...          ...        ...
4988247    5,287        NaN
4988248    5,287        NaN
4988249    5,287        NaN
4988250    5,287        NaN
4988251    5,287        NaN

[4988252 rows x 2 columns]

In [43]:
cold = ['impr_sq_ft']

# Step 1: remove commas
df['impr_sq_ft'] = df['impr_sq_ft'].astype(str).str.replace(',', '')

# Step 2: keep ONLY valid integers (others → NaN)
mask = df['impr_sq_ft'].str.fullmatch(r'\d+')

df.loc[~mask, 'impr_sq_ft'] = pd.NA

# Step 3: strict conversion (no error now)
df['impr_sq_ft'] = df['impr_sq_ft'].astype('Int64')
df['impr_sq_ft']

0          13054
1           4958
2          11160
3          23030
4          13054
           ...
4988247     <NA>
4988248     <NA>
4988249     <NA>
4988250     <NA>
4988251     <NA>
Name: impr_sq_ft, Length: 4988252, dtype: Int64

In [44]:


checks = {
    "Numeric 0": [0, 0.0],
    "String '0'": ['0', '00', '0.0','0 x 0 x 0'],
    "Hyphen '-'": ['-', '--', '---', '----'],
    "Symbols": ['+', '_', '=', '\\', '|', '!', '@', '`', '~', "'", '"', "''", '""'],
    "Question marks": ['?', '???', '??', '????', '?? 00000'],
    "Punctuation": ['%', '&', '^', '*', '(', ')', '[', ']', '{', '}'],
    "Dots / Slash": ['..', '...', '…', '', ' ', '/', '.'],
    "Unknown text": ['UNK','unk','Unknown','unknown','UNKNOWN','Unkown','Unkonw','UNKNOW'],
    "NA values": ['Na','N/A','N/a','n/A','n/ a','N.A','N/A/','null','none','nan','nil','None','NONE'],
    "Other": ['XXXXX','x x','unsure','undeveloped']
}

# Flatten junk values
all_bad_values = [v for vals in checks.values() for v in vals]

junk_mask = df.isin(all_bad_values)

print("===== DETAILED JUNK VALUE REPORT =====")

for category, values in checks.items():
    print(f"\n=== {category} ===")
    
    columns_with_junk = []   # store columns
    
    for col in df.columns:
        counts = df[col].value_counts(dropna=False)
        junk_counts = counts[counts.index.isin(values)]
        
        if not junk_counts.empty:
            columns_with_junk.append(col)
            
            print(f"\nColumn: {col}")
            for val, cnt in junk_counts.items():
                print(f"{val} : {cnt}")
    
    # NEW PART: show columns list
    if columns_with_junk:
        print(f"\nColumns containing {category}: {columns_with_junk}")

# Total junk count per column
total_junk_counts = junk_mask.sum()
total_junk_counts = total_junk_counts[total_junk_counts > 0]

print("\n===== TOTAL JUNK COUNT PER COLUMN =====")
print(total_junk_counts)

===== DETAILED JUNK VALUE REPORT =====

=== Numeric 0 ===

=== String '0' ===

=== Hyphen '-' ===

=== Symbols ===

=== Question marks ===

=== Punctuation ===

=== Dots / Slash ===

=== Unknown text ===

=== NA values ===

=== Other ===

===== TOTAL JUNK COUNT PER COLUMN =====
Series([], dtype: Int64)

## Replacing the '--' with null from column 'remodeled'

In [35]:
df['remodeled'] = df['remodeled'].replace('--',np.nan)
df['remodeled']

0                            2007
1                             NaN
2                             NaN
3                             NaN
4                            2007
                    ...
4988247    Apartment - Tax Credit
4988248    Apartment - Tax Credit
4988249    Apartment - Tax Credit
4988250    Apartment - Tax Credit
4988251    Apartment - Tax Credit
Name: remodeled, Length: 4988252, dtype: object

## Replacing the 'Unknown' value with null from column 'heating_type'

In [34]:
df['heating_type'] = df['heating_type'].replace('Unknown',np.nan)
df['heating_type']

0          Hot Air
1          Hot Air
2          Hot Air
3          Hot Air
4          Hot Air
            ...
4988247    Hot Air
4988248    Hot Air
4988249    Hot Air
4988250    Hot Air
4988251    Hot Air
Name: heating_type, Length: 4988252, dtype: object

In [30]:
df

,parcel_number,leed_certification_level,open_frame_porch_pri,elev_hydro_pass,basement,fireplace_open_1,unfin_basement_lwr,util_bldg_frm_c,frame_overhang_upr,one_story_mas_lwr,living_area_lwr,garage_interior_parking_apartments_c,parking_spaces,store_front_metal,unfin_l_a_upper,mobile_home_8_11_width,economic_obsolescence,cnpy_roof_ss_ave_c,mobile_home_30_width,base_value_small_tank,canopy_lwr,garage_att_frm_c,cost_and_design,unfin_l_a_primary,attic_finished,cond_desir_util,masonry_terrace_pri,bank_canopy_c,basement_top,one_story_frame_upr,enclosed_entry_c,masonry_bay_pri,encl_frame_porch_upr,cnpy_roof_ss_eco_c,comm_condo_neighborhood,fireplace_masonry_firebrick,basement_c,mas_brk_garage_pri,mobile_home_12_14_width,oh_door_motor_rs,quality,mas_conc_patio_pri,fireplace_direct_vent,bank_drive_thru,canopy_pri,frame_garage_pri,dock_level_floor_c,mobile_home_15_19_width,fireplace_adl_open,room_rec,cnpy_roof_ss_gd_c,interior_finish_percent,one_story_frame_pri,medical_beds,heating_ac,energy_star_certification,year,exterior_wall,base_area_lwr,masonry_bay_upr,room_full_bath,store_front_wood,util_bldg_mtl_c,masonry_overhang_upr,oh_door_motor_w_m,plumbing_type,base_area_upr,oh_door_roll_steel,mobile_home_20_29_width,atrium,open_mas_porch_upr,heating_type,masonry_overhang_pri,miscellaneous,one_story_mas_upr,office_warehouse_ratio,wood_deck_lwr,elevator_stops,open_mas_porch_pri,elev_elect_pass,style,mas_conc_patio_lwr,construction_type,carport_c,base_value_large_tank,sprinkler_type,porch_enclosed_c,building_number,stone_tile_patio_upper,area_hirise_ofc_c,mas_brk_garage_lwr,encl_frame_porch_pri,year_built,masonry_trim,encl_mas_porch_pri,base_area_pri,impr_sq_ft,stone_tile_patio_pri,oh_door_wood_mtl,base_value_tiny_tank,market_adjustment,half_story_mas_upr,ldng_ramp_conc_c,frame_garage_lwr,carport_lwr,truck_train_wells_c,open_mas_porch_lwr,apt_3_bedroom_unit,half_story_frame_upr,carport_pri,wood_deck_upr,cnpy_only_c,frame_overhang_pri,one_story_mas_pri,apt_effcncy_unit,sprinkler_wet,attic_unfinished,number_of_apartment_units,foundation_type,cnpy_roof_w_slab_c,craneway_5_ton,masnry_util_bldg_pri,partition_type,net_rentable_area,room_half_bath,wood_deck_pri,porch_open_c,parking_garage_c,type,frame_bay_pri,stories,cooling_type,apt_1_bedroom_unit,franchise_code,wall_height,apt_2_bedroom_unit,wall_height_enclosure,garage_att_mas_c,perimeter,room_total,elev_elect_frght,room_bedroom,building_details,frame_util_bldg_upr,fireplace_metal_prefab,open_frame_porch_lwr,escalator_48,remodeled,market_index_adjustment,frame_util_bldg_pri,porch_open_upr_c,frame_bay_upr,base_value_medium_tank,bank_vault_no_door,frame_util_bldg_lwr,elev_hydro_frght,functional_utility,grade_adjustment,physical_condition,open_frame_porch_upr,parking_garage_upper_level_c,page_save
0,1168130000001,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,Normal,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2021,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,Adequate,<NA>,NaN,NaN,<NA>,NaN,Hot Air,NaN,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,<NA>,NaN,NaN,1,NaN,NaN,NaN,NaN,1990,<NA>,NaN,13054,"13,054",NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,7000.0,<NA>,NaN,Normal,<NA>,<NA>,NaN,NaN,NaN,Strip Shopping Center,<NA>,NaN,Central / Forced,<NA>,<NA>,14.0,<NA>,NaN,NaN,NaN,<NA>,<NA>,<NA>,Displayed,NaN,<NA>,NaN,<NA>,2007,111% Market Index Adjustment,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,Avg/Normal,NaN,Avg/Normal,NaN,<NA>,1168130000001_2021.html
1,1168130000001,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,Normal,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2021,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,Adequate,<NA>,NaN,NaN,<NA>,NaN,Hot Air,NaN,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,<NA>,NaN,NaN,2,NaN,NaN,NaN,NaN,1990,<NA>,NaN,4958,"4,958",NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,4646.0,<NA>,NaN,Normal,<NA>,<NA>,NaN,NaN,NaN,Strip Shopping Center,<NA>,NaN,Central / Forced,<NA>,<NA>,14.0,<NA>,NaN,NaN,NaN,<NA>,<NA>,<NA>,View,NaN,<NA>,NaN,<NA>,NaN,111% Market Index Adjustment,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,Avg/Normal,NaN,Avg/Normal,NaN,<NA>,1168130000001_2021.html
2,1168130000001,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,Normal,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2021,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,Adequate,<NA>,NaN,NaN,<NA>,NaN,Hot Air,NaN,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,<NA>,NaN,NaN,6,NaN,NaN,NaN,NaN,1990,<NA>,NaN,11160,"11,160",NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,Normal,<NA>,<NA>,NaN,NaN,NaN,Strip Shopping Center,<NA>,NaN,Central / Forced,<NA>,<NA>,14.0,<NA>,NaN,NaN,NaN,<NA>,<NA>,<NA>,View,NaN,<NA>,NaN,<NA>,NaN,111% Market Index Adjustment,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,Avg/Normal,NaN,Avg/Normal,NaN,<NA>,1168130000001_2021.html
3,1168130000001,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,Normal,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,Adequate,<NA>,NaN,NaN,<NA>,NaN,Hot Air,NaN,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,<NA>,NaN,NaN,7,NaN,NaN,NaN,NaN,1990,<NA>,NaN,23030,"23,030",NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,Normal,<NA>,<NA>,NaN,NaN,NaN,Strip Shopping Center,<NA>,NaN,Central / Forced,<NA>,<NA>,0.0,<NA>,NaN,NaN,NaN,<NA>,<NA>,<NA>,View,NaN,<NA>,NaN,<NA>,NaN,111% Market Index Adjustment,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,Avg/Normal,NaN,Avg/Normal,NaN,<NA>,1168130000001_2021.html
4,1168130000001,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,Normal,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2022,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,Adequate,<NA>,NaN,NaN,<NA>,NaN,Hot Air,NaN,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,<NA>,NaN,NaN,1,NaN,NaN,NaN,NaN,1990,<NA>,NaN,13054,"13,054",NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,7000.0,<NA>,NaN,Normal,<NA>,<NA>,NaN,NaN,NaN,Strip Shopping Center,<NA>,NaN,Central / Forced,<NA>,<NA>,14.0,<NA>,NaN,NaN,NaN,<NA>,<NA>,<NA>,Displayed,NaN,<NA>,NaN,<NA>,2007,100% No Mkt Index Adjustment,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,Avg/Normal,NaN,Avg/Normal,NaN,<NA>,1168130000001_2022.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4988247,1321770010001,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,Normal,NaN,NaN,<NA>,NaN,991.0,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,"5,287",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2026,Frame / Stucco,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,Adequate,<NA>,NaN,NaN,<NA>,NaN,Hot Air,NaN,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,Average,NaN,NaN,NaN,<NA>,NaN,NaN,13,NaN,NaN,NaN,NaN,2010,<NA>,NaN,5287,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,Normal,<NA>,<NA>,NaN,137.0,NaN,8451 -- Multiple Res. (Sen. Citizen),<NA>,NaN,NaN,<NA>,<NA>,NaN,<NA>,9.0,NaN,NaN,<NA>,<NA>,<NA>,View,NaN,<NA>,NaN,<NA>,Apartment - Tax Credit,100% No Mkt Index Adjustment,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,Avg/Normal,NaN,Avg/Normal,NaN,<NA>,1321770010001_2026.html
4988248,1321770010001,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,Normal,NaN,NaN,<NA>,NaN,991.0,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,"5,287",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2026,Frame / Stucco,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,Adequate,<NA>,NaN,NaN,<NA>,NaN,Hot Air,NaN,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,Average,NaN,NaN,NaN,<NA>,NaN,NaN,14,NaN,NaN,NaN,NaN,2010,<NA>,NaN,5287,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,Normal,<NA>,<NA>,NaN,137.0,NaN,8451 -- Multiple Res. (Sen. Citizen),<NA>,NaN,Central / Forced,<NA>,<NA>,9.0,<NA>,NaN,NaN,NaN,<NA>,<NA>,<NA>,View,NaN,<NA>,NaN,<NA>,Apartment - Tax Credit,100% No Mkt Index Adjustment,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,Avg/Normal,NaN,Avg/Normal,NaN,<NA>,1321770010001_2026.html
4988249,1321770010001,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,Normal,NaN,NaN,<NA>,NaN,991.0,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,"5,287",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2026,Frame / Stucco,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,Adequate,<NA>,NaN,NaN,<NA>,NaN,Hot Air,NaN,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,Average,NaN,NaN,NaN,<NA>,NaN,NaN,15,NaN,NaN,NaN,NaN,2010,<NA>,NaN,5287,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,Normal,<NA>,<NA>,NaN,137.0,NaN,8451 -- Multiple Res. (Sen. Citizen),<NA>,NaN,Central / Forced,<NA>,<NA>,9.0,<NA>,NaN,NaN,NaN,<NA>,<NA>,<NA>,View,NaN,<NA>,NaN,<NA>,Apartment - Tax Credit,100% No Mkt Index Adjustment,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,Avg/Normal,NaN,Avg/Normal,NaN,<NA>,1321770010001_2026.html
4988250,1321770010001,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,Normal,NaN,NaN,<NA>,NaN,991.0,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,"5,287",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2026,Frame / Stucco,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,Adequate,<NA>,NaN,NaN,<NA>,NaN,Hot Air,NaN,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,Average,NaN,NaN,NaN,<NA>,NaN,NaN,16,NaN,NaN,NaN,NaN,2010,<NA>,NaN,5287,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,Normal,<NA>,<NA>,NaN,137.0,NaN,8451 -- Multiple Res. (Sen. Citizen),<NA>,NaN,Central / Forced,<NA>,<NA>,9.0,<NA>,NaN,NaN,NaN,<NA>,<NA>,<NA>,View,NaN,<NA>,NaN,<NA>,Apartment - Tax Credit,100% No Mkt Index Adjustment,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,Avg/Normal,NaN,Avg/Normal,NaN,<NA>,1321770010001_2026.html
4988251,1321770010001,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,Normal,NaN,NaN,<NA>,NaN,991.0,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,"5,287",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2026,Frame / Stucco,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,Adequate,<NA>,NaN,NaN,<NA>,NaN,Hot Air,NaN,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,Average,NaN,NaN,NaN,<NA>,NaN,NaN,17,NaN,NaN,NaN,NaN,2010,<NA>,NaN,5287,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,Normal,<NA>,<NA>,NaN,137.0,NaN,8451 -- Multiple Res. (Sen. Citizen),<NA>,NaN,Central / Forced,<NA>,<NA>,9.0,<NA>,NaN,NaN,NaN,<NA>,<NA>,<NA>,View,NaN,<NA>,NaN,<NA>,Apartment - Tax Credit,100% No Mkt Index Adjustment,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,Avg/Normal,NaN,Avg/Normal,NaN,<NA>,1321770010001_2026.html

In [32]:
df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4988252 entries, 0 to 4988251
Data columns (total 162 columns):
 #    Column                                Non-Null Count    Dtype
---   ------                                --------------    -----
 0    parcel_number                         4988252 non-null  int64
 1    leed_certification_level              541 non-null      object
 2    open_frame_porch_pri                  2615132 non-null  float64
 3    elev_hydro_pass                       3790 non-null     Int64
 4    basement                              1454 non-null     float64
 5    fireplace_open_1                      697 non-null      Int64
 6    unfin_basement_lwr                    579 non-null      float64
 7    util_bldg_frm_c                       8731 non-null     float64
 8    frame_overhang_upr                    118276 non-null   float64
 9    one_story_mas_lwr                     956 non-null      float64
 10   living_area_lwr                       1271 non-null     float64
 11   garage_interior_parking_apartments_c  4456 non-null     float64
 12   parking_spaces                        1025 non-null     float64
 13   store_front_metal                     20503 non-null    Int64
 14   unfin_l_a_upper                       2572 non-null     float64
 15   mobile_home_8_11_width                2367 non-null     float64
 16   economic_obsolescence                 491169 non-null   object
 17   cnpy_roof_ss_ave_c                    1891 non-null     float64
 18   mobile_home_30_width                  2639 non-null     float64
 19   base_value_small_tank                 3978 non-null     Int64
 20   canopy_lwr                            16114 non-null    float64
 21   garage_att_frm_c                      4667 non-null     float64
 22   cost_and_design                       1153901 non-null  object
 23   unfin_l_a_primary                     526 non-null      float64
 24   attic_finished                        130021 non-null   float64
 25   cond_desir_util                       4472728 non-null  object
 26   masonry_terrace_pri                   27393 non-null    float64
 27   bank_canopy_c                         3578 non-null     float64
 28   basement_top                          62 non-null       Int64
 29   one_story_frame_upr                   407718 non-null   float64
 30   enclosed_entry_c                      1177 non-null     float64
 31   masonry_bay_pri                       37557 non-null    float64
 32   encl_frame_porch_upr                  1828 non-null     float64
 33   cnpy_roof_ss_eco_c                    678 non-null      float64
 34   comm_condo_neighborhood               6993 non-null     object
 35   fireplace_masonry_firebrick           892900 non-null   Int64
 36   basement_c                            539 non-null      float64
 37   mas_brk_garage_pri                    2101497 non-null  float64
 38   mobile_home_12_14_width               28882 non-null    float64
 39   oh_door_motor_rs                      916 non-null      float64
 40   quality                               4988252 non-null  object
 41   mas_conc_patio_pri                    593313 non-null   float64
 42   fireplace_direct_vent                 108980 non-null   float64
 43   bank_drive_thru                       1355 non-null     float64
 44   canopy_pri                            153376 non-null   float64
 45   frame_garage_pri                      496304 non-null   float64
 46   dock_level_floor_c                    174 non-null      float64
 47   mobile_home_15_19_width               12042 non-null    float64
 48   fireplace_adl_open                    18317 non-null    float64
 49   room_rec                              1587644 non-null  float64
 50   cnpy_roof_ss_gd_c                     2065 non-null     float64
 51   interior_finish_percent               464550 non-null   float64
 52   one_story_frame_pri                   535971 non-null   float64
 53   medical_beds                          486 non-null      float64
 54   heating_ac                            4131626 non-null  object
 55   energy_star_certification             832 non-null      object
 56   year                                  4988252 non-null  int64
 57   exterior_wall                         4959775 non-null  object
 58   base_area_lwr                         76432 non-null    float64
 59   masonry_bay_upr                       1400 non-null     float64
 60   room_full_bath                        4472412 non-null  float64
 61   store_front_wood                      1465 non-null     float64
 62   util_bldg_mtl_c                       2870 non-null     float64
 63   masonry_overhang_upr                  4238 non-null     float64
 64   oh_door_motor_w_m                     1384 non-null     Int64
 65   plumbing_type                         440921 non-null   object
 66   base_area_upr                         1684872 non-null  Int64
 67   oh_door_roll_steel                    31230 non-null    float64
 68   mobile_home_20_29_width               15395 non-null    float64
 69   atrium                                6445 non-null     Int64
 70   open_mas_porch_upr                    31134 non-null    float64
 71   heating_type                          333887 non-null   object
 72   masonry_overhang_pri                  1200 non-null     float64
 73   miscellaneous                         540 non-null      Int64
 74   one_story_mas_upr                     115162 non-null   float64
 75   office_warehouse_ratio                60613 non-null    float64
 76   wood_deck_lwr                         1472 non-null     float64
 77   elevator_stops                        17409 non-null    Int64
 78   open_mas_porch_pri                    1474209 non-null  float64
 79   elev_elect_pass                       9804 non-null     float64
 80   style                                 4988252 non-null  object
 81   mas_conc_patio_lwr                    4209 non-null     float64
 82   construction_type                     24267 non-null    object
 83   carport_c                             4802 non-null     float64
 84   base_value_large_tank                 701 non-null      Int64
 85   sprinkler_type                        43403 non-null    object
 86   porch_enclosed_c                      3534 non-null     float64
 87   building_number                       4988252 non-null  int64
 88   stone_tile_patio_upper                4508 non-null     float64
 89   area_hirise_ofc_c                     64 non-null       float64
 90   mas_brk_garage_lwr                    24574 non-null    float64
 91   encl_frame_porch_pri                  121662 non-null   float64
 92   year_built                            4988252 non-null  int64
 93   masonry_trim                          128032 non-null   Int64
 94   encl_mas_porch_pri                    9256 non-null     float64
 95   base_area_pri                         4920170 non-null  Int64
 96   impr_sq_ft                            4733883 non-null  object
 97   stone_tile_patio_pri                  33688 non-null    float64
 98   oh_door_wood_mtl                      107258 non-null   float64
 99   base_value_tiny_tank                  7687 non-null     Int64
 100  market_adjustment                     87495 non-null    object
 101  half_story_mas_upr                    2047 non-null     float64
 102  ldng_ramp_conc_c                      1705 non-null     float64
 103  frame_garage_lwr                      77382 non-null    float64
 104  carport_lwr                           5086 non-null     float64
 105  truck_train_wells_c                   3899 non-null     float64
 106  open_mas_porch_lwr                    11738 non-null    float64
 107  apt_3_bedroom_unit                    8717 non-null     Int64
 108  half_story_frame_upr                  7326 non-null     float64
 109  carport_pri                           189321 non-null   float64
 110  wood_deck_upr                         29703 non-null    float64
 111  cnpy_only_c                           26752 non-null    float64
 112  frame_overhang_pri                    8110 non-null     float64
 113  one_story_mas_pri                     677420 non-null   float64
 114  apt_effcncy_unit                      2782 non-null     Int64
 115  sprinkler_wet                         2461 non-null     Int64
 116  attic_unfinished                      24263 non-null    float64
 117  number_of_apartment_units             1684 non-null     Int64
 118  foundation_type                       4472730 non-null  object
 119  cnpy_roof_w_slab_c                    117468 non-null   float64
 120  craneway_5_ton                        654 non-null      Int64
 121  masnry_util_bldg_pri                  10992 non-null    float64
 122  partition_type                        446997 non-null   object
 123  net_rentable_area                     1068 non-null     Int64
 124  room_half_bath                        1761052 non-null  Int64
 125  wood_deck_pri                         160941 non-null   float64
 126  porch_open_c                          110041 non-null   float64
 127  parking_garage_c                      1612 non-null     float64
 128  type                                  4988252 non-null  object
 129  frame_bay_pri                         15464 non-null    Int64
 130  stories                               44838 non-null    float64
 131  cooling_type                          311928 non-null   object
 132  apt_1_bedroom_unit                    34940 non-null    Int64
 133  franchise_code                        10080 non-null    Int64
 134  wall_height                           345669 non-null   float64
 135  apt_2_bedroom_unit                    36675 non-null    Int64
 136  wall_height_enclosure                 148762 non-null   float64
 137  garage_att_mas_c                      1024 non-null     float64
 138  perimeter                             566 non-null      float64
 139  room_total                            4472521 non-null  Int64
 140  elev_elect_frght                      3925 non-null     Int64
 141  room_bedroom                          4472840 non-null  Int64
 142  building_details                      4985587 non-null  object
 143  frame_util_bldg_upr                   2094 non-null     float64
 144  fireplace_metal_prefab                1478397 non-null  Int64
 145  open_frame_porch_lwr                  34349 non-null    float64
 146  escalator_48                          203 non-null      Int64
 147  remodeled                             4988234 non-null  object
 148  market_index_adjustment               470798 non-null   object
 149  frame_util_bldg_pri                   74298 non-null    float64
 150  porch_open_upr_c                      89188 non-null    float64
 151  frame_bay_upr                         2135 non-null     Int64
 152  base_value_medium_tank                6236 non-null     Int64
 153  bank_vault_no_door                    662 non-null      Int64
 154  frame_util_bldg_lwr                   4171 non-null     float64
 155  elev_hydro_frght                      658 non-null      Int64
 156  functional_utility                    489806 non-null   object
 157  grade_adjustment                      4474587 non-null  object
 158  physical_condition                    4964694 non-null  object
 159  open_frame_porch_upr                  116118 non-null   float64
 160  parking_garage_upper_level_c          1315 non-null     Int64
 161  page_save                             4988252 non-null  object
dtypes: Int64(36), float64(95), int64(4), object(27)
memory usage: 6.2+ GB

In [33]:
df['grade_adjustment'].value_counts()

grade_adjustment
C                       1523494
C+                       894554
B-                       414362
B                        373858
C-                       320195
D                        218114
B+                       213689
D+                       127636
A-                       100352
A                         92884
A+                        66472
D-                        61438
X-                        24154
X                         15598
E                         13002
E+                         7549
X+                         3733
E-                         1717
90% Comm. Grade Adj         463
95% Comm. Grade Adj         296
75% Comm. Grade Adj         207
80% Comm. Grade Adj         204
85% Comm. Grade Adj         184
125% Comm. Grade Adj        122
105% Comm. Grade Adj         95
115% Comm. Grade Adj         87
110% Comm. Grade Adj         68
140% Comm. Grade Adj         18
120% Comm. Grade Adj         14
145% Comm. Grade Adj          9
160% Comm. Grade Adj          6
150% Comm. Grade Adj          6
130% Comm. Grade Adj          6
70% Comm. Grade Adj           1
Name: count, dtype: int64

In [45]:
df.duplicated().sum()

np.int64(0)

In [46]:
df

,parcel_number,leed_certification_level,open_frame_porch_pri,elev_hydro_pass,basement,fireplace_open_1,unfin_basement_lwr,util_bldg_frm_c,frame_overhang_upr,one_story_mas_lwr,living_area_lwr,garage_interior_parking_apartments_c,parking_spaces,store_front_metal,unfin_l_a_upper,mobile_home_8_11_width,economic_obsolescence,cnpy_roof_ss_ave_c,mobile_home_30_width,base_value_small_tank,canopy_lwr,garage_att_frm_c,cost_and_design,unfin_l_a_primary,attic_finished,cond_desir_util,masonry_terrace_pri,bank_canopy_c,basement_top,one_story_frame_upr,enclosed_entry_c,masonry_bay_pri,encl_frame_porch_upr,cnpy_roof_ss_eco_c,comm_condo_neighborhood,fireplace_masonry_firebrick,basement_c,mas_brk_garage_pri,mobile_home_12_14_width,oh_door_motor_rs,quality,mas_conc_patio_pri,fireplace_direct_vent,bank_drive_thru,canopy_pri,frame_garage_pri,dock_level_floor_c,mobile_home_15_19_width,fireplace_adl_open,room_rec,cnpy_roof_ss_gd_c,interior_finish_percent,one_story_frame_pri,medical_beds,heating_ac,energy_star_certification,year,exterior_wall,base_area_lwr,masonry_bay_upr,room_full_bath,store_front_wood,util_bldg_mtl_c,masonry_overhang_upr,oh_door_motor_w_m,plumbing_type,base_area_upr,oh_door_roll_steel,mobile_home_20_29_width,atrium,open_mas_porch_upr,heating_type,masonry_overhang_pri,miscellaneous,one_story_mas_upr,office_warehouse_ratio,wood_deck_lwr,elevator_stops,open_mas_porch_pri,elev_elect_pass,style,mas_conc_patio_lwr,construction_type,carport_c,base_value_large_tank,sprinkler_type,porch_enclosed_c,building_number,stone_tile_patio_upper,area_hirise_ofc_c,mas_brk_garage_lwr,encl_frame_porch_pri,year_built,masonry_trim,encl_mas_porch_pri,base_area_pri,impr_sq_ft,stone_tile_patio_pri,oh_door_wood_mtl,base_value_tiny_tank,market_adjustment,half_story_mas_upr,ldng_ramp_conc_c,frame_garage_lwr,carport_lwr,truck_train_wells_c,open_mas_porch_lwr,apt_3_bedroom_unit,half_story_frame_upr,carport_pri,wood_deck_upr,cnpy_only_c,frame_overhang_pri,one_story_mas_pri,apt_effcncy_unit,sprinkler_wet,attic_unfinished,number_of_apartment_units,foundation_type,cnpy_roof_w_slab_c,craneway_5_ton,masnry_util_bldg_pri,partition_type,net_rentable_area,room_half_bath,wood_deck_pri,porch_open_c,parking_garage_c,type,frame_bay_pri,stories,cooling_type,apt_1_bedroom_unit,franchise_code,wall_height,apt_2_bedroom_unit,wall_height_enclosure,garage_att_mas_c,perimeter,room_total,elev_elect_frght,room_bedroom,building_details,frame_util_bldg_upr,fireplace_metal_prefab,open_frame_porch_lwr,escalator_48,remodeled,market_index_adjustment,frame_util_bldg_pri,porch_open_upr_c,frame_bay_upr,base_value_medium_tank,bank_vault_no_door,frame_util_bldg_lwr,elev_hydro_frght,functional_utility,grade_adjustment,physical_condition,open_frame_porch_upr,parking_garage_upper_level_c,page_save
0,1168130000001,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,Normal,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2021,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,Adequate,<NA>,NaN,NaN,<NA>,NaN,Hot Air,NaN,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,<NA>,NaN,NaN,1,NaN,NaN,NaN,NaN,1990.0,<NA>,NaN,13054,13054,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,7000.0,<NA>,NaN,Normal,<NA>,<NA>,NaN,NaN,NaN,Strip Shopping Center,<NA>,NaN,Central / Forced,<NA>,<NA>,14.0,<NA>,NaN,NaN,NaN,<NA>,<NA>,<NA>,Displayed,NaN,<NA>,NaN,<NA>,2007,111% Market Index Adjustment,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,Avg/Normal,NaN,Avg/Normal,NaN,<NA>,1168130000001_2021.html
1,1168130000001,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,Normal,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2021,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,Adequate,<NA>,NaN,NaN,<NA>,NaN,Hot Air,NaN,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,<NA>,NaN,NaN,2,NaN,NaN,NaN,NaN,1990.0,<NA>,NaN,4958,4958,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,4646.0,<NA>,NaN,Normal,<NA>,<NA>,NaN,NaN,NaN,Strip Shopping Center,<NA>,NaN,Central / Forced,<NA>,<NA>,14.0,<NA>,NaN,NaN,NaN,<NA>,<NA>,<NA>,View,NaN,<NA>,NaN,<NA>,NaN,111% Market Index Adjustment,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,Avg/Normal,NaN,Avg/Normal,NaN,<NA>,1168130000001_2021.html
2,1168130000001,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,Normal,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2021,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,Adequate,<NA>,NaN,NaN,<NA>,NaN,Hot Air,NaN,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,<NA>,NaN,NaN,6,NaN,NaN,NaN,NaN,1990.0,<NA>,NaN,11160,11160,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,Normal,<NA>,<NA>,NaN,NaN,NaN,Strip Shopping Center,<NA>,NaN,Central / Forced,<NA>,<NA>,14.0,<NA>,NaN,NaN,NaN,<NA>,<NA>,<NA>,View,NaN,<NA>,NaN,<NA>,NaN,111% Market Index Adjustment,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,Avg/Normal,NaN,Avg/Normal,NaN,<NA>,1168130000001_2021.html
3,1168130000001,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,Normal,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,Adequate,<NA>,NaN,NaN,<NA>,NaN,Hot Air,NaN,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,<NA>,NaN,NaN,7,NaN,NaN,NaN,NaN,1990.0,<NA>,NaN,23030,23030,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,Normal,<NA>,<NA>,NaN,NaN,NaN,Strip Shopping Center,<NA>,NaN,Central / Forced,<NA>,<NA>,NaN,<NA>,NaN,NaN,NaN,<NA>,<NA>,<NA>,View,NaN,<NA>,NaN,<NA>,NaN,111% Market Index Adjustment,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,Avg/Normal,NaN,Avg/Normal,NaN,<NA>,1168130000001_2021.html
4,1168130000001,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,Normal,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2022,Concr Tilt Up,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,Adequate,<NA>,NaN,NaN,<NA>,NaN,Hot Air,NaN,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,8412 -- Neighborhood Shopping Ctr,NaN,NaN,NaN,<NA>,NaN,NaN,1,NaN,NaN,NaN,NaN,1990.0,<NA>,NaN,13054,13054,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,7000.0,<NA>,NaN,Normal,<NA>,<NA>,NaN,NaN,NaN,Strip Shopping Center,<NA>,NaN,Central / Forced,<NA>,<NA>,14.0,<NA>,NaN,NaN,NaN,<NA>,<NA>,<NA>,Displayed,NaN,<NA>,NaN,<NA>,2007,100% No Mkt Index Adjustment,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,Avg/Normal,NaN,Avg/Normal,NaN,<NA>,1168130000001_2022.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4988247,1321770010001,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,Normal,NaN,NaN,<NA>,NaN,991.0,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,"5,287",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2026,Frame / Stucco,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,Adequate,<NA>,NaN,NaN,<NA>,NaN,Hot Air,NaN,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,Average,NaN,NaN,NaN,<NA>,NaN,NaN,13,NaN,NaN,NaN,NaN,2010.0,<NA>,NaN,5287,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,Normal,<NA>,<NA>,NaN,137.0,NaN,8451 -- Multiple Res. (Sen. Citizen),<NA>,NaN,NaN,<NA>,<NA>,NaN,<NA>,9.0,NaN,NaN,<NA>,<NA>,<NA>,View,NaN,<NA>,NaN,<NA>,Apartment - Tax Credit,100% No Mkt Index Adjustment,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,Avg/Normal,NaN,Avg/Normal,NaN,<NA>,1321770010001_2026.html
4988248,1321770010001,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,Normal,NaN,NaN,<NA>,NaN,991.0,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,"5,287",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2026,Frame / Stucco,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,Adequate,<NA>,NaN,NaN,<NA>,NaN,Hot Air,NaN,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,Average,NaN,NaN,NaN,<NA>,NaN,NaN,14,NaN,NaN,NaN,NaN,2010.0,<NA>,NaN,5287,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,Normal,<NA>,<NA>,NaN,137.0,NaN,8451 -- Multiple Res. (Sen. Citizen),<NA>,NaN,Central / Forced,<NA>,<NA>,9.0,<NA>,NaN,NaN,NaN,<NA>,<NA>,<NA>,View,NaN,<NA>,NaN,<NA>,Apartment - Tax Credit,100% No Mkt Index Adjustment,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,Avg/Normal,NaN,Avg/Normal,NaN,<NA>,1321770010001_2026.html
4988249,1321770010001,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,Normal,NaN,NaN,<NA>,NaN,991.0,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,"5,287",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2026,Frame / Stucco,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,Adequate,<NA>,NaN,NaN,<NA>,NaN,Hot Air,NaN,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,Average,NaN,NaN,NaN,<NA>,NaN,NaN,15,NaN,NaN,NaN,NaN,2010.0,<NA>,NaN,5287,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,Normal,<NA>,<NA>,NaN,137.0,NaN,8451 -- Multiple Res. (Sen. Citizen),<NA>,NaN,Central / Forced,<NA>,<NA>,9.0,<NA>,NaN,NaN,NaN,<NA>,<NA>,<NA>,View,NaN,<NA>,NaN,<NA>,Apartment - Tax Credit,100% No Mkt Index Adjustment,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,Avg/Normal,NaN,Avg/Normal,NaN,<NA>,1321770010001_2026.html
4988250,1321770010001,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,Normal,NaN,NaN,<NA>,NaN,991.0,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,"5,287",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2026,Frame / Stucco,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,Adequate,<NA>,NaN,NaN,<NA>,NaN,Hot Air,NaN,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,Average,NaN,NaN,NaN,<NA>,NaN,NaN,16,NaN,NaN,NaN,NaN,2010.0,<NA>,NaN,5287,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,Normal,<NA>,<NA>,NaN,137.0,NaN,8451 -- Multiple Res. (Sen. Citizen),<NA>,NaN,Central / Forced,<NA>,<NA>,9.0,<NA>,NaN,NaN,NaN,<NA>,<NA>,<NA>,View,NaN,<NA>,NaN,<NA>,Apartment - Tax Credit,100% No Mkt Index Adjustment,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,Avg/Normal,NaN,Avg/Normal,NaN,<NA>,1321770010001_2026.html
4988251,1321770010001,NaN,NaN,<NA>,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,Normal,NaN,NaN,<NA>,NaN,991.0,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,"5,287",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,2026,Frame / Stucco,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,Adequate,<NA>,NaN,NaN,<NA>,NaN,Hot Air,NaN,<NA>,NaN,NaN,NaN,<NA>,NaN,NaN,Average,NaN,NaN,NaN,<NA>,NaN,NaN,17,NaN,NaN,NaN,NaN,2010.0,<NA>,NaN,5287,<NA>,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,<NA>,NaN,NaN,<NA>,NaN,Normal,<NA>,<NA>,NaN,137.0,NaN,8451 -- Multiple Res. (Sen. Citizen),<NA>,NaN,Central / Forced,<NA>,<NA>,9.0,<NA>,NaN,NaN,NaN,<NA>,<NA>,<NA>,View,NaN,<NA>,NaN,<NA>,Apartment - Tax Credit,100% No Mkt Index Adjustment,NaN,NaN,<NA>,<NA>,<NA>,NaN,<NA>,Avg/Normal,NaN,Avg/Normal,NaN,<NA>,1321770010001_2026.html

## Placing the file

In [47]:
df.to_csv(r"D:\Khushi\[XB3421] Data Extraction For USA Counties_Virec\us\texas\harris\prop\Cleaned_Data\us_tx_48201_data_prop_building-summary_silver_20260501.csv",index=False)