In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv(r"D:\Khushi\[XB3421] Data Extraction For USA Counties_Virec\us\texas\harris\prop\Raw_Data\us_tx_48201_data_prop_building-summary_bronze_20260501.csv",dtype={'parcel_number':str})
df

C:\Users\khushi.limbachiya\AppData\Local\Temp\ipykernel_14440\7116822.py:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"D:\Khushi\[XB3421] Data Extraction For USA Counties_Virec\us\texas\harris\prop\Raw_Data\us_tx_48201_data_prop_building-summary_bronze_20260501.csv",dtype={'parcel_number':str})

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
0,0010020000016,Restaurant,1,1900,"22,608",Displayed,2021,Low,8350 -- Restaurant,NaN,1,0010020000016_2021.html
1,0010020000016,Bar/Lounge,1,1900,"22,608",Displayed,2022,Average,8441 -- Cocktail Lounge,2021,1,0010020000016_2022.html
2,0010020000016,Bar/Lounge,1,1900,"22,608",Displayed,2023,Average,8441 -- Cocktail Lounge,2021,1,0010020000016_2023.html
3,0010020000016,Bar/Lounge,1,1900,"22,608",Displayed,2024,Average,8441 -- Cocktail Lounge,2021,1,0010020000016_2024.html
4,0010020000016,Bar/Lounge,1,1900,"22,608",Displayed,2025,Average,8441 -- Cocktail Lounge,2021,1,0010020000016_2025.html
...,...,...,...,...,...,...,...,...,...,...,...,...
8330634,1955020050280,Residential Single Family,1,1979,"1,374 *",Displayed,2022,Average,101 -- Residential 1 Family,NaN,1,1955020050280_2022.html
8330635,1955020050280,Residential Single Family,1,1979,"1,374 *",Displayed,2023,Average,101 -- Residential 1 Family,NaN,1,1955020050280_2023.html
8330636,1955020050280,Residential Single Family,1,1979,"1,374 *",Displayed,2024,Average,101 -- Residential 1 Family,NaN,1,1955020050280_2024.html
8330637,1955020050280,Residential Single Family,1,1979,"1,374 *",Displayed,2025,Average,101 -- Residential 1 Family,NaN,1,1955020050280_2025.html
8330638,1955020050280,Residential Single Family,1,1979,"1,374 *",Displayed,2026,Average,101 -- Residential 1 Family,NaN,1,1955020050280_2026.html

In [ ]:
df['parcel_number'].nunique()

1311905

In [ ]:
df[df['parcel_number']=='1163150010037']

Empty DataFrame
Columns: [parcel_number, type, building, year_built, impr_sq_ft, building_details, year, quality, style, remodeled, building_number, page_save]
Index: []

In [ ]:
df[df['parcel_number']=='1249340020004']

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
386069,1249340020004,Residential Single Family,1,2006,"3,182 *",Displayed,2021,Good,101 -- Residential 1 Family,NaN,1,1249340020004_2021.html
386070,1249340020004,Residential Single Family,1,2006,"3,182 *",Displayed,2022,Good,101 -- Residential 1 Family,NaN,1,1249340020004_2022.html
386071,1249340020004,Residential Single Family,1,2006,"3,182 *",Displayed,2023,Good,101 -- Residential 1 Family,NaN,1,1249340020004_2023.html
386072,1249340020004,Residential Single Family,1,2006,"3,182 *",Displayed,2024,Good,101 -- Residential 1 Family,NaN,1,1249340020004_2024.html
386073,1249340020004,Residential Single Family,1,2006,"3,182 *",Displayed,2025,Good,101 -- Residential 1 Family,NaN,1,1249340020004_2025.html
386074,1249340020004,Residential Single Family,1,2006,"3,182 *",Displayed,2026,Good,101 -- Residential 1 Family,NaN,1,1249340020004_2026.html

In [ ]:
df[df['parcel_number']=='1295860010001']

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
3745832,1295860010001,Industrial Manufacturing,1,1955,"48,767",Displayed,2021,Average,"9494 -- Industrial, Light Mftg.",--,1,1295860010001_2021.html
3745833,1295860010001,Industrial Warehouse- Light Metallic,2,1956,"1,500",NaN,2021,Average,9471 -- Utility Building,--,2,1295860010001_2021.html
3745834,1295860010001,Industrial Warehouse- Light Metallic,3,1974,"3,600",NaN,2021,Average,9406 -- Industrial Warehouse,--,3,1295860010001_2021.html
3745835,1295860010001,Industrial Manufacturing,4,1973,"16,400",NaN,2021,Average,"9494 -- Industrial, Light Mftg.",2005,4,1295860010001_2021.html
3745836,1295860010001,Industrial Manufacturing,6,1982,"15,384",NaN,2021,Average,9344 -- Office Building,--,5,1295860010001_2021.html
...,...,...,...,...,...,...,...,...,...,...,...,...
3745911,1295860010001,Industrial Warehouse- Light Metallic,11,1947,550,NaN,2026,Average,9406 -- Industrial Warehouse,--,10,1295860010001_2026.html
3745912,1295860010001,Industrial Warehouse - Heavy - Non Metallic,13,2019,"8,294",NaN,2026,Low,9406 -- Industrial Warehouse,--,11,1295860010001_2026.html
3745913,1295860010001,Industrial Warehouse - Heavy - Non Metallic,15,2019,"1,800",NaN,2026,Average,9406 -- Industrial Warehouse,--,12,1295860010001_2026.html
3745914,1295860010001,Industrial Warehouse- Light Metallic,16,2019,"1,800",NaN,2026,Average,9406 -- Industrial Warehouse,--,13,1295860010001_2026.html
3745915,1295860010001,Storage Tank - Tiny,17,1999,64,NaN,2026,Poor,9781 -- Storage Tank - Tiny,--,14,1295860010001_2026.html

In [ ]:
df['parcel_number'].nunique()

1311905

In [ ]:
df[df['parcel_number']=='0471690000066']

Empty DataFrame
Columns: [parcel_number, type, building, year_built, impr_sq_ft, building_details, year, quality, style, remodeled, building_number, page_save]
Index: []

In [ ]:
df[df['parcel_number']=='471690000066']

Empty DataFrame
Columns: [parcel_number, type, building, year_built, impr_sq_ft, building_details, year, quality, style, remodeled, building_number, page_save]
Index: []

In [ ]:
df[df['parcel_number']=='0430980000057']

Empty DataFrame
Columns: [parcel_number, type, building, year_built, impr_sq_ft, building_details, year, quality, style, remodeled, building_number, page_save]
Index: []

In [ ]:
df[df['parcel_number']=='1152740150003']

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
5523621,1152740150003,Residential Condo,1,1982,531 *,Displayed,2021,Average,106 -- Condominium (Common Element),NaN,1,1152740150003_2021.html
5523622,1152740150003,Residential Condo,1,1982,531 *,Displayed,2022,Average,106 -- Condominium (Common Element),NaN,1,1152740150003_2022.html
5523623,1152740150003,Residential Condo,1,1982,531 *,Displayed,2023,Average,106 -- Condominium (Common Element),NaN,1,1152740150003_2023.html
5523624,1152740150003,Residential Condo,1,1982,531 *,Displayed,2024,Average,106 -- Condominium (Common Element),NaN,1,1152740150003_2024.html
5523625,1152740150003,Residential Condo,1,1982,531 *,Displayed,2025,Average,106 -- Condominium (Common Element),NaN,1,1152740150003_2025.html
5523626,1152740150003,Residential Condo,1,1982,531 *,Displayed,2026,Average,106 -- Condominium (Common Element),NaN,1,1152740150003_2026.html

In [ ]:
df[df['parcel_number']=='1128980000017']

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
5505158,1128980000017,Residential Single Family,1,1983,"1,570 *",Displayed,2021,Average,101 -- Residential 1 Family,NaN,1,1128980000017_2021.html
5505159,1128980000017,Residential Single Family,1,1983,"1,570 *",Displayed,2022,Average,101 -- Residential 1 Family,NaN,1,1128980000017_2022.html
5505160,1128980000017,Residential Single Family,1,1983,"1,570 *",Displayed,2023,Average,101 -- Residential 1 Family,NaN,1,1128980000017_2023.html
5505161,1128980000017,Residential Single Family,1,1983,"1,570 *",Displayed,2024,Average,101 -- Residential 1 Family,NaN,1,1128980000017_2024.html
5505162,1128980000017,Residential Single Family,1,1983,"1,570 *",Displayed,2025,Average,101 -- Residential 1 Family,NaN,1,1128980000017_2025.html
5505163,1128980000017,Residential Single Family,1,1983,"1,570 *",Displayed,2026,Average,101 -- Residential 1 Family,NaN,1,1128980000017_2026.html

In [ ]:
df[df['parcel_number']=='1135750000004']

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
5508222,1135750000004,Residential Single Family,1,1996,"1,788 *",Displayed,2021,Average,101 -- Residential 1 Family,NaN,1,1135750000004_2021.html
5508223,1135750000004,Residential Single Family,1,1996,"1,788 *",Displayed,2022,Average,101 -- Residential 1 Family,NaN,1,1135750000004_2022.html
5508224,1135750000004,Residential Single Family,1,1996,"1,788 *",Displayed,2023,Average,101 -- Residential 1 Family,NaN,1,1135750000004_2023.html
5508225,1135750000004,Residential Single Family,1,1996,"1,788 *",Displayed,2024,Average,101 -- Residential 1 Family,NaN,1,1135750000004_2024.html
5508226,1135750000004,Residential Single Family,1,1996,"1,788 *",Displayed,2025,Average,101 -- Residential 1 Family,NaN,1,1135750000004_2025.html
5508227,1135750000004,Residential Single Family,1,1996,"1,788 *",Displayed,2026,Average,101 -- Residential 1 Family,NaN,1,1135750000004_2026.html

In [ ]:
df[df['parcel_number']=='1030870010001']

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
8269786,1030870010001,Residential Single Family,1,2024,"7,057 *",Displayed,2025,Superior,101 -- Residential 1 Family,NaN,1,1030870010001_2025.html
8269787,1030870010001,Residential Single Family,1,2024,"7,750 *",Displayed,2026,Superior,101 -- Residential 1 Family,NaN,1,1030870010001_2026.html

In [ ]:
df[df['parcel_number']=='0141180380007']

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
8201823,0141180380007,Residential Single Family,1,2025,"1,620 *",Displayed,2026,Average,101 -- Residential 1 Family,NaN,1,0141180380007_2026.html
8201824,0141180380007,Residential Single Family,2,2025,"1,620 *",NaN,2026,Average,101 -- Residential 1 Family,NaN,2,0141180380007_2026.html

In [ ]:
df[df['parcel_number']=='1427460010009']

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
7390983,1427460010009,Residential Single Family,1,2025,"1,713 *",Displayed,2026,Average,101 -- Residential 1 Family,NaN,1,1427460010009_2026.html

In [ ]:
df[df['parcel_number']=='1471360030013']

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
7792926,1471360030013,Residential Single Family,1,2025,"2,810 *",Displayed,2026,Average,101 -- Residential 1 Family,NaN,1,1471360030013_2026.html

In [ ]:
df[df['parcel_number']=='1063340000002']

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
7220320,1063340000002,Residential Single Family,1,2021,"1,040 *",Displayed,2022,Average,101 -- Residential 1 Family,NaN,1,1063340000002_2022.html
7220321,1063340000002,Residential Single Family,1,2021,"1,040 *",Displayed,2023,Average,101 -- Residential 1 Family,NaN,1,1063340000002_2023.html
7220322,1063340000002,Residential Single Family,1,2021,"1,040 *",Displayed,2024,Average,101 -- Residential 1 Family,NaN,1,1063340000002_2024.html
7220323,1063340000002,Residential Single Family,1,2021,"1,040 *",Displayed,2025,Average,101 -- Residential 1 Family,NaN,1,1063340000002_2025.html
7220324,1063340000002,Residential Single Family,1,2021,"1,040 *",Displayed,2026,Average,101 -- Residential 1 Family,NaN,1,1063340000002_2026.html

In [ ]:
df[df['parcel_number']=='1000520000005']

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
7053312,1000520000005,Residential Single Family,1,2022,"2,330 *",Displayed,2023,Good,101 -- Residential 1 Family,NaN,1,1000520000005_2023.html
7053313,1000520000005,Residential Single Family,1,2022,"2,330 *",Displayed,2024,Good,101 -- Residential 1 Family,NaN,1,1000520000005_2024.html
7053314,1000520000005,Residential Single Family,1,2022,"2,330 *",Displayed,2025,Good,101 -- Residential 1 Family,NaN,1,1000520000005_2025.html
7053315,1000520000005,Residential Single Family,1,2022,"2,330 *",Displayed,2026,Good,101 -- Residential 1 Family,NaN,1,1000520000005_2026.html

In [ ]:
for col in df.columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=True))

--- parcel_number ---
parcel_number
0440990010029    1898
0440990010031    1398
0402650000004    1297
1005740000004    1262
0410290040161    1181
                 ...
1468550050023       1
1470990030014       1
1503800010001       1
1501290010001       1
1473050010001       1
Name: count, Length: 1311905, dtype: int64

--- type ---
type
Residential Single Family            6713370
Residential Condo                     380289
Apartment Garden (1 to 3 Stories)     196159
Warehouse - Metallic                  149549
Residential Townhome                  136116
                                      ...
Utility District, Other Operating          4
Auxiliary Improvement                      2
Utility District, Pumping                  2
Pipeline, Pumping Station                  2
Unsound Commercial Structure               1
Name: count, Length: 161, dtype: int64

--- building ---
building
1      7600832
2       299445
3        86849
4        48681
5        33111
        ...
324          6
327          2
326          2
328          2
310          1
Name: count, Length: 326, dtype: int64

--- year_built ---
year_built
1983    246168
2006    217396
1978    215356
2005    212842
1950    202570
         ...
1840         6
1873         5
1080         5
1100         2
1            1
Name: count, Length: 172, dtype: int64

--- impr_sq_ft ---
impr_sq_ft
1,440 *     14012
1,560 *     12997
960 *       12727
1,200 *     12669
1,520 *     12607
            ...
11,157 *        1
32,508          1
189,920         1
49,810          1
9,338 *         1
Name: count, Length: 39335, dtype: int64

--- building_details ---
building_details
Displayed    7630281
Name: count, dtype: int64

--- year ---
year
2026    1424144
2025    1417103
2024    1401987
2023    1381728
2022    1363207
2021    1342470
Name: count, dtype: int64

--- quality ---
quality
Average      5001295
Good         2021655
Low           695440
Excellent     488806
Superior       77721
Very Low       45501
Poor             214
Name: count, dtype: int64

--- style ---
style
101 -- Residential 1 Family              6714215
106 -- Condominium (Common Element)       380314
8352 -- Multiple Res (Low Rise)           237595
8454 -- Shell, Industrial                 184288
107 -- Townhome (with Common Element)     135377
                                          ...
8152 -- Residential Garage - Detached          4
8994 -- Int. Space, Industrial                 3
8495 -- Industrials, Heavy Mftg.               3
110 -- Unsound Residential Structure           2
0 -- None                                      1
Name: count, Length: 267, dtype: int64

--- remodeled ---
remodeled
2018      189347
2017      118961
--        110385
2019       97674
2015       81205
           ...
2921           2
1920           1
2099           1
3312           1
1980.0         1
Name: count, Length: 119, dtype: int64

--- building_number ---
building_number
1      7656239
2       271325
3        78063
4        44512
5        30900
        ...
314          6
315          6
316          3
317          3
318          2
Name: count, Length: 318, dtype: int64

--- page_save ---
page_save
0440990010029_2025.html    318
0440990010029_2026.html    318
0440990010029_2021.html    317
0440990010029_2023.html    315
0440990010029_2024.html    315
                          ...
1502530010001_2022.html      1
1502530010001_2023.html      1
1503800010001_2022.html      1
1953050320690_2021.html      1
0021260000005_2026.html      1
Name: count, Length: 7630546, dtype: int64

In [ ]:
df[df['parcel_number']=='1468550040006']

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
8330529,1468550040006,Residential Single Family,1,2025,"2,552 *",Displayed,2026,Average,101 -- Residential 1 Family,NaN,1,1468550040006_2026.html

In [ ]:
df[df['parcel_number']=='1501290010001']

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
8330617,1501290010001,Fast Food,1,2024,"2,046",Displayed,2025,Excellent,8349 -- Fast Food Restaurant,NaN,1,1501290010001_2025.html

In [ ]:
df[df['parcel_number']=='1000300000010']

Empty DataFrame
Columns: [parcel_number, type, building, year_built, impr_sq_ft, building_details, year, quality, style, remodeled, building_number, page_save]
Index: []

In [ ]:
df[df['parcel_number']=='1000970000022']

Empty DataFrame
Columns: [parcel_number, type, building, year_built, impr_sq_ft, building_details, year, quality, style, remodeled, building_number, page_save]
Index: []

In [ ]:
cols = df.columns.difference(['parcel_number', 'page_save'])
 
mask = df[cols].isna().all(axis=1)
df[mask]

Empty DataFrame
Columns: [parcel_number, type, building, year_built, impr_sq_ft, building_details, year, quality, style, remodeled, building_number, page_save]
Index: []

In [ ]:
cols = df.columns.difference(['parcel_number','year', 'page_save'])
 
mask = df[cols].isna().all(axis=1)
df[mask]

Empty DataFrame
Columns: [parcel_number, type, building, year_built, impr_sq_ft, building_details, year, quality, style, remodeled, building_number, page_save]
Index: []

In [ ]:
cols = df.columns.difference(['parcel_number','year','building_number','building', 'page_save'])
 
mask = df[cols].isna().all(axis=1)
df[mask]

Empty DataFrame
Columns: [parcel_number, type, building, year_built, impr_sq_ft, building_details, year, quality, style, remodeled, building_number, page_save]
Index: []

In [ ]:
cols = df.columns.difference(['parcel_number','building_number','building', 'page_save'])
 
mask = df[cols].isna().all(axis=1)
df[mask]

Empty DataFrame
Columns: [parcel_number, type, building, year_built, impr_sq_ft, building_details, year, quality, style, remodeled, building_number, page_save]
Index: []

In [ ]:
df[df['parcel_number']=='10020000013']

Empty DataFrame
Columns: [parcel_number, type, building, year_built, impr_sq_ft, building_details, year, quality, style, remodeled, building_number, page_save]
Index: []

In [ ]:
df[df['parcel_number']=='1168130000001']

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
353240,1168130000001,Strip Shopping Center,1,1990,"13,054",Displayed,2021,Good,8412 -- Neighborhood Shopping Ctr,2007,1,1168130000001_2021.html
353241,1168130000001,Strip Shopping Center,2,1990,"4,958",NaN,2021,Average,8412 -- Neighborhood Shopping Ctr,--,2,1168130000001_2021.html
353242,1168130000001,Strip Shopping Center,6,1990,"11,160",NaN,2021,Good,8412 -- Neighborhood Shopping Ctr,--,3,1168130000001_2021.html
353243,1168130000001,Strip Shopping Center,7,1990,"23,030",NaN,2021,Good,8412 -- Neighborhood Shopping Ctr,--,4,1168130000001_2021.html
353244,1168130000001,Strip Shopping Center,1,1990,"13,054",Displayed,2022,Good,8412 -- Neighborhood Shopping Ctr,2007,1,1168130000001_2022.html
353245,1168130000001,Strip Shopping Center,2,1990,"4,958",NaN,2022,Average,8412 -- Neighborhood Shopping Ctr,--,2,1168130000001_2022.html
353246,1168130000001,Strip Shopping Center,6,1990,"11,160",NaN,2022,Good,8412 -- Neighborhood Shopping Ctr,--,3,1168130000001_2022.html
353247,1168130000001,Strip Shopping Center,7,1990,"23,030",NaN,2022,Good,8412 -- Neighborhood Shopping Ctr,--,4,1168130000001_2022.html
353248,1168130000001,Strip Shopping Center,1,1990,"13,054",Displayed,2023,Good,8412 -- Neighborhood Shopping Ctr,2007,1,1168130000001_2023.html
353249,1168130000001,Strip Shopping Center,2,1990,"4,958",NaN,2023,Average,8412 -- Neighborhood Shopping Ctr,--,2,1168130000001_2023.html
353250,1168130000001,Strip Shopping Center,6,1990,"11,160",NaN,2023,Good,8412 -- Neighborhood Shopping Ctr,--,3,1168130000001_2023.html
353251,1168130000001,Strip Shopping Center,7,1990,"23,030",NaN,2023,Good,8412 -- Neighborhood Shopping Ctr,--,4,1168130000001_2023.html
353252,1168130000001,Strip Shopping Center,1,1990,"13,054",Displayed,2024,Good,8412 -- Neighborhood Shopping Ctr,2007,1,1168130000001_2024.html
353253,1168130000001,Strip Shopping Center,2,1990,"4,958",NaN,2024,Average,8412 -- Neighborhood Shopping Ctr,--,2,1168130000001_2024.html
353254,1168130000001,Strip Shopping Center,6,1990,"11,160",NaN,2024,Good,8412 -- Neighborhood Shopping Ctr,--,3,1168130000001_2024.html
353255,1168130000001,Strip Shopping Center,7,1990,"23,030",NaN,2024,Good,8412 -- Neighborhood Shopping Ctr,--,4,1168130000001_2024.html
353256,1168130000001,Strip Shopping Center,1,1990,"13,054",Displayed,2025,Good,8412 -- Neighborhood Shopping Ctr,2007,1,1168130000001_2025.html
353257,1168130000001,Strip Shopping Center,2,1990,"4,958",NaN,2025,Average,8412 -- Neighborhood Shopping Ctr,--,2,1168130000001_2025.html
353258,1168130000001,Strip Shopping Center,6,1990,"11,160",NaN,2025,Good,8412 -- Neighborhood Shopping Ctr,--,3,1168130000001_2025.html
353259,1168130000001,Strip Shopping Center,7,1990,"23,030",NaN,2025,Good,8412 -- Neighborhood Shopping Ctr,--,4,1168130000001_2025.html
353260,1168130000001,Strip Shopping Center,1,1990,"13,054",Displayed,2026,Good,8412 -- Neighborhood Shopping Ctr,2007,1,1168130000001_2026.html
353261,1168130000001,Strip Shopping Center,2,1990,"4,958",NaN,2026,Average,8412 -- Neighborhood Shopping Ctr,--,2,1168130000001_2026.html
353262,1168130000001,Strip Shopping Center,6,1990,"11,160",NaN,2026,Good,8412 -- Neighborhood Shopping Ctr,--,3,1168130000001_2026.html
353263,1168130000001,Strip Shopping Center,7,1990,"23,030",NaN,2026,Good,8412 -- Neighborhood Shopping Ctr,--,4,1168130000001_2026.html

In [ ]:
df[df['parcel_number']=='1065330270009']

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
7221726,1065330270009,Residential Single Family,1,2021,"2,434 *",Displayed,2022,Average,101 -- Residential 1 Family,NaN,1,1065330270009_2022.html
7221727,1065330270009,Residential Single Family,1,2021,"2,434 *",Displayed,2023,Average,101 -- Residential 1 Family,NaN,1,1065330270009_2023.html
7221728,1065330270009,Residential Single Family,1,2021,"2,434 *",Displayed,2024,Average,101 -- Residential 1 Family,NaN,1,1065330270009_2024.html
7221729,1065330270009,Residential Single Family,1,2021,"2,434 *",Displayed,2025,Average,101 -- Residential 1 Family,NaN,1,1065330270009_2025.html
7221730,1065330270009,Residential Single Family,1,2021,"2,434 *",Displayed,2026,Average,101 -- Residential 1 Family,NaN,1,1065330270009_2026.html

In [ ]:
df[(df['parcel_number']=='1168130000001') & (df['year']==2026)]

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
353260,1168130000001,Strip Shopping Center,1,1990,"13,054",Displayed,2026,Good,8412 -- Neighborhood Shopping Ctr,2007,1,1168130000001_2026.html
353261,1168130000001,Strip Shopping Center,2,1990,"4,958",NaN,2026,Average,8412 -- Neighborhood Shopping Ctr,--,2,1168130000001_2026.html
353262,1168130000001,Strip Shopping Center,6,1990,"11,160",NaN,2026,Good,8412 -- Neighborhood Shopping Ctr,--,3,1168130000001_2026.html
353263,1168130000001,Strip Shopping Center,7,1990,"23,030",NaN,2026,Good,8412 -- Neighborhood Shopping Ctr,--,4,1168130000001_2026.html

In [ ]:
df[df['parcel_number']=='1168130000001']

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
353240,1168130000001,Strip Shopping Center,1,1990,"13,054",Displayed,2021,Good,8412 -- Neighborhood Shopping Ctr,2007,1,1168130000001_2021.html
353241,1168130000001,Strip Shopping Center,2,1990,"4,958",NaN,2021,Average,8412 -- Neighborhood Shopping Ctr,--,2,1168130000001_2021.html
353242,1168130000001,Strip Shopping Center,6,1990,"11,160",NaN,2021,Good,8412 -- Neighborhood Shopping Ctr,--,3,1168130000001_2021.html
353243,1168130000001,Strip Shopping Center,7,1990,"23,030",NaN,2021,Good,8412 -- Neighborhood Shopping Ctr,--,4,1168130000001_2021.html
353244,1168130000001,Strip Shopping Center,1,1990,"13,054",Displayed,2022,Good,8412 -- Neighborhood Shopping Ctr,2007,1,1168130000001_2022.html
353245,1168130000001,Strip Shopping Center,2,1990,"4,958",NaN,2022,Average,8412 -- Neighborhood Shopping Ctr,--,2,1168130000001_2022.html
353246,1168130000001,Strip Shopping Center,6,1990,"11,160",NaN,2022,Good,8412 -- Neighborhood Shopping Ctr,--,3,1168130000001_2022.html
353247,1168130000001,Strip Shopping Center,7,1990,"23,030",NaN,2022,Good,8412 -- Neighborhood Shopping Ctr,--,4,1168130000001_2022.html
353248,1168130000001,Strip Shopping Center,1,1990,"13,054",Displayed,2023,Good,8412 -- Neighborhood Shopping Ctr,2007,1,1168130000001_2023.html
353249,1168130000001,Strip Shopping Center,2,1990,"4,958",NaN,2023,Average,8412 -- Neighborhood Shopping Ctr,--,2,1168130000001_2023.html
353250,1168130000001,Strip Shopping Center,6,1990,"11,160",NaN,2023,Good,8412 -- Neighborhood Shopping Ctr,--,3,1168130000001_2023.html
353251,1168130000001,Strip Shopping Center,7,1990,"23,030",NaN,2023,Good,8412 -- Neighborhood Shopping Ctr,--,4,1168130000001_2023.html
353252,1168130000001,Strip Shopping Center,1,1990,"13,054",Displayed,2024,Good,8412 -- Neighborhood Shopping Ctr,2007,1,1168130000001_2024.html
353253,1168130000001,Strip Shopping Center,2,1990,"4,958",NaN,2024,Average,8412 -- Neighborhood Shopping Ctr,--,2,1168130000001_2024.html
353254,1168130000001,Strip Shopping Center,6,1990,"11,160",NaN,2024,Good,8412 -- Neighborhood Shopping Ctr,--,3,1168130000001_2024.html
353255,1168130000001,Strip Shopping Center,7,1990,"23,030",NaN,2024,Good,8412 -- Neighborhood Shopping Ctr,--,4,1168130000001_2024.html
353256,1168130000001,Strip Shopping Center,1,1990,"13,054",Displayed,2025,Good,8412 -- Neighborhood Shopping Ctr,2007,1,1168130000001_2025.html
353257,1168130000001,Strip Shopping Center,2,1990,"4,958",NaN,2025,Average,8412 -- Neighborhood Shopping Ctr,--,2,1168130000001_2025.html
353258,1168130000001,Strip Shopping Center,6,1990,"11,160",NaN,2025,Good,8412 -- Neighborhood Shopping Ctr,--,3,1168130000001_2025.html
353259,1168130000001,Strip Shopping Center,7,1990,"23,030",NaN,2025,Good,8412 -- Neighborhood Shopping Ctr,--,4,1168130000001_2025.html
353260,1168130000001,Strip Shopping Center,1,1990,"13,054",Displayed,2026,Good,8412 -- Neighborhood Shopping Ctr,2007,1,1168130000001_2026.html
353261,1168130000001,Strip Shopping Center,2,1990,"4,958",NaN,2026,Average,8412 -- Neighborhood Shopping Ctr,--,2,1168130000001_2026.html
353262,1168130000001,Strip Shopping Center,6,1990,"11,160",NaN,2026,Good,8412 -- Neighborhood Shopping Ctr,--,3,1168130000001_2026.html
353263,1168130000001,Strip Shopping Center,7,1990,"23,030",NaN,2026,Good,8412 -- Neighborhood Shopping Ctr,--,4,1168130000001_2026.html

In [ ]:
df[df['parcel_number']=='1113770000001']

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
6073707,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2021,Excellent,8344 -- Office Building,NaN,1,1113770000001_2021.html
6073708,1113770000001,Parking Garage,2,1981,"340,792",NaN,2021,Average,8345 -- Parking Structure,NaN,2,1113770000001_2021.html
6073709,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2022,Excellent,8344 -- Office Building,NaN,1,1113770000001_2022.html
6073710,1113770000001,Parking Garage,2,1981,"340,792",NaN,2022,Average,8345 -- Parking Structure,NaN,2,1113770000001_2022.html
6073711,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2023,Excellent,8344 -- Office Building,NaN,1,1113770000001_2023.html
6073712,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2024,Excellent,8344 -- Office Building,NaN,1,1113770000001_2024.html
6073713,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2025,Excellent,8344 -- Office Building,NaN,1,1113770000001_2025.html
6073714,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2026,Excellent,8344 -- Office Building,NaN,1,1113770000001_2026.html
6772261,1113770000001,Parking Garage,2,1981,"340,792",NaN,2023,Average,8345 -- Parking Structure,NaN,1,1113770000001_2023.html
6772262,1113770000001,Parking Garage,2,1981,"340,792",NaN,2024,Average,8345 -- Parking Structure,NaN,1,1113770000001_2024.html
6772263,1113770000001,Parking Garage,2,1981,"340,792",NaN,2025,Average,8345 -- Parking Structure,NaN,1,1113770000001_2025.html
6772264,1113770000001,Parking Garage,2,1981,"340,792",NaN,2026,Average,8345 -- Parking Structure,NaN,1,1113770000001_2026.html

In [ ]:
df[(df['parcel_number']=='1113770000001') & (df['year']==2026)]

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
6073714,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2026,Excellent,8344 -- Office Building,NaN,1,1113770000001_2026.html
6772264,1113770000001,Parking Garage,2,1981,"340,792",NaN,2026,Average,8345 -- Parking Structure,NaN,1,1113770000001_2026.html

In [ ]:
filtered_df = df[(df['parcel_number'] == '1168130000001') & (df['year'] == 2021)]

filtered_df = filtered_df.dropna(axis=1, how='all')
filtered_df

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
353240,1168130000001,Strip Shopping Center,1,1990,"13,054",Displayed,2021,Good,8412 -- Neighborhood Shopping Ctr,2007,1,1168130000001_2021.html
353241,1168130000001,Strip Shopping Center,2,1990,"4,958",NaN,2021,Average,8412 -- Neighborhood Shopping Ctr,--,2,1168130000001_2021.html
353242,1168130000001,Strip Shopping Center,6,1990,"11,160",NaN,2021,Good,8412 -- Neighborhood Shopping Ctr,--,3,1168130000001_2021.html
353243,1168130000001,Strip Shopping Center,7,1990,"23,030",NaN,2021,Good,8412 -- Neighborhood Shopping Ctr,--,4,1168130000001_2021.html

In [ ]:
df['building_number'].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
       183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195,
       196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208,
       209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,
       222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234,
       235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247,
       248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260,
       261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273,
       274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286,
       287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299,
       300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312,
       313, 314, 315, 316, 317, 318])

In [ ]:
df[df['building_number']==328]

Empty DataFrame
Columns: [parcel_number, type, building, year_built, impr_sq_ft, building_details, year, quality, style, remodeled, building_number, page_save]
Index: []

In [ ]:
df[df['building']==328]

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
2626708,0440990010029,Storage Tank - Medium,328,2024,"100,200",NaN,2025,Average,9783 -- Storage Tank - Medium,--,318,0440990010029_2025.html
2627026,0440990010029,Storage Tank - Medium,328,2024,"97,000",NaN,2026,Average,9783 -- Storage Tank - Medium,--,318,0440990010029_2026.html

In [ ]:
df[(df['parcel_number']=='0440990010029') & (df['year']==2021)]

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
2625129,0440990010029,Office Bldgs. Low-Rise (1 to 4 Stories),1,2010,"39,318",Displayed,2021,Average,9344 -- Office Building,NaN,1,0440990010029_2021.html
2625130,0440990010029,Petroleum Refining / Industry,2,2000,"10,908",NaN,2021,Average,9406 -- Industrial Warehouse,NaN,2,0440990010029_2021.html
2625131,0440990010029,Storage Tank - Small,4,1972,"12,000",NaN,2021,Average,9782 -- Storage Tank - Small,NaN,3,0440990010029_2021.html
2625132,0440990010029,Storage Tank - Small,5,1972,"12,000",NaN,2021,Average,9782 -- Storage Tank - Small,NaN,4,0440990010029_2021.html
2625133,0440990010029,Storage Tank - Small,6,1975,"12,000",NaN,2021,Average,9782 -- Storage Tank - Small,NaN,5,0440990010029_2021.html
...,...,...,...,...,...,...,...,...,...,...,...,...
2625441,0440990010029,Storage Tank - Medium,321,2020,"30,000",NaN,2021,Average,9783 -- Storage Tank - Medium,NaN,313,0440990010029_2021.html
2625442,0440990010029,Storage Tank - Medium,322,2020,"30,000",NaN,2021,Average,9783 -- Storage Tank - Medium,NaN,314,0440990010029_2021.html
2625443,0440990010029,Storage Tank - Medium,323,2020,"30,000",NaN,2021,Average,9783 -- Storage Tank - Medium,NaN,315,0440990010029_2021.html
2625444,0440990010029,Storage Tank - Medium,324,2020,"30,000",NaN,2021,Average,9783 -- Storage Tank - Medium,NaN,316,0440990010029_2021.html
2625445,0440990010029,Storage Tank - Medium,325,2020,"30,000",NaN,2021,Average,9783 -- Storage Tank - Medium,NaN,317,0440990010029_2021.html

In [ ]:
df[(df['parcel_number']=='0440990010029') & (df['year']==2022)]

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
2625446,0440990010029,Office Bldgs. Low-Rise (1 to 4 Stories),1,2010,"39,318",Displayed,2022,Average,9344 -- Office Building,NaN,1,0440990010029_2022.html
2625447,0440990010029,Petroleum Refining / Industry,2,2000,"10,908",NaN,2022,Average,9406 -- Industrial Warehouse,NaN,2,0440990010029_2022.html
2625448,0440990010029,Storage Tank - Small,4,1972,"12,000",NaN,2022,Average,9782 -- Storage Tank - Small,NaN,3,0440990010029_2022.html
2625449,0440990010029,Storage Tank - Small,5,1972,"12,000",NaN,2022,Average,9782 -- Storage Tank - Small,NaN,4,0440990010029_2022.html
2625450,0440990010029,Storage Tank - Small,6,1975,"12,000",NaN,2022,Average,9782 -- Storage Tank - Small,NaN,5,0440990010029_2022.html
...,...,...,...,...,...,...,...,...,...,...,...,...
2625756,0440990010029,Storage Tank - Medium,321,2020,"30,000",NaN,2022,Average,9783 -- Storage Tank - Medium,NaN,311,0440990010029_2022.html
2625757,0440990010029,Storage Tank - Medium,322,2020,"30,000",NaN,2022,Average,9783 -- Storage Tank - Medium,NaN,312,0440990010029_2022.html
2625758,0440990010029,Storage Tank - Medium,323,2020,"30,000",NaN,2022,Average,9783 -- Storage Tank - Medium,NaN,313,0440990010029_2022.html
2625759,0440990010029,Storage Tank - Medium,324,2020,"30,000",NaN,2022,Average,9783 -- Storage Tank - Medium,NaN,314,0440990010029_2022.html
2625760,0440990010029,Storage Tank - Medium,325,2020,"30,000",NaN,2022,Average,9783 -- Storage Tank - Medium,NaN,315,0440990010029_2022.html

In [ ]:
df[(df['parcel_number']=='0440990010029') & (df['year']==2023)]

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
2625761,0440990010029,Office Bldgs. Low-Rise (1 to 4 Stories),1,2010,"39,318",Displayed,2023,Average,9344 -- Office Building,--,1,0440990010029_2023.html
2625762,0440990010029,Petroleum Refining / Industry,2,2000,"10,908",NaN,2023,Average,9406 -- Industrial Warehouse,--,2,0440990010029_2023.html
2625763,0440990010029,Storage Tank - Small,4,1972,"12,000",NaN,2023,Average,9782 -- Storage Tank - Small,--,3,0440990010029_2023.html
2625764,0440990010029,Storage Tank - Small,5,1972,"12,000",NaN,2023,Average,9782 -- Storage Tank - Small,--,4,0440990010029_2023.html
2625765,0440990010029,Storage Tank - Small,6,1975,"12,000",NaN,2023,Average,9782 -- Storage Tank - Small,--,5,0440990010029_2023.html
...,...,...,...,...,...,...,...,...,...,...,...,...
2626071,0440990010029,Storage Tank - Medium,321,2020,"30,000",NaN,2023,Average,9783 -- Storage Tank - Medium,--,311,0440990010029_2023.html
2626072,0440990010029,Storage Tank - Medium,322,2020,"30,000",NaN,2023,Average,9783 -- Storage Tank - Medium,--,312,0440990010029_2023.html
2626073,0440990010029,Storage Tank - Medium,323,2020,"30,000",NaN,2023,Average,9783 -- Storage Tank - Medium,--,313,0440990010029_2023.html
2626074,0440990010029,Storage Tank - Medium,324,2020,"30,000",NaN,2023,Average,9783 -- Storage Tank - Medium,--,314,0440990010029_2023.html
2626075,0440990010029,Storage Tank - Medium,325,2020,"30,000",NaN,2023,Average,9783 -- Storage Tank - Medium,--,315,0440990010029_2023.html

In [ ]:
df[(df['parcel_number']=='0440990010029') & (df['year']==2024)]

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
2626076,0440990010029,Office Bldgs. Low-Rise (1 to 4 Stories),1,2010,"39,318",Displayed,2024,Average,9344 -- Office Building,--,1,0440990010029_2024.html
2626077,0440990010029,Petroleum Refining / Industry,2,2000,"10,908",NaN,2024,Average,9406 -- Industrial Warehouse,--,2,0440990010029_2024.html
2626078,0440990010029,Storage Tank - Small,4,1972,"12,000",NaN,2024,Average,9782 -- Storage Tank - Small,--,3,0440990010029_2024.html
2626079,0440990010029,Storage Tank - Small,5,1972,"12,000",NaN,2024,Average,9782 -- Storage Tank - Small,--,4,0440990010029_2024.html
2626080,0440990010029,Storage Tank - Small,6,1975,"12,000",NaN,2024,Average,9782 -- Storage Tank - Small,--,5,0440990010029_2024.html
...,...,...,...,...,...,...,...,...,...,...,...,...
2626386,0440990010029,Storage Tank - Medium,321,2020,"30,000",NaN,2024,Average,9783 -- Storage Tank - Medium,--,311,0440990010029_2024.html
2626387,0440990010029,Storage Tank - Medium,322,2020,"30,000",NaN,2024,Average,9783 -- Storage Tank - Medium,--,312,0440990010029_2024.html
2626388,0440990010029,Storage Tank - Medium,323,2020,"30,000",NaN,2024,Average,9783 -- Storage Tank - Medium,--,313,0440990010029_2024.html
2626389,0440990010029,Storage Tank - Medium,324,2020,"30,000",NaN,2024,Average,9783 -- Storage Tank - Medium,--,314,0440990010029_2024.html
2626390,0440990010029,Storage Tank - Medium,325,2020,"30,000",NaN,2024,Average,9783 -- Storage Tank - Medium,--,315,0440990010029_2024.html

In [ ]:
df[(df['parcel_number']=='0440990010029') & (df['year']==2025)]

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
2626391,0440990010029,Office Bldgs. Low-Rise (1 to 4 Stories),1,2010,"39,318",Displayed,2025,Average,9344 -- Office Building,--,1,0440990010029_2025.html
2626392,0440990010029,Petroleum Refining / Industry,2,2000,"10,908",NaN,2025,Average,9406 -- Industrial Warehouse,--,2,0440990010029_2025.html
2626393,0440990010029,Storage Tank - Small,4,1972,"12,000",NaN,2025,Average,9782 -- Storage Tank - Small,--,3,0440990010029_2025.html
2626394,0440990010029,Storage Tank - Small,5,1972,"12,000",NaN,2025,Average,9782 -- Storage Tank - Small,--,4,0440990010029_2025.html
2626395,0440990010029,Storage Tank - Small,6,1975,"12,000",NaN,2025,Average,9782 -- Storage Tank - Small,--,5,0440990010029_2025.html
...,...,...,...,...,...,...,...,...,...,...,...,...
2626704,0440990010029,Storage Tank - Medium,324,2020,"30,000",NaN,2025,Average,9783 -- Storage Tank - Medium,--,314,0440990010029_2025.html
2626705,0440990010029,Storage Tank - Medium,325,2020,"30,000",NaN,2025,Average,9783 -- Storage Tank - Medium,--,315,0440990010029_2025.html
2626706,0440990010029,Storage Tank - Medium,326,2024,"101,200",NaN,2025,Average,9783 -- Storage Tank - Medium,--,316,0440990010029_2025.html
2626707,0440990010029,Storage Tank - Medium,327,2024,"100,200",NaN,2025,Average,9783 -- Storage Tank - Medium,--,317,0440990010029_2025.html
2626708,0440990010029,Storage Tank - Medium,328,2024,"100,200",NaN,2025,Average,9783 -- Storage Tank - Medium,--,318,0440990010029_2025.html

In [ ]:
df[(df['parcel_number']=='0440990010029') & (df['year']==2026)]

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
2626709,0440990010029,Office Bldgs. Low-Rise (1 to 4 Stories),1,2010,"39,318",Displayed,2026,Average,9344 -- Office Building,--,1,0440990010029_2026.html
2626710,0440990010029,Petroleum Refining / Industry,2,2000,"10,908",NaN,2026,Average,9406 -- Industrial Warehouse,--,2,0440990010029_2026.html
2626711,0440990010029,Storage Tank - Small,4,1972,"12,000",NaN,2026,Average,9782 -- Storage Tank - Small,--,3,0440990010029_2026.html
2626712,0440990010029,Storage Tank - Small,5,1972,"12,000",NaN,2026,Average,9782 -- Storage Tank - Small,--,4,0440990010029_2026.html
2626713,0440990010029,Storage Tank - Small,6,1975,"12,000",NaN,2026,Average,9782 -- Storage Tank - Small,--,5,0440990010029_2026.html
...,...,...,...,...,...,...,...,...,...,...,...,...
2627022,0440990010029,Storage Tank - Medium,324,2020,"30,000",NaN,2026,Average,9783 -- Storage Tank - Medium,--,314,0440990010029_2026.html
2627023,0440990010029,Storage Tank - Medium,325,2020,"30,000",NaN,2026,Average,9783 -- Storage Tank - Medium,--,315,0440990010029_2026.html
2627024,0440990010029,Storage Tank - Medium,326,2024,"97,000",NaN,2026,Average,9783 -- Storage Tank - Medium,--,316,0440990010029_2026.html
2627025,0440990010029,Storage Tank - Medium,327,2024,"97,000",NaN,2026,Average,9783 -- Storage Tank - Medium,--,317,0440990010029_2026.html
2627026,0440990010029,Storage Tank - Medium,328,2024,"97,000",NaN,2026,Average,9783 -- Storage Tank - Medium,--,318,0440990010029_2026.html

In [ ]:
df[df['parcel_number']=='0440990010029']

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
2625129,0440990010029,Office Bldgs. Low-Rise (1 to 4 Stories),1,2010,"39,318",Displayed,2021,Average,9344 -- Office Building,NaN,1,0440990010029_2021.html
2625130,0440990010029,Petroleum Refining / Industry,2,2000,"10,908",NaN,2021,Average,9406 -- Industrial Warehouse,NaN,2,0440990010029_2021.html
2625131,0440990010029,Storage Tank - Small,4,1972,"12,000",NaN,2021,Average,9782 -- Storage Tank - Small,NaN,3,0440990010029_2021.html
2625132,0440990010029,Storage Tank - Small,5,1972,"12,000",NaN,2021,Average,9782 -- Storage Tank - Small,NaN,4,0440990010029_2021.html
2625133,0440990010029,Storage Tank - Small,6,1975,"12,000",NaN,2021,Average,9782 -- Storage Tank - Small,NaN,5,0440990010029_2021.html
...,...,...,...,...,...,...,...,...,...,...,...,...
2627022,0440990010029,Storage Tank - Medium,324,2020,"30,000",NaN,2026,Average,9783 -- Storage Tank - Medium,--,314,0440990010029_2026.html
2627023,0440990010029,Storage Tank - Medium,325,2020,"30,000",NaN,2026,Average,9783 -- Storage Tank - Medium,--,315,0440990010029_2026.html
2627024,0440990010029,Storage Tank - Medium,326,2024,"97,000",NaN,2026,Average,9783 -- Storage Tank - Medium,--,316,0440990010029_2026.html
2627025,0440990010029,Storage Tank - Medium,327,2024,"97,000",NaN,2026,Average,9783 -- Storage Tank - Medium,--,317,0440990010029_2026.html
2627026,0440990010029,Storage Tank - Medium,328,2024,"97,000",NaN,2026,Average,9783 -- Storage Tank - Medium,--,318,0440990010029_2026.html

In [ ]:
df[(df['parcel_number']=='0440990010029') & (df['year']==2024)]

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
2626076,0440990010029,Office Bldgs. Low-Rise (1 to 4 Stories),1,2010,"39,318",Displayed,2024,Average,9344 -- Office Building,--,1,0440990010029_2024.html
2626077,0440990010029,Petroleum Refining / Industry,2,2000,"10,908",NaN,2024,Average,9406 -- Industrial Warehouse,--,2,0440990010029_2024.html
2626078,0440990010029,Storage Tank - Small,4,1972,"12,000",NaN,2024,Average,9782 -- Storage Tank - Small,--,3,0440990010029_2024.html
2626079,0440990010029,Storage Tank - Small,5,1972,"12,000",NaN,2024,Average,9782 -- Storage Tank - Small,--,4,0440990010029_2024.html
2626080,0440990010029,Storage Tank - Small,6,1975,"12,000",NaN,2024,Average,9782 -- Storage Tank - Small,--,5,0440990010029_2024.html
...,...,...,...,...,...,...,...,...,...,...,...,...
2626386,0440990010029,Storage Tank - Medium,321,2020,"30,000",NaN,2024,Average,9783 -- Storage Tank - Medium,--,311,0440990010029_2024.html
2626387,0440990010029,Storage Tank - Medium,322,2020,"30,000",NaN,2024,Average,9783 -- Storage Tank - Medium,--,312,0440990010029_2024.html
2626388,0440990010029,Storage Tank - Medium,323,2020,"30,000",NaN,2024,Average,9783 -- Storage Tank - Medium,--,313,0440990010029_2024.html
2626389,0440990010029,Storage Tank - Medium,324,2020,"30,000",NaN,2024,Average,9783 -- Storage Tank - Medium,--,314,0440990010029_2024.html
2626390,0440990010029,Storage Tank - Medium,325,2020,"30,000",NaN,2024,Average,9783 -- Storage Tank - Medium,--,315,0440990010029_2024.html

In [ ]:
df[(df['parcel_number']=='0440990010029') & (df['year']==2023)]

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
2625761,0440990010029,Office Bldgs. Low-Rise (1 to 4 Stories),1,2010,"39,318",Displayed,2023,Average,9344 -- Office Building,--,1,0440990010029_2023.html
2625762,0440990010029,Petroleum Refining / Industry,2,2000,"10,908",NaN,2023,Average,9406 -- Industrial Warehouse,--,2,0440990010029_2023.html
2625763,0440990010029,Storage Tank - Small,4,1972,"12,000",NaN,2023,Average,9782 -- Storage Tank - Small,--,3,0440990010029_2023.html
2625764,0440990010029,Storage Tank - Small,5,1972,"12,000",NaN,2023,Average,9782 -- Storage Tank - Small,--,4,0440990010029_2023.html
2625765,0440990010029,Storage Tank - Small,6,1975,"12,000",NaN,2023,Average,9782 -- Storage Tank - Small,--,5,0440990010029_2023.html
...,...,...,...,...,...,...,...,...,...,...,...,...
2626071,0440990010029,Storage Tank - Medium,321,2020,"30,000",NaN,2023,Average,9783 -- Storage Tank - Medium,--,311,0440990010029_2023.html
2626072,0440990010029,Storage Tank - Medium,322,2020,"30,000",NaN,2023,Average,9783 -- Storage Tank - Medium,--,312,0440990010029_2023.html
2626073,0440990010029,Storage Tank - Medium,323,2020,"30,000",NaN,2023,Average,9783 -- Storage Tank - Medium,--,313,0440990010029_2023.html
2626074,0440990010029,Storage Tank - Medium,324,2020,"30,000",NaN,2023,Average,9783 -- Storage Tank - Medium,--,314,0440990010029_2023.html
2626075,0440990010029,Storage Tank - Medium,325,2020,"30,000",NaN,2023,Average,9783 -- Storage Tank - Medium,--,315,0440990010029_2023.html

In [ ]:
df[(df['parcel_number']=='0440990010029') & (df['year']==2022)]

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
2625446,0440990010029,Office Bldgs. Low-Rise (1 to 4 Stories),1,2010,"39,318",Displayed,2022,Average,9344 -- Office Building,NaN,1,0440990010029_2022.html
2625447,0440990010029,Petroleum Refining / Industry,2,2000,"10,908",NaN,2022,Average,9406 -- Industrial Warehouse,NaN,2,0440990010029_2022.html
2625448,0440990010029,Storage Tank - Small,4,1972,"12,000",NaN,2022,Average,9782 -- Storage Tank - Small,NaN,3,0440990010029_2022.html
2625449,0440990010029,Storage Tank - Small,5,1972,"12,000",NaN,2022,Average,9782 -- Storage Tank - Small,NaN,4,0440990010029_2022.html
2625450,0440990010029,Storage Tank - Small,6,1975,"12,000",NaN,2022,Average,9782 -- Storage Tank - Small,NaN,5,0440990010029_2022.html
...,...,...,...,...,...,...,...,...,...,...,...,...
2625756,0440990010029,Storage Tank - Medium,321,2020,"30,000",NaN,2022,Average,9783 -- Storage Tank - Medium,NaN,311,0440990010029_2022.html
2625757,0440990010029,Storage Tank - Medium,322,2020,"30,000",NaN,2022,Average,9783 -- Storage Tank - Medium,NaN,312,0440990010029_2022.html
2625758,0440990010029,Storage Tank - Medium,323,2020,"30,000",NaN,2022,Average,9783 -- Storage Tank - Medium,NaN,313,0440990010029_2022.html
2625759,0440990010029,Storage Tank - Medium,324,2020,"30,000",NaN,2022,Average,9783 -- Storage Tank - Medium,NaN,314,0440990010029_2022.html
2625760,0440990010029,Storage Tank - Medium,325,2020,"30,000",NaN,2022,Average,9783 -- Storage Tank - Medium,NaN,315,0440990010029_2022.html

In [ ]:
df[(df['parcel_number']=='0440990010029') & (df['year']==2021)]

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
2625129,0440990010029,Office Bldgs. Low-Rise (1 to 4 Stories),1,2010,"39,318",Displayed,2021,Average,9344 -- Office Building,NaN,1,0440990010029_2021.html
2625130,0440990010029,Petroleum Refining / Industry,2,2000,"10,908",NaN,2021,Average,9406 -- Industrial Warehouse,NaN,2,0440990010029_2021.html
2625131,0440990010029,Storage Tank - Small,4,1972,"12,000",NaN,2021,Average,9782 -- Storage Tank - Small,NaN,3,0440990010029_2021.html
2625132,0440990010029,Storage Tank - Small,5,1972,"12,000",NaN,2021,Average,9782 -- Storage Tank - Small,NaN,4,0440990010029_2021.html
2625133,0440990010029,Storage Tank - Small,6,1975,"12,000",NaN,2021,Average,9782 -- Storage Tank - Small,NaN,5,0440990010029_2021.html
...,...,...,...,...,...,...,...,...,...,...,...,...
2625441,0440990010029,Storage Tank - Medium,321,2020,"30,000",NaN,2021,Average,9783 -- Storage Tank - Medium,NaN,313,0440990010029_2021.html
2625442,0440990010029,Storage Tank - Medium,322,2020,"30,000",NaN,2021,Average,9783 -- Storage Tank - Medium,NaN,314,0440990010029_2021.html
2625443,0440990010029,Storage Tank - Medium,323,2020,"30,000",NaN,2021,Average,9783 -- Storage Tank - Medium,NaN,315,0440990010029_2021.html
2625444,0440990010029,Storage Tank - Medium,324,2020,"30,000",NaN,2021,Average,9783 -- Storage Tank - Medium,NaN,316,0440990010029_2021.html
2625445,0440990010029,Storage Tank - Medium,325,2020,"30,000",NaN,2021,Average,9783 -- Storage Tank - Medium,NaN,317,0440990010029_2021.html

In [ ]:
df[(df['parcel_number']=='0440990010029') & (df['year']==2025)]

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
2626391,0440990010029,Office Bldgs. Low-Rise (1 to 4 Stories),1,2010,"39,318",Displayed,2025,Average,9344 -- Office Building,--,1,0440990010029_2025.html
2626392,0440990010029,Petroleum Refining / Industry,2,2000,"10,908",NaN,2025,Average,9406 -- Industrial Warehouse,--,2,0440990010029_2025.html
2626393,0440990010029,Storage Tank - Small,4,1972,"12,000",NaN,2025,Average,9782 -- Storage Tank - Small,--,3,0440990010029_2025.html
2626394,0440990010029,Storage Tank - Small,5,1972,"12,000",NaN,2025,Average,9782 -- Storage Tank - Small,--,4,0440990010029_2025.html
2626395,0440990010029,Storage Tank - Small,6,1975,"12,000",NaN,2025,Average,9782 -- Storage Tank - Small,--,5,0440990010029_2025.html
...,...,...,...,...,...,...,...,...,...,...,...,...
2626704,0440990010029,Storage Tank - Medium,324,2020,"30,000",NaN,2025,Average,9783 -- Storage Tank - Medium,--,314,0440990010029_2025.html
2626705,0440990010029,Storage Tank - Medium,325,2020,"30,000",NaN,2025,Average,9783 -- Storage Tank - Medium,--,315,0440990010029_2025.html
2626706,0440990010029,Storage Tank - Medium,326,2024,"101,200",NaN,2025,Average,9783 -- Storage Tank - Medium,--,316,0440990010029_2025.html
2626707,0440990010029,Storage Tank - Medium,327,2024,"100,200",NaN,2025,Average,9783 -- Storage Tank - Medium,--,317,0440990010029_2025.html
2626708,0440990010029,Storage Tank - Medium,328,2024,"100,200",NaN,2025,Average,9783 -- Storage Tank - Medium,--,318,0440990010029_2025.html

In [ ]:
df[df['parcel_number']=='1471360030013']

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
7792926,1471360030013,Residential Single Family,1,2025,"2,810 *",Displayed,2026,Average,101 -- Residential 1 Family,NaN,1,1471360030013_2026.html

In [ ]:
df[df['parcel_number']=='1063340000002']

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
7220320,1063340000002,Residential Single Family,1,2021,"1,040 *",Displayed,2022,Average,101 -- Residential 1 Family,NaN,1,1063340000002_2022.html
7220321,1063340000002,Residential Single Family,1,2021,"1,040 *",Displayed,2023,Average,101 -- Residential 1 Family,NaN,1,1063340000002_2023.html
7220322,1063340000002,Residential Single Family,1,2021,"1,040 *",Displayed,2024,Average,101 -- Residential 1 Family,NaN,1,1063340000002_2024.html
7220323,1063340000002,Residential Single Family,1,2021,"1,040 *",Displayed,2025,Average,101 -- Residential 1 Family,NaN,1,1063340000002_2025.html
7220324,1063340000002,Residential Single Family,1,2021,"1,040 *",Displayed,2026,Average,101 -- Residential 1 Family,NaN,1,1063340000002_2026.html

In [ ]:
df[df['parcel_number']=='1000520000005']

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
7053312,1000520000005,Residential Single Family,1,2022,"2,330 *",Displayed,2023,Good,101 -- Residential 1 Family,NaN,1,1000520000005_2023.html
7053313,1000520000005,Residential Single Family,1,2022,"2,330 *",Displayed,2024,Good,101 -- Residential 1 Family,NaN,1,1000520000005_2024.html
7053314,1000520000005,Residential Single Family,1,2022,"2,330 *",Displayed,2025,Good,101 -- Residential 1 Family,NaN,1,1000520000005_2025.html
7053315,1000520000005,Residential Single Family,1,2022,"2,330 *",Displayed,2026,Good,101 -- Residential 1 Family,NaN,1,1000520000005_2026.html

In [ ]:
df[(df['parcel_number']=='0440990010029') & (df['year']==2026)]

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
2626709,0440990010029,Office Bldgs. Low-Rise (1 to 4 Stories),1,2010,"39,318",Displayed,2026,Average,9344 -- Office Building,--,1,0440990010029_2026.html
2626710,0440990010029,Petroleum Refining / Industry,2,2000,"10,908",NaN,2026,Average,9406 -- Industrial Warehouse,--,2,0440990010029_2026.html
2626711,0440990010029,Storage Tank - Small,4,1972,"12,000",NaN,2026,Average,9782 -- Storage Tank - Small,--,3,0440990010029_2026.html
2626712,0440990010029,Storage Tank - Small,5,1972,"12,000",NaN,2026,Average,9782 -- Storage Tank - Small,--,4,0440990010029_2026.html
2626713,0440990010029,Storage Tank - Small,6,1975,"12,000",NaN,2026,Average,9782 -- Storage Tank - Small,--,5,0440990010029_2026.html
...,...,...,...,...,...,...,...,...,...,...,...,...
2627022,0440990010029,Storage Tank - Medium,324,2020,"30,000",NaN,2026,Average,9783 -- Storage Tank - Medium,--,314,0440990010029_2026.html
2627023,0440990010029,Storage Tank - Medium,325,2020,"30,000",NaN,2026,Average,9783 -- Storage Tank - Medium,--,315,0440990010029_2026.html
2627024,0440990010029,Storage Tank - Medium,326,2024,"97,000",NaN,2026,Average,9783 -- Storage Tank - Medium,--,316,0440990010029_2026.html
2627025,0440990010029,Storage Tank - Medium,327,2024,"97,000",NaN,2026,Average,9783 -- Storage Tank - Medium,--,317,0440990010029_2026.html
2627026,0440990010029,Storage Tank - Medium,328,2024,"97,000",NaN,2026,Average,9783 -- Storage Tank - Medium,--,318,0440990010029_2026.html

In [ ]:
df.loc[df['parcel_number'] == '0440990010029', 'year'].unique().tolist()

[2021, 2022, 2023, 2024, 2025, 2026]

In [ ]:
filtered_df = df[(df['parcel_number'] == '0440990010029') & (df['building_number'] == 318)]

filtered_df = filtered_df.dropna(axis=1, how='all')
filtered_df

,parcel_number,type,building,year_built,impr_sq_ft,year,quality,style,remodeled,building_number,page_save
2626708,0440990010029,Storage Tank - Medium,328,2024,"100,200",2025,Average,9783 -- Storage Tank - Medium,--,318,0440990010029_2025.html
2627026,0440990010029,Storage Tank - Medium,328,2024,"97,000",2026,Average,9783 -- Storage Tank - Medium,--,318,0440990010029_2026.html

In [ ]:
filtered_df = df[(df['parcel_number'] == '1113770000001') ]

filtered_df = filtered_df.dropna(axis=1, how='all')
filtered_df

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,building_number,page_save
6073707,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2021,Excellent,8344 -- Office Building,1,1113770000001_2021.html
6073708,1113770000001,Parking Garage,2,1981,"340,792",NaN,2021,Average,8345 -- Parking Structure,2,1113770000001_2021.html
6073709,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2022,Excellent,8344 -- Office Building,1,1113770000001_2022.html
6073710,1113770000001,Parking Garage,2,1981,"340,792",NaN,2022,Average,8345 -- Parking Structure,2,1113770000001_2022.html
6073711,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2023,Excellent,8344 -- Office Building,1,1113770000001_2023.html
6073712,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2024,Excellent,8344 -- Office Building,1,1113770000001_2024.html
6073713,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2025,Excellent,8344 -- Office Building,1,1113770000001_2025.html
6073714,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2026,Excellent,8344 -- Office Building,1,1113770000001_2026.html
6772261,1113770000001,Parking Garage,2,1981,"340,792",NaN,2023,Average,8345 -- Parking Structure,1,1113770000001_2023.html
6772262,1113770000001,Parking Garage,2,1981,"340,792",NaN,2024,Average,8345 -- Parking Structure,1,1113770000001_2024.html
6772263,1113770000001,Parking Garage,2,1981,"340,792",NaN,2025,Average,8345 -- Parking Structure,1,1113770000001_2025.html
6772264,1113770000001,Parking Garage,2,1981,"340,792",NaN,2026,Average,8345 -- Parking Structure,1,1113770000001_2026.html

In [ ]:
df[(df['parcel_number'] == '1113770000001') & (df['impr_sq_ft']=='340,792')]

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
6073708,1113770000001,Parking Garage,2,1981,"340,792",NaN,2021,Average,8345 -- Parking Structure,NaN,2,1113770000001_2021.html
6073710,1113770000001,Parking Garage,2,1981,"340,792",NaN,2022,Average,8345 -- Parking Structure,NaN,2,1113770000001_2022.html
6772261,1113770000001,Parking Garage,2,1981,"340,792",NaN,2023,Average,8345 -- Parking Structure,NaN,1,1113770000001_2023.html
6772262,1113770000001,Parking Garage,2,1981,"340,792",NaN,2024,Average,8345 -- Parking Structure,NaN,1,1113770000001_2024.html
6772263,1113770000001,Parking Garage,2,1981,"340,792",NaN,2025,Average,8345 -- Parking Structure,NaN,1,1113770000001_2025.html
6772264,1113770000001,Parking Garage,2,1981,"340,792",NaN,2026,Average,8345 -- Parking Structure,NaN,1,1113770000001_2026.html

In [ ]:
filtered_df = df[(df['parcel_number'] == '1113770000001') & (df['impr_sq_ft']=='324,758')]

filtered_df = filtered_df.dropna(axis=1, how='all')
filtered_df

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,building_number,page_save
6073707,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2021,Excellent,8344 -- Office Building,1,1113770000001_2021.html
6073709,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2022,Excellent,8344 -- Office Building,1,1113770000001_2022.html
6073711,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2023,Excellent,8344 -- Office Building,1,1113770000001_2023.html
6073712,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2024,Excellent,8344 -- Office Building,1,1113770000001_2024.html
6073713,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2025,Excellent,8344 -- Office Building,1,1113770000001_2025.html
6073714,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2026,Excellent,8344 -- Office Building,1,1113770000001_2026.html

In [ ]:
df['quality'].value_counts()

quality
Average      5001295
Good         2021655
Low           695440
Excellent     488806
Superior       77721
Very Low       45501
Poor             214
Name: count, dtype: int64

In [ ]:
df[df['parcel_number'] == '1113770000001']

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
6073707,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2021,Excellent,8344 -- Office Building,NaN,1,1113770000001_2021.html
6073708,1113770000001,Parking Garage,2,1981,"340,792",NaN,2021,Average,8345 -- Parking Structure,NaN,2,1113770000001_2021.html
6073709,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2022,Excellent,8344 -- Office Building,NaN,1,1113770000001_2022.html
6073710,1113770000001,Parking Garage,2,1981,"340,792",NaN,2022,Average,8345 -- Parking Structure,NaN,2,1113770000001_2022.html
6073711,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2023,Excellent,8344 -- Office Building,NaN,1,1113770000001_2023.html
6073712,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2024,Excellent,8344 -- Office Building,NaN,1,1113770000001_2024.html
6073713,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2025,Excellent,8344 -- Office Building,NaN,1,1113770000001_2025.html
6073714,1113770000001,Office Bldgs. Hi-Rise (5+ Stories),1,1981,"324,758",Displayed,2026,Excellent,8344 -- Office Building,NaN,1,1113770000001_2026.html
6772261,1113770000001,Parking Garage,2,1981,"340,792",NaN,2023,Average,8345 -- Parking Structure,NaN,1,1113770000001_2023.html
6772262,1113770000001,Parking Garage,2,1981,"340,792",NaN,2024,Average,8345 -- Parking Structure,NaN,1,1113770000001_2024.html
6772263,1113770000001,Parking Garage,2,1981,"340,792",NaN,2025,Average,8345 -- Parking Structure,NaN,1,1113770000001_2025.html
6772264,1113770000001,Parking Garage,2,1981,"340,792",NaN,2026,Average,8345 -- Parking Structure,NaN,1,1113770000001_2026.html

In [ ]:

filtered_df = df[(df['parcel_number'] == '0421300000163') ]

filtered_df = filtered_df.dropna(axis=1, how='all')
filtered_df

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,building_number,page_save
15656,0421300000163,Office Bldgs. Low-Rise (1 to 4 Stories),1,1977,"31,050",Displayed,2021,Average,8344 -- Office Building,1,0421300000163_2021.html
15657,0421300000163,Office Bldgs. Low-Rise (1 to 4 Stories),1,1977,"31,050",Displayed,2022,Average,8344 -- Office Building,1,0421300000163_2022.html
15658,0421300000163,Office Bldgs. Low-Rise (1 to 4 Stories),1,1977,"31,050",Displayed,2023,Average,8344 -- Office Building,1,0421300000163_2023.html
15659,0421300000163,Office Bldgs. Low-Rise (1 to 4 Stories),1,1977,"31,050",Displayed,2024,Average,8344 -- Office Building,1,0421300000163_2024.html
15660,0421300000163,Office Bldgs. Low-Rise (1 to 4 Stories),1,1977,"31,050",Displayed,2025,Average,8344 -- Office Building,1,0421300000163_2025.html
15661,0421300000163,Office Bldgs. Low-Rise (1 to 4 Stories),1,1977,"31,290",Displayed,2026,Average,8344 -- Office Building,1,0421300000163_2026.html

In [ ]:
df[df['impr_sq_ft']=='2049 *']

Empty DataFrame
Columns: [parcel_number, type, building, year_built, impr_sq_ft, building_details, year, quality, style, remodeled, building_number, page_save]
Index: []

## Replacing the '--' with null form column 'remodeled'

In [ ]:
df['remodeled'] = df['remodeled'].replace('--',np.nan)
df['remodeled']

0           NaN
1          2021
2          2021
3          2021
4          2021
           ...
8330634     NaN
8330635     NaN
8330636     NaN
8330637     NaN
8330638     NaN
Name: remodeled, Length: 8330639, dtype: object

In [ ]:
df['remodeled'].value_counts()

remodeled
2018      189347
2017      118961
2019       97674
2015       81205
2016       68591
           ...
2921           2
1920           1
2099           1
3312           1
1980.0         1
Name: count, Length: 118, dtype: int64

## Change type into intger from column

In [ ]:
cold = ['impr_sq_ft','year_built','year','remodeled']

for col in cold:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(',', '', regex=False)
        .str.extract(r'(\d+)', expand=False)
    )

df[cold] = df[cold].astype('Int64')
df[cold]

         impr_sq_ft  year_built  year  remodeled
0             22608        1900  2021       <NA>
1             22608        1900  2022       2021
2             22608        1900  2023       2021
3             22608        1900  2024       2021
4             22608        1900  2025       2021
...             ...         ...   ...        ...
8330634        1374        1979  2022       <NA>
8330635        1374        1979  2023       <NA>
8330636        1374        1979  2024       <NA>
8330637        1374        1979  2025       <NA>
8330638        1374        1979  2026       <NA>

[8330639 rows x 4 columns]

In [ ]:
df.info(verbose=True,show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8330639 entries, 0 to 8330638
Data columns (total 12 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   parcel_number     8330639 non-null  object
 1   type              8330639 non-null  object
 2   building          8330639 non-null  int64
 3   year_built        8330639 non-null  Int64
 4   impr_sq_ft        8330639 non-null  Int64
 5   building_details  7630281 non-null  object
 6   year              8330639 non-null  Int64
 7   quality           8330632 non-null  object
 8   style             8330639 non-null  object
 9   remodeled         1450134 non-null  Int64
 10  building_number   8330639 non-null  int64
 11  page_save         8330639 non-null  object
dtypes: Int64(4), int64(2), object(6)
memory usage: 794.5+ MB

In [ ]:
df.columns

Index(['parcel_number', 'type', 'building', 'year_built', 'impr_sq_ft',
       'building_details', 'year', 'quality', 'style', 'remodeled',
       'building_number', 'page_save'],
      dtype='object')

In [ ]:
df[df['parcel_number']=='1168130000001']

,parcel_number,type,building,year_built,impr_sq_ft,building_details,year,quality,style,remodeled,building_number,page_save
353240,1168130000001,Strip Shopping Center,1,1990,13054,Displayed,2021,Good,8412 -- Neighborhood Shopping Ctr,2007,1,1168130000001_2021.html
353241,1168130000001,Strip Shopping Center,2,1990,4958,NaN,2021,Average,8412 -- Neighborhood Shopping Ctr,<NA>,2,1168130000001_2021.html
353242,1168130000001,Strip Shopping Center,6,1990,11160,NaN,2021,Good,8412 -- Neighborhood Shopping Ctr,<NA>,3,1168130000001_2021.html
353243,1168130000001,Strip Shopping Center,7,1990,23030,NaN,2021,Good,8412 -- Neighborhood Shopping Ctr,<NA>,4,1168130000001_2021.html
353244,1168130000001,Strip Shopping Center,1,1990,13054,Displayed,2022,Good,8412 -- Neighborhood Shopping Ctr,2007,1,1168130000001_2022.html
353245,1168130000001,Strip Shopping Center,2,1990,4958,NaN,2022,Average,8412 -- Neighborhood Shopping Ctr,<NA>,2,1168130000001_2022.html
353246,1168130000001,Strip Shopping Center,6,1990,11160,NaN,2022,Good,8412 -- Neighborhood Shopping Ctr,<NA>,3,1168130000001_2022.html
353247,1168130000001,Strip Shopping Center,7,1990,23030,NaN,2022,Good,8412 -- Neighborhood Shopping Ctr,<NA>,4,1168130000001_2022.html
353248,1168130000001,Strip Shopping Center,1,1990,13054,Displayed,2023,Good,8412 -- Neighborhood Shopping Ctr,2007,1,1168130000001_2023.html
353249,1168130000001,Strip Shopping Center,2,1990,4958,NaN,2023,Average,8412 -- Neighborhood Shopping Ctr,<NA>,2,1168130000001_2023.html
353250,1168130000001,Strip Shopping Center,6,1990,11160,NaN,2023,Good,8412 -- Neighborhood Shopping Ctr,<NA>,3,1168130000001_2023.html
353251,1168130000001,Strip Shopping Center,7,1990,23030,NaN,2023,Good,8412 -- Neighborhood Shopping Ctr,<NA>,4,1168130000001_2023.html
353252,1168130000001,Strip Shopping Center,1,1990,13054,Displayed,2024,Good,8412 -- Neighborhood Shopping Ctr,2007,1,1168130000001_2024.html
353253,1168130000001,Strip Shopping Center,2,1990,4958,NaN,2024,Average,8412 -- Neighborhood Shopping Ctr,<NA>,2,1168130000001_2024.html
353254,1168130000001,Strip Shopping Center,6,1990,11160,NaN,2024,Good,8412 -- Neighborhood Shopping Ctr,<NA>,3,1168130000001_2024.html
353255,1168130000001,Strip Shopping Center,7,1990,23030,NaN,2024,Good,8412 -- Neighborhood Shopping Ctr,<NA>,4,1168130000001_2024.html
353256,1168130000001,Strip Shopping Center,1,1990,13054,Displayed,2025,Good,8412 -- Neighborhood Shopping Ctr,2007,1,1168130000001_2025.html
353257,1168130000001,Strip Shopping Center,2,1990,4958,NaN,2025,Average,8412 -- Neighborhood Shopping Ctr,<NA>,2,1168130000001_2025.html
353258,1168130000001,Strip Shopping Center,6,1990,11160,NaN,2025,Good,8412 -- Neighborhood Shopping Ctr,<NA>,3,1168130000001_2025.html
353259,1168130000001,Strip Shopping Center,7,1990,23030,NaN,2025,Good,8412 -- Neighborhood Shopping Ctr,<NA>,4,1168130000001_2025.html
353260,1168130000001,Strip Shopping Center,1,1990,13054,Displayed,2026,Good,8412 -- Neighborhood Shopping Ctr,2007,1,1168130000001_2026.html
353261,1168130000001,Strip Shopping Center,2,1990,4958,NaN,2026,Average,8412 -- Neighborhood Shopping Ctr,<NA>,2,1168130000001_2026.html
353262,1168130000001,Strip Shopping Center,6,1990,11160,NaN,2026,Good,8412 -- Neighborhood Shopping Ctr,<NA>,3,1168130000001_2026.html
353263,1168130000001,Strip Shopping Center,7,1990,23030,NaN,2026,Good,8412 -- Neighborhood Shopping Ctr,<NA>,4,1168130000001_2026.html

In [ ]:
new = ['parcel_number','year', 'building_number', 'building','year_built',  'remodeled', 'type', 'style', 'quality', 'impr_sq_ft',
       'building_details',  
       'page_save']
df = df.reindex(columns=new)

In [ ]:
df.info(verbose=True,show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8330639 entries, 0 to 8330638
Data columns (total 12 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   parcel_number     8330639 non-null  object
 1   year              8330639 non-null  Int64
 2   building_number   8330639 non-null  int64
 3   building          8330639 non-null  int64
 4   year_built        8330639 non-null  Int64
 5   remodeled         1450134 non-null  Int64
 6   type              8330639 non-null  object
 7   style             8330639 non-null  object
 8   quality           8330632 non-null  object
 9   impr_sq_ft        8330639 non-null  Int64
 10  building_details  7630281 non-null  object
 11  page_save         8330639 non-null  object
dtypes: Int64(4), int64(2), object(6)
memory usage: 794.5+ MB

In [ ]:
df[df['parcel_number']=='1168130000001']

,parcel_number,year,building_number,building,year_built,remodeled,type,style,quality,impr_sq_ft,building_details,page_save
353240,1168130000001,2021,1,1,1990,2007,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,13054,Displayed,1168130000001_2021.html
353241,1168130000001,2021,2,2,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Average,4958,NaN,1168130000001_2021.html
353242,1168130000001,2021,3,6,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,11160,NaN,1168130000001_2021.html
353243,1168130000001,2021,4,7,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,23030,NaN,1168130000001_2021.html
353244,1168130000001,2022,1,1,1990,2007,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,13054,Displayed,1168130000001_2022.html
353245,1168130000001,2022,2,2,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Average,4958,NaN,1168130000001_2022.html
353246,1168130000001,2022,3,6,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,11160,NaN,1168130000001_2022.html
353247,1168130000001,2022,4,7,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,23030,NaN,1168130000001_2022.html
353248,1168130000001,2023,1,1,1990,2007,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,13054,Displayed,1168130000001_2023.html
353249,1168130000001,2023,2,2,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Average,4958,NaN,1168130000001_2023.html
353250,1168130000001,2023,3,6,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,11160,NaN,1168130000001_2023.html
353251,1168130000001,2023,4,7,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,23030,NaN,1168130000001_2023.html
353252,1168130000001,2024,1,1,1990,2007,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,13054,Displayed,1168130000001_2024.html
353253,1168130000001,2024,2,2,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Average,4958,NaN,1168130000001_2024.html
353254,1168130000001,2024,3,6,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,11160,NaN,1168130000001_2024.html
353255,1168130000001,2024,4,7,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,23030,NaN,1168130000001_2024.html
353256,1168130000001,2025,1,1,1990,2007,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,13054,Displayed,1168130000001_2025.html
353257,1168130000001,2025,2,2,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Average,4958,NaN,1168130000001_2025.html
353258,1168130000001,2025,3,6,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,11160,NaN,1168130000001_2025.html
353259,1168130000001,2025,4,7,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,23030,NaN,1168130000001_2025.html
353260,1168130000001,2026,1,1,1990,2007,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,13054,Displayed,1168130000001_2026.html
353261,1168130000001,2026,2,2,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Average,4958,NaN,1168130000001_2026.html
353262,1168130000001,2026,3,6,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,11160,NaN,1168130000001_2026.html
353263,1168130000001,2026,4,7,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,23030,NaN,1168130000001_2026.html

In [ ]:
result = {}

for col in df.columns:
    vals = df[col].astype(str)
    filtered = vals[vals.str.len() == 1].unique().tolist()
    
    if filtered: 
        result[col] = filtered
  
print(result)

{'building_number': ['1', '2', '3', '4', '5', '6', '7', '8', '9'], 'building': ['1', '2', '3', '4', '5', '6', '7', '8', '9'], 'year_built': ['0', '1'], 'remodeled': ['8'], 'impr_sq_ft': ['0', '7', '1', '3']}

In [ ]:
df[df['remodeled']==8]

,parcel_number,year,building_number,building,year_built,remodeled,type,style,quality,impr_sq_ft,building_details,page_save
3745837,1295860010001,2021,6,7,1960,8,Industrial Warehouse - Heavy - Non Metallic,9406 -- Industrial Warehouse,Average,4000,NaN,1295860010001_2021.html
3745851,1295860010001,2022,6,7,1960,8,Industrial Warehouse - Heavy - Non Metallic,9406 -- Industrial Warehouse,Average,4000,NaN,1295860010001_2022.html
3745865,1295860010001,2023,6,7,1960,8,Industrial Warehouse - Heavy - Non Metallic,9406 -- Industrial Warehouse,Average,4000,NaN,1295860010001_2023.html
3745879,1295860010001,2024,6,7,1960,8,Industrial Warehouse - Heavy - Non Metallic,9406 -- Industrial Warehouse,Average,4000,NaN,1295860010001_2024.html
3745893,1295860010001,2025,6,7,1960,8,Industrial Warehouse - Heavy - Non Metallic,9406 -- Industrial Warehouse,Average,4000,NaN,1295860010001_2025.html

In [ ]:
df[df['parcel_number']=='1295860010001']['building_number']

3745832     1
3745833     2
3745834     3
3745835     4
3745836     5
           ..
3745911    10
3745912    11
3745913    12
3745914    13
3745915    14
Name: building_number, Length: 84, dtype: int64

In [ ]:
df[df['remodeled']==2099]

,parcel_number,year,building_number,building,year_built,remodeled,type,style,quality,impr_sq_ft,building_details,page_save
4256445,0880450000011,2021,1,1,1961,2099,Residential Single Family,101 -- Residential 1 Family,Average,1982,Displayed,0880450000011_2021.html

In [ ]:
df[df['parcel_number']=='0880450000011']

,parcel_number,year,building_number,building,year_built,remodeled,type,style,quality,impr_sq_ft,building_details,page_save
4256445,0880450000011,2021,1,1,1961,2099,Residential Single Family,101 -- Residential 1 Family,Average,1982,Displayed,0880450000011_2021.html
4256446,0880450000011,2022,1,1,1961,2017,Residential Single Family,101 -- Residential 1 Family,Average,1982,Displayed,0880450000011_2022.html
4256447,0880450000011,2023,1,1,1961,2017,Residential Single Family,101 -- Residential 1 Family,Average,1982,Displayed,0880450000011_2023.html
4256448,0880450000011,2024,1,1,1961,2017,Residential Single Family,101 -- Residential 1 Family,Average,1982,Displayed,0880450000011_2024.html
4256449,0880450000011,2025,1,1,1961,2017,Residential Single Family,101 -- Residential 1 Family,Average,1982,Displayed,0880450000011_2025.html
4256450,0880450000011,2026,1,1,1961,2017,Residential Single Family,101 -- Residential 1 Family,Average,1982,Displayed,0880450000011_2026.html

In [ ]:


checks = {
    "Numeric 0": [0, 0.0],
    "String '0'": ['0', '00', '0.0','0 x 0 x 0'],
    "Hyphen '-'": ['-', '--', '---', '----'],
    "Symbols": ['+', '_', '=', '\\', '|', '!', '@', '`', '~', "'", '"', "''", '""'],
    "Question marks": ['?', '???', '??', '????', '?? 00000'],
    "Punctuation": ['%', '&', '^', '*', '(', ')', '[', ']', '{', '}'],
    "Dots / Slash": ['..', '...', '…', '', ' ', '/', '.'],
    "Unknown text": ['UNK','unk','Unknown','unknown','UNKNOWN','Unkown','Unkonw','UNKNOW'],
    "NA values": ['Na','N/A','N/a','n/A','n/ a','N.A','N/A/','null','none','nan','nil','None','NONE'],
    "Other": ['XXXXX','x x','unsure','undeveloped']
}

# Flatten junk values
all_bad_values = [v for vals in checks.values() for v in vals]

junk_mask = df.isin(all_bad_values)

print("===== DETAILED JUNK VALUE REPORT =====")

for category, values in checks.items():
    print(f"\n=== {category} ===")
    
    columns_with_junk = []   # store columns
    
    for col in df.columns:
        counts = df[col].value_counts(dropna=False)
        junk_counts = counts[counts.index.isin(values)]
        
        if not junk_counts.empty:
            columns_with_junk.append(col)
            
            print(f"\nColumn: {col}")
            for val, cnt in junk_counts.items():
                print(f"{val} : {cnt}")
    
    # NEW PART: show columns list
    if columns_with_junk:
        print(f"\nColumns containing {category}: {columns_with_junk}")

# Total junk count per column
total_junk_counts = junk_mask.sum()
total_junk_counts = total_junk_counts[total_junk_counts > 0]

print("\n===== TOTAL JUNK COUNT PER COLUMN =====")
print(total_junk_counts)

===== DETAILED JUNK VALUE REPORT =====

=== Numeric 0 ===

Column: year_built
0 : 20

Column: impr_sq_ft
0 : 5040

Columns containing Numeric 0: ['year_built', 'impr_sq_ft']

=== String '0' ===

=== Hyphen '-' ===

=== Symbols ===

=== Question marks ===

=== Punctuation ===

=== Dots / Slash ===

=== Unknown text ===

=== NA values ===

=== Other ===

===== TOTAL JUNK COUNT PER COLUMN =====
year_built      20
impr_sq_ft    5040
dtype: Int64

In [ ]:
df[df['impr_sq_ft']==2049]

,parcel_number,year,building_number,building,year_built,remodeled,type,style,quality,impr_sq_ft,building_details,page_save
8494,0291720030021,2021,1,1,1996,<NA>,Residential Single Family,101 -- Residential 1 Family,Good,2049,Displayed,0291720030021_2021.html
8495,0291720030021,2022,1,1,1996,<NA>,Residential Single Family,101 -- Residential 1 Family,Good,2049,Displayed,0291720030021_2022.html
8496,0291720030021,2023,1,1,1996,<NA>,Residential Single Family,101 -- Residential 1 Family,Good,2049,Displayed,0291720030021_2023.html
8497,0291720030021,2024,1,1,1996,<NA>,Residential Single Family,101 -- Residential 1 Family,Good,2049,Displayed,0291720030021_2024.html
8498,0291720030021,2025,1,1,1996,<NA>,Residential Single Family,101 -- Residential 1 Family,Good,2049,Displayed,0291720030021_2025.html
...,...,...,...,...,...,...,...,...,...,...,...,...
8317616,1260800030010,2021,1,1,2006,<NA>,Residential Single Family,101 -- Residential 1 Family,Average,2049,Displayed,1260800030010_2021.html
8317617,1260800030010,2022,1,1,2006,<NA>,Residential Single Family,101 -- Residential 1 Family,Average,2049,Displayed,1260800030010_2022.html
8317618,1260800030010,2023,1,1,2006,<NA>,Residential Single Family,101 -- Residential 1 Family,Average,2049,Displayed,1260800030010_2023.html
8317619,1260800030010,2024,1,1,2006,<NA>,Residential Single Family,101 -- Residential 1 Family,Average,2049,Displayed,1260800030010_2024.html
8317620,1260800030010,2025,1,1,2006,<NA>,Residential Single Family,101 -- Residential 1 Family,Average,2049,Displayed,1260800030010_2025.html

## Replacing the '0' value with null from column 'impr_sq_ft' and 'year_built'

In [ ]:
colss =  ['impr_sq_ft', 'year_built']
df[colss] = df[colss].replace(0,np.nan)
df[colss]

         impr_sq_ft  year_built
0             22608        1900
1             22608        1900
2             22608        1900
3             22608        1900
4             22608        1900
...             ...         ...
8330634        1374        1979
8330635        1374        1979
8330636        1374        1979
8330637        1374        1979
8330638        1374        1979

[8330639 rows x 2 columns]

In [ ]:
checks = {
    "Numeric 0": [0, 0.0],
    "String '0'": ['0', '00', '0.0','0 x 0 x 0'],
    "Hyphen '-'": ['-', '--', '---', '----'],
    "Symbols": ['+', '_', '=', '\\', '|', '!', '@', '`', '~', "'", '"', "''", '""'],
    "Question marks": ['?', '???', '??', '????', '?? 00000'],
    "Punctuation": ['%', '&', '^', '*', '(', ')', '[', ']', '{', '}'],
    "Dots / Slash": ['..', '...', '…', '', ' ', '/', '.'],
    "Unknown text": ['UNK','unk','Unknown','unknown','UNKNOWN','Unkown','Unkonw','UNKNOW'],
    "NA values": ['Na','N/A','N/a','n/A','n/ a','N.A','N/A/','null','none','nan','nil','None','NONE'],
    "Other": ['XXXXX','x x','unsure','undeveloped']
}

# Flatten junk values
all_bad_values = [v for vals in checks.values() for v in vals]

junk_mask = df.isin(all_bad_values)

print("===== DETAILED JUNK VALUE REPORT =====")

for category, values in checks.items():
    print(f"\n=== {category} ===")
    
    columns_with_junk = []   # store columns
    
    for col in df.columns:
        counts = df[col].value_counts(dropna=False)
        junk_counts = counts[counts.index.isin(values)]
        
        if not junk_counts.empty:
            columns_with_junk.append(col)
            
            print(f"\nColumn: {col}")
            for val, cnt in junk_counts.items():
                print(f"{val} : {cnt}")
    
    # NEW PART: show columns list
    if columns_with_junk:
        print(f"\nColumns containing {category}: {columns_with_junk}")

# Total junk count per column
total_junk_counts = junk_mask.sum()
total_junk_counts = total_junk_counts[total_junk_counts > 0]

print("\n===== TOTAL JUNK COUNT PER COLUMN =====")
print(total_junk_counts)

===== DETAILED JUNK VALUE REPORT =====

=== Numeric 0 ===

=== String '0' ===

=== Hyphen '-' ===

=== Symbols ===

=== Question marks ===

=== Punctuation ===

=== Dots / Slash ===

=== Unknown text ===

=== NA values ===

=== Other ===

===== TOTAL JUNK COUNT PER COLUMN =====
Series([], dtype: Int64)

In [ ]:
df[df['parcel_number']=='1113770000001']

,parcel_number,year,building_number,building,year_built,remodeled,type,style,quality,impr_sq_ft,building_details,page_save
6073707,1113770000001,2021,1,1,1981,<NA>,Office Bldgs. Hi-Rise (5+ Stories),8344 -- Office Building,Excellent,324758,Displayed,1113770000001_2021.html
6073708,1113770000001,2021,2,2,1981,<NA>,Parking Garage,8345 -- Parking Structure,Average,340792,NaN,1113770000001_2021.html
6073709,1113770000001,2022,1,1,1981,<NA>,Office Bldgs. Hi-Rise (5+ Stories),8344 -- Office Building,Excellent,324758,Displayed,1113770000001_2022.html
6073710,1113770000001,2022,2,2,1981,<NA>,Parking Garage,8345 -- Parking Structure,Average,340792,NaN,1113770000001_2022.html
6073711,1113770000001,2023,1,1,1981,<NA>,Office Bldgs. Hi-Rise (5+ Stories),8344 -- Office Building,Excellent,324758,Displayed,1113770000001_2023.html
6073712,1113770000001,2024,1,1,1981,<NA>,Office Bldgs. Hi-Rise (5+ Stories),8344 -- Office Building,Excellent,324758,Displayed,1113770000001_2024.html
6073713,1113770000001,2025,1,1,1981,<NA>,Office Bldgs. Hi-Rise (5+ Stories),8344 -- Office Building,Excellent,324758,Displayed,1113770000001_2025.html
6073714,1113770000001,2026,1,1,1981,<NA>,Office Bldgs. Hi-Rise (5+ Stories),8344 -- Office Building,Excellent,324758,Displayed,1113770000001_2026.html
6772261,1113770000001,2023,1,2,1981,<NA>,Parking Garage,8345 -- Parking Structure,Average,340792,NaN,1113770000001_2023.html
6772262,1113770000001,2024,1,2,1981,<NA>,Parking Garage,8345 -- Parking Structure,Average,340792,NaN,1113770000001_2024.html
6772263,1113770000001,2025,1,2,1981,<NA>,Parking Garage,8345 -- Parking Structure,Average,340792,NaN,1113770000001_2025.html
6772264,1113770000001,2026,1,2,1981,<NA>,Parking Garage,8345 -- Parking Structure,Average,340792,NaN,1113770000001_2026.html

In [ ]:
df.columns

Index(['parcel_number', 'year', 'building_number', 'building', 'year_built',
       'remodeled', 'type', 'style', 'quality', 'impr_sq_ft',
       'building_details', 'page_save'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8330639 entries, 0 to 8330638
Data columns (total 12 columns):
 #   Column            Dtype
---  ------            -----
 0   parcel_number     object
 1   year              Int64
 2   building_number   int64
 3   building          int64
 4   year_built        Int64
 5   remodeled         Int64
 6   type              object
 7   style             object
 8   quality           object
 9   impr_sq_ft        Int64
 10  building_details  object
 11  page_save         object
dtypes: Int64(4), int64(2), object(6)
memory usage: 794.5+ MB

In [ ]:
df[df['parcel_number']=='1113770000001']

,parcel_number,year,building_number,building,year_built,remodeled,type,style,quality,impr_sq_ft,building_details,page_save
6073707,1113770000001,2021,1,1,1981,<NA>,Office Bldgs. Hi-Rise (5+ Stories),8344 -- Office Building,Excellent,324758,Displayed,1113770000001_2021.html
6073708,1113770000001,2021,2,2,1981,<NA>,Parking Garage,8345 -- Parking Structure,Average,340792,NaN,1113770000001_2021.html
6073709,1113770000001,2022,1,1,1981,<NA>,Office Bldgs. Hi-Rise (5+ Stories),8344 -- Office Building,Excellent,324758,Displayed,1113770000001_2022.html
6073710,1113770000001,2022,2,2,1981,<NA>,Parking Garage,8345 -- Parking Structure,Average,340792,NaN,1113770000001_2022.html
6073711,1113770000001,2023,1,1,1981,<NA>,Office Bldgs. Hi-Rise (5+ Stories),8344 -- Office Building,Excellent,324758,Displayed,1113770000001_2023.html
6073712,1113770000001,2024,1,1,1981,<NA>,Office Bldgs. Hi-Rise (5+ Stories),8344 -- Office Building,Excellent,324758,Displayed,1113770000001_2024.html
6073713,1113770000001,2025,1,1,1981,<NA>,Office Bldgs. Hi-Rise (5+ Stories),8344 -- Office Building,Excellent,324758,Displayed,1113770000001_2025.html
6073714,1113770000001,2026,1,1,1981,<NA>,Office Bldgs. Hi-Rise (5+ Stories),8344 -- Office Building,Excellent,324758,Displayed,1113770000001_2026.html
6772261,1113770000001,2023,1,2,1981,<NA>,Parking Garage,8345 -- Parking Structure,Average,340792,NaN,1113770000001_2023.html
6772262,1113770000001,2024,1,2,1981,<NA>,Parking Garage,8345 -- Parking Structure,Average,340792,NaN,1113770000001_2024.html
6772263,1113770000001,2025,1,2,1981,<NA>,Parking Garage,8345 -- Parking Structure,Average,340792,NaN,1113770000001_2025.html
6772264,1113770000001,2026,1,2,1981,<NA>,Parking Garage,8345 -- Parking Structure,Average,340792,NaN,1113770000001_2026.html

In [ ]:
df[df['page_save']=='1166790050010_2021.html']

,parcel_number,year,building_number,building,year_built,remodeled,type,style,quality,impr_sq_ft,building_details,page_save
149035,1166790050010,2021,1,1,1987,<NA>,Residential Single Family,101 -- Residential 1 Family,Average,2049,Displayed,1166790050010_2021.html

In [ ]:
df[df['page_save']=='1168130000001_2021.html']

,parcel_number,year,building_number,building,year_built,remodeled,type,style,quality,impr_sq_ft,building_details,page_save
353240,1168130000001,2021,1,1,1990,2007,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,13054,Displayed,1168130000001_2021.html
353241,1168130000001,2021,2,2,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Average,4958,NaN,1168130000001_2021.html
353242,1168130000001,2021,3,6,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,11160,NaN,1168130000001_2021.html
353243,1168130000001,2021,4,7,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,23030,NaN,1168130000001_2021.html

In [ ]:
df.info()

In [ ]:
df.drop(columns='building_details',inplace=True)

In [ ]:
df.info()

In [ ]:
df

In [ ]:
df[df['parcel_number']=='1168130000001']

,parcel_number,year,building_number,building,year_built,remodeled,type,style,quality,impr_sq_ft,building_details,page_save
353240,1168130000001,2021,1,1,1990,2007,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,13054,Displayed,1168130000001_2021.html
353241,1168130000001,2021,2,2,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Average,4958,NaN,1168130000001_2021.html
353242,1168130000001,2021,3,6,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,11160,NaN,1168130000001_2021.html
353243,1168130000001,2021,4,7,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,23030,NaN,1168130000001_2021.html
353244,1168130000001,2022,1,1,1990,2007,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,13054,Displayed,1168130000001_2022.html
353245,1168130000001,2022,2,2,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Average,4958,NaN,1168130000001_2022.html
353246,1168130000001,2022,3,6,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,11160,NaN,1168130000001_2022.html
353247,1168130000001,2022,4,7,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,23030,NaN,1168130000001_2022.html
353248,1168130000001,2023,1,1,1990,2007,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,13054,Displayed,1168130000001_2023.html
353249,1168130000001,2023,2,2,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Average,4958,NaN,1168130000001_2023.html
353250,1168130000001,2023,3,6,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,11160,NaN,1168130000001_2023.html
353251,1168130000001,2023,4,7,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,23030,NaN,1168130000001_2023.html
353252,1168130000001,2024,1,1,1990,2007,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,13054,Displayed,1168130000001_2024.html
353253,1168130000001,2024,2,2,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Average,4958,NaN,1168130000001_2024.html
353254,1168130000001,2024,3,6,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,11160,NaN,1168130000001_2024.html
353255,1168130000001,2024,4,7,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,23030,NaN,1168130000001_2024.html
353256,1168130000001,2025,1,1,1990,2007,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,13054,Displayed,1168130000001_2025.html
353257,1168130000001,2025,2,2,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Average,4958,NaN,1168130000001_2025.html
353258,1168130000001,2025,3,6,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,11160,NaN,1168130000001_2025.html
353259,1168130000001,2025,4,7,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,23030,NaN,1168130000001_2025.html
353260,1168130000001,2026,1,1,1990,2007,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,13054,Displayed,1168130000001_2026.html
353261,1168130000001,2026,2,2,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Average,4958,NaN,1168130000001_2026.html
353262,1168130000001,2026,3,6,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,11160,NaN,1168130000001_2026.html
353263,1168130000001,2026,4,7,1990,<NA>,Strip Shopping Center,8412 -- Neighborhood Shopping Ctr,Good,23030,NaN,1168130000001_2026.html

In [ ]:
df

,parcel_number,year,building_number,building,year_built,remodeled,type,style,quality,impr_sq_ft,building_details,page_save
0,0010020000016,2021,1,1,1900,<NA>,Restaurant,8350 -- Restaurant,Low,22608,Displayed,0010020000016_2021.html
1,0010020000016,2022,1,1,1900,2021,Bar/Lounge,8441 -- Cocktail Lounge,Average,22608,Displayed,0010020000016_2022.html
2,0010020000016,2023,1,1,1900,2021,Bar/Lounge,8441 -- Cocktail Lounge,Average,22608,Displayed,0010020000016_2023.html
3,0010020000016,2024,1,1,1900,2021,Bar/Lounge,8441 -- Cocktail Lounge,Average,22608,Displayed,0010020000016_2024.html
4,0010020000016,2025,1,1,1900,2021,Bar/Lounge,8441 -- Cocktail Lounge,Average,22608,Displayed,0010020000016_2025.html
...,...,...,...,...,...,...,...,...,...,...,...,...
8330634,1955020050280,2022,1,1,1979,<NA>,Residential Single Family,101 -- Residential 1 Family,Average,1374,Displayed,1955020050280_2022.html
8330635,1955020050280,2023,1,1,1979,<NA>,Residential Single Family,101 -- Residential 1 Family,Average,1374,Displayed,1955020050280_2023.html
8330636,1955020050280,2024,1,1,1979,<NA>,Residential Single Family,101 -- Residential 1 Family,Average,1374,Displayed,1955020050280_2024.html
8330637,1955020050280,2025,1,1,1979,<NA>,Residential Single Family,101 -- Residential 1 Family,Average,1374,Displayed,1955020050280_2025.html
8330638,1955020050280,2026,1,1,1979,<NA>,Residential Single Family,101 -- Residential 1 Family,Average,1374,Displayed,1955020050280_2026.html

In [ ]:
df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8330639 entries, 0 to 8330638
Data columns (total 12 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   parcel_number     8330639 non-null  object
 1   year              8330639 non-null  Int64
 2   building_number   8330639 non-null  int64
 3   building          8330639 non-null  int64
 4   year_built        8330619 non-null  Int64
 5   remodeled         1450134 non-null  Int64
 6   type              8330639 non-null  object
 7   style             8330639 non-null  object
 8   quality           8330632 non-null  object
 9   impr_sq_ft        8325599 non-null  Int64
 10  building_details  7630281 non-null  object
 11  page_save         8330639 non-null  object
dtypes: Int64(4), int64(2), object(6)
memory usage: 794.5+ MB

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
cols = df.columns.difference(['parcel_number', 'page_save'])
 
mask = df[cols].isna().all(axis=1)
df[mask]

Empty DataFrame
Columns: [parcel_number, year, building_number, building, year_built, remodeled, type, style, quality, impr_sq_ft, building_details, page_save]
Index: []

In [ ]:
df

,parcel_number,year,building_number,building,year_built,remodeled,type,style,quality,impr_sq_ft,building_details,page_save
0,0010020000016,2021,1,1,1900,<NA>,Restaurant,8350 -- Restaurant,Low,22608,Displayed,0010020000016_2021.html
1,0010020000016,2022,1,1,1900,2021,Bar/Lounge,8441 -- Cocktail Lounge,Average,22608,Displayed,0010020000016_2022.html
2,0010020000016,2023,1,1,1900,2021,Bar/Lounge,8441 -- Cocktail Lounge,Average,22608,Displayed,0010020000016_2023.html
3,0010020000016,2024,1,1,1900,2021,Bar/Lounge,8441 -- Cocktail Lounge,Average,22608,Displayed,0010020000016_2024.html
4,0010020000016,2025,1,1,1900,2021,Bar/Lounge,8441 -- Cocktail Lounge,Average,22608,Displayed,0010020000016_2025.html
...,...,...,...,...,...,...,...,...,...,...,...,...
8330634,1955020050280,2022,1,1,1979,<NA>,Residential Single Family,101 -- Residential 1 Family,Average,1374,Displayed,1955020050280_2022.html
8330635,1955020050280,2023,1,1,1979,<NA>,Residential Single Family,101 -- Residential 1 Family,Average,1374,Displayed,1955020050280_2023.html
8330636,1955020050280,2024,1,1,1979,<NA>,Residential Single Family,101 -- Residential 1 Family,Average,1374,Displayed,1955020050280_2024.html
8330637,1955020050280,2025,1,1,1979,<NA>,Residential Single Family,101 -- Residential 1 Family,Average,1374,Displayed,1955020050280_2025.html
8330638,1955020050280,2026,1,1,1979,<NA>,Residential Single Family,101 -- Residential 1 Family,Average,1374,Displayed,1955020050280_2026.html

## Placing the file

In [ ]:
df.to_csv(r"D:\Khushi\[XB3421] Data Extraction For USA Counties_Virec\us\texas\harris\prop\Cleaned_Data\us_tx_48201_data_prop_building-summary_silver_20260501.csv",index=False)
df